---
title: "Samantha XVI"
author: "Elizabeth Kolling"
date: "2025-11-22T08:54:00"
categories: [Samantha]
description: " "
---

[insert more]

What reason did she have to stay? How long could she distract herself with time spent in cafes before she realized she wasn't moving forward anymore. If ever, she thought, and shit was what she said to herself as she felt the change of pressure from (a higher place) up above. She inhaled sharply to counteract the flow and wiped her nose with the soft back of her hand. People say they know a place like the back of their hand, but why, was what she asked herself (as she held her nose towards the heavens). It's the inner part that grips and touches, feels all, and eventually lets go. She knew the place now like the palm of her hand, and the deep crimson across was like the makeup artist’s swatch of lipstick. She had sat in her chair and looked into the mirror.

“Do you have a handkerchief, or a tissue?”

“No, sorry.”

The stranger on the street picked up speed, and Samantha turned to face the wall. She lifted her toe with a sigh, lodging it between the grooves of two stones, and rested her backpack on her leg. Her back was to the street as she held her nose towards the heavens and thought *hell is other people*. 

She continued up Pearl Street to where it intersected Oliver, and opened the door to the interior. 

"Can I use your restroom? I have a bloody nose."

"Yeah, of course. Down that way." 

[insert more]