---
title: "Maximilian II"
author: "Elizabeth Kolling"
date: "2025-06-12T10:00:00"
categories: 
description: " "
---


Max grew up poor in New York City, but he was talented, a class standout, and he learned to survive for the sake of his future.

His family moved from Florida for a fresh start, and his father moved back after the divorce, so he didn’t really know his father on a personal level but his father loved him enough to stay in touch. They talked about the un-touchy things, once or twice a month. His mother cheated with his kindergarten teacher, as he pieced it together, which meant he and his sister had to share a room and he was ever skeptical of the education system. Their apartment was a two-bedroom, one bath, small and naturally dark. He preferred the lights off, because the light-emitting diodes blinded him. The rent-controlled co-op building was pre-war, on the Upper West Side, and he had to get glasses in the second grade. At least, that’s what he told the kids in school one day after weeks of calling him names. 

“Near the Museum.”

He said this to one kid by the cubbies, and then started making his rounds each recess. 

The natural history buffs would be all buggy-eyed, thinking it was so cool, ‘cause the Museum of Natural History was all the rage at that age. He’d be relieved momentarily, knowing deep down he was a phony. They'd invite him to tag along after school for the walks home. He’d peel away from the group walking downtown around 81st and Columbus and walk slowly towards Central Park West until he was sure no one was watching  him. Then, he’d walk back up—sixteen or so blocks and two avenues west until he reached Manhattan Valley.  

He was ashamed of who he was—where he lived, where he came from. He felt the shame of association, which turned into deep dislike and then eventual indifference. He didn’t really like his father or his mother or his sister. His parents weren’t the smartest people, and his sister was a cry baby. He hated how quick she was to play victim and put herself at the center. 

He hadn’t always felt this way, she’d eventually remind him (when he started acting really sour towards her). There were the first few times after the divorce, where he’d get out of bed to console his sister. He’d tap her shoulder, brush his thumb across her temple towards her part and then tuck her hair behind her ear. He’d *shh shh shhhh* her until the tears down her cheek were dry, and she’d fall asleep.

His friends were his family, and he found any good enough reason to belong elesewhere. 