---
title: "Sara VI"
author: "Elizabeth Kolling"
date: "2025-11-08T10:38:00"
categories: [Sara]
description: " "
---


(Sara is off to college, majoring in English).

Sara knocks on the open door of his office in the building that houses Berkeley English Department. 

“Come in.
 
“Hi, Professor.” 

“How can I help you?”

“I just had a question after last lecture.”

“Okay.”

“Uh, about what you were saying about—” 

“You know what I’ve been thinking about?” 

“Uh-huh.”

“What’s a lazy start to a novel.”

“What?”

“That critical point, where consciousness meets unconsciousness.”

“You mean when a character wakes up.”

“She woke up. He awakens. I mean, it’s an effective way to set a clean slate. But it’s lazy.” 

“It’s a common deployment, no?”

“Very.” 

Beat. 

“If I were to write a novel, I’d start with something messy," said Sara. "Sorry, I mean—” 

“Would you mind reading this?”

Dr. Dribben hands her the manuscript that she’s been eyeing on his desk.

“The whole thing?”

“Just the first page.” 

“Okay.”

She starts to read it to herself.

“Aloud, I mean.”

“Oh, right,” she said, starting to read. "Keys to the Chevy Silverado jostled against the chain in hand, as the man walked the quiet drive." 

The keychain was Jesus on the cross who died for their sins, and the first left turn off Gold Ridge was a mixture of dirt and gravel, reinforced with underlayment for erosion during the rainy season, and in need of some work. Bits of black fabric peeked through, but this was last year’s undoing and the season was summer. The sun cut through the pale and the fog was lifting, though the sign and those four words still loomed in the mind of the man who walked with a limp towards the house: private property, no trespassing. 

The man looked back to see his pickup still there where he parked it, with its front wheels angled towards a family of turkey vultures, stoic, on some dead limbs nearby. The Live Oak rotting from the inside out reminded him of his aunt, Eunice, whose breath had been so bad that he fainted one Fourth of July of his youth from having to hold his own around her.
    
“One day,” she had said. “Someone’s gonna sock you straight in the face. Just make sure it ain't me, and get back to work on that ditch in the driveway. Winter’s comin’.”

“But mom and pop say today’s a holiday.”

The words loomed over him, but he rolled up his sleeves any way and walked on towards the front door. The man knocked twice. Too soft, he thought, pressing hard against the mahogany. Once more, he bent his wrist towards his heart and let the knuckles knock like the knees under the table of two lovers who would never know each other. The knock made the man think of Fran, whose family had moved away in the fourth grade. He thought it a shame to lose track of her. But this time, he knocked three times with confidence before stepping back. He was unassured because of who might be on the other side of the door, though there was a sure fire. Smoke, coming out the chimney, but no one home. Sure, thought the man as he raised his leg and twisted himself around. He kicked rocks on the way back and dragged his lone sole across the quiet drive, occasionally looking up with a long sigh and longing eye. He was surrounded on all sides, with one leg but skin in the game. 


