---
title: "Levi II"
author: "Elizabeth Kolling"
date: "2025-06-27"
categories: 
description: " "
---

The teachers were telling him that hypos was short for melancholia, but Levi had read it differently.

“When I read that,” he said to Ethan. “I thought it was short for hypodermic.”

“Hypodermic, like under the skin?”

“Yeah, like hypodermic needle,” he said. “It got me thinking…”

“Yeah?”

“What if Ishmael is a drug addict?”

“I don’t know, what kind of drug addict would sail away to sea? I’d think a drug addict would prefer to be on land, and in the streets.”

“I guess,” Levi said, pausing to think for a second. “But I mean, read this section.” 

He opened the book to the first page of the first chapter, and started reading aloud the first paragraph.

“Uh-huh,” Ethan said. 

“If Ishmael were depressed, wouldn’t it take a strong moral principle to leave his shitty apartment and step outside, into the street? Here, it’d be saying that when he’s depressed he can’t help himself from getting up and going out, which is hard for me to believe. I feel like if you’re depressed, you just want to sit inside and waste the day away, without motivation or a mission. Now, if you’re a drug addict whose hypos or addiction is getting the better of you, then it takes a strong moral principle to not defer to the street, where your supplier and next high are, or help yourself from knocking people’s hats off. I think the hats part is not to be taken literally. It’s a literary flare, which may be taken to mean getting in a fight, but it could also refer to someone who is just flailing their arms about, swinging aimlessly because they’re in some sort of drug-induced psychosis. I’ve seen that in San Francisco before, especially where the open-air drug markets are, in the Tenderloin, near Turk Street and Hyde. Any way, what else? Oh, yeah! Melville also uses the word high, ‘high time’ he says, which to me connotes drugs and drug use. I don’t know. The need to get to the sea, is maybe the need to save himself, to cut himself off from his assured supply, you know, ashore.”

“Well, what about the line about pistol and ball?” Ethan said. “Doesn’t that suggest suicide stemming from depression.”

“You could read it like that, but I also think it applies to the lens of addiction.”

“I’m listening.”

“Pistol and ball is basically suicide, and drug use is kind of this implicit suicide, because you’re killing yourself. So, taking to the sea could be Ishmael’s substitute for pistol and ball, i.e. doing drugs, i.e. overdosing, i.e. killing himself.” 

“Okay, then what about Cato?”

“Cato?”

“Yeah, in the line that follows. Cato died by suicide.” 

“He stabbed himself with a sword, and maybe Ishmael stabbed himself with a needle.” 