---
title: "Freddie VII"
author: "Elizabeth Kolling"
date: "2025-12-22T19:00:00"
categories: [Freddie]
description: " "
---


[after Monday at the bakery]

"I mean, I was just wondering. If you knew you had cancer, it spread everywhere, and you didn't have much time left, how would that affect your choices?"

"You'd choose differently?"

"Would you? I'm not trying to tell you how to live your life, or anyone else in this place for that matter, but personally...if it were...I'd go with...I don't know."

"I've got to go."

[insert more]

He thought about it on the way home, how it takes place during the holidays.

(It’s about businessmen debating the pros and cons of a railway extending to their coastal town, and the main male character is the owner of a shipping firm. There are a bunch of women doing needlepoint in the house and the first bit is them gossiping about this and that. In particular, they’re discussing how the entry of a traveling theatre company had dismantled the moral constitution of the town, and they’re reminiscing about the  *good old days*. The men have a more optimistic view of the moral foundation of the town, while the women are more pessimistic. They keep asking the men to include them in their discussion about the railway, but the men keep claiming they wouldn’t understand. Other minor plot is the shipowner son who is 13 is playing with a gun and pointing it at people like Hilmar, so I can only wonder what will happen next.)

