---
title: "Laura"
author: "Elizabeth Kolling"
date: "2025-06-04"
categories: 
description: " "
---

I saw him in the street that day in early June, hand on her shoulder, with her arm around his waist.

Wait, I remember. She was wearing a wide brim, and the hat was like her ankle-cut linen pants: white. It was the kind of white that no working woman or man would or could ever wear. She was one of those mothers who waded through the mornings and somehow stumbled upon afternoon, waiting for the time to turn to two. She’d pack a snack and make her way to the elementary school pick-up zone, where the first car in line belonged to the other Jennifer in front of her. Her name was Laura Chase and she was the same as the other mothers there, with hours to kill and always complaining, claiming to be busy and not like mine who was hard-working but had taste about her. In her free time, Laura liked to talk about the rounded notes of red wine and sit on the back porch of her million and four dollar house, where the nearby pool was heated and salt water. Years later, when no one was home to swim in it, she’d invite her boyfriend over for a quick dip, in and out, or her son’s friends from high school who were going to the local college a few towns over. 

They even called it community.

