---
title: "Maximilian III"
author: "Elizabeth Kolling"
date: "2025-06-22"
categories: 
description: " "
---


He wanted Max to tell it to him (and the class) how he saw it. So he told him, *picture this:*

“A substantial man (tall, round about the countenance, swollen gut) in Washington Square reaches into a trash can. He considers it (the bagel), and walks on to the next. He does the exact same thing, except this time it’s a bacon, egg and cheese. He’s doing a circle around the fountain, like clock work, and by the time he comes around again he has an adequate stash. He takes his grocery cart to a nearby bench (of all the empty benches down wind of the public restrooms, it’s the one next to mine). He sits for a second. Then, he spots another trash can farther afield (untouched) and walks away. He walks back. He sits again and dips his hand down into his pocket. He chucks the poppyseed with cream cheese to a family of field sparrows. The field sparrows are pecking, and the piece of lightly toasted bread is shooting up and doing flips, ultimately migrating across the concrete to the place just beyond my feet. All of a sudden, a pigeon swoops in and starts pecking. Some of the swallows are scared away, but a few determined ones remain."

Max stopped talking, and looked out at the rows of his concerned classmates. Maddie, his crush, was looking right at him with reluctant judgement in her eyes as Sara leaned across the aisle and whispered something into her ear. He couldn't hear what Sara was saying, but he could tell what Maddie was thinking. 

"What I'm trying to say is, is this was a homeless man who didn't have anything to eat so he turned to digging through the throwaways, but still somehow he was overweight, maybe unhappy, and he threw what he did find to the birds first. Any way, I’m watching these birds fight for their right to feed, and I’m there thinking these aren’t sparrows. These are wolves in sheep’s clothing. Call it survival. This is a city of seagulls. Okay, that’s all. Thank you.” 

"Thank you," He said to Max. "Does anyone have Questions?" 

Sara's hand shot straight up.

"Yes, Sara."

"I don't think this homeless man is altruistic. I mean, are birds supposed to eat human food? I don't think it's good for them, and now they have this dependence on this homeless man who may be an unreliable food source in the future."

"Thank you, Sara. Max, would you like to respond?"

Max looked at Sara, and then at Maddie. 

"Stare at a painting long enough and it doesn't look all that impressive. Some of the lines are messy and less precise than we would've liked. I guess, my answer is that...sometimes, we can overcomplicate niceness or look for the ill will of good intentions."  

"Thanks, Max," he said. "Sara, does that answer your question?"

"Not really, Mr. P." 