---
title: "Laura IV"
author: "Elizabeth Kolling"
date: "2025-07-05"
categories: [Laura]
description: " "
---


"So, how was the party for you," her son asked.

Laura was sitting on the couch with her feet on the leather ottoman, looking relaxed, reading *Vogue Living*. 

"Oh, it was just lovely, I talked to Cheryl for a while, you know, your assistant head of school. She has some great ideas about how you can make your applications more competitive. Any way, I know it's the weekend. I'm just so happy how it turned out, people really seemed to be enjoying themselves. Did you have fun with your friends, honey?" 

"Did you talk to Samantha?"

"Um," she said, now serious. "Well, we three spoke in the beginning, remember?"

"Mom, seriously. You said hello and then beelined it for the tablecloths."

"Ethan, come on."

"Did you talk to her at all?"

"She could have offered to help with that." 

"She literally did offer. You just chose to ignore her."

"You know, honey, I was really busy yesterday. First the ribs, and then getting a last-minute red, white, and blue cake after the cupcakes turned out pink. I was putting out small fires everywhere, and I hardly got to stop for a slice of watermelon."

“Mom,” he said. “I don't want to fight with you. I'm not trying to corner you. I just want you to know that it means a lot to me and Samantha that you get to know her.”

“I know.”

“She’s my girlfriend, she’s been my girlfriend.”

“How many months has it been?”

“A lot of months, mom, and you don’t even know one beneath the surface thing about her.”

“Not true,” she said. “I know she’s a talented actor.”

“Mom.”

“Actress, I mean.”

“That’s because I told you that, but have you ever even asked her about it?”

“Is actress an offensive term?”

“I don’t know, Mom.”

“Actress,” she said, sounding it out and extending her jaw on the over-enunciation. “Actress, I think it implies less than.”

“Mom, I’m not talking to you about semantics. I’m trying to ask you to respect my relationship.”

“I do respect your relationships. I always have, honey.”

“You’re so hard to talk to sometimes.”

“I’m sorry.”

“You are a master deflector,” he said. “It gets on my nerves.”

“Let’s please not accuse each other. We have to support each other.”

“Can you at least come to her play?” 

“She’s in a play?”

“Yes, I told you.”

“Oh yes, a summer production?”

“Yes.” 

“You told me she was playing a supporting role.”

“Oh, so suddenly you do remember? And, yeah. So what?”

“Don’t roll your eyes at me, please. Sometimes it takes a second to recall. I have a lot of things on my plate, and a lot to keep track of. It’s not easy on my own now, and it’d be nice to receive some appreciation once in a while.” 

“Don’t bring Dad into this.”

“I’ll go to your girlfriend’s play,” she said. “Happy?” 