---
title: "Ethan XIV"
author: "Elizabeth Kolling"
date: "2025-07-15T22:25:00"
categories: 
description: " "
---

“They made it then,” said Levi. “To Nantucket.”

“Finally.” 

“Finally?”

“It feels like we’ve been trying to get there for many chapters,” said Ethan. “And nothing’s really happened.”

“What? So much has happened,” said Levi. “We’ve hardly scratched the surface.”

“Let’s see, so, we met Ishmael. We still don’t know much about him. We know he wants to get the heck out of Manhattan.”

“We know Manhattoes is another word for it, or at least means the southern tip.”

“The toes of the island.”

“Okay, lower Manhattan, here it says it’s the Financial District.” 

“That can’t be right, here, let me see,” said Ethan. “Melville must be referring to the Battery.” 

“Or wait…I see a Water Street…didn’t he mention a Water Street? Here, the chapel chapter, six, it says, ‘…New Bedford beats all Water Street and Wapping.’” 

“So he’s referring to this Water Street in the Battery?”

“No, the Seaport.”

“Oh, makes sense,” said Ethan. “That’s where the ports are.”

“Now, they’re mere piers.”