---
title: "Summer XVII"
author: "Elizabeth Kolling"
date: "2025-12-02T19:24:00"
categories: [Summer]
description: " "
---

[insert more]

It was Tuesday, which meant Summer had been moved in for nearly four weeks by the time of the unboxing. After an hour of breaking down, she sat between two towers. One was labeled miscellaneous. The other, winter clothes. She sat on the hardwood floor and looked at the spine of the one that stared back. She unclasped her fingers from her shins and stood. She walked to the shelf at the far wall and pulled the one apart from the others. Turning the hard cover towards the window, she flipped the first few pages to where the letter *F* bent towards the right margin. His handwriting was nice, not like she expected. It had this italicized quality to it that made every written word look a little bit more romantic than he had probably intended. Romantic, yet unsure, she thought. She wasn't sure, but she thought she knew why he had given it to her. She turned to the first chapter and read the first sentence as if it were the beginning, middle, and end. She closed the chapter and put the book back with the rest on the shelf. 

[insert more]
