---
title: "Samantha XIII"
author: "Elizabeth Kolling"
date: "2025-10-02T23:54:00"
categories: [Samantha]
description: " "
---



It was the second Thursday dinner, now a sort of tradition. Alexis sat on the same side as Freddie, across from Jonah who was next to Summer. Samantha sat at the head of the table and asked the two of them on either side of her, “Do you believe in soulmates?” Freddie and Summer looked at each other and then back at Samantha.

“No,” said Summer. “I don’t.” 

“And what about you?” 

Samantha was looking at Freddie, who had gone still and silent.

“Believe in soulmates...” said Freddie. “As in do I believe in them? Do I believe they exist? Do I believe in Santa Claus? Well, no, not since I was eight. So, I’d say no.” 

“So you both say no.”

“Yes,” they said together. 

“Okay,” said Samantha, lifting her glass for another sip of sauvignon blanc. “If there’s no *one* person out there for you, the can you be in love with more than one person at the same time? Can you be in love with two people at once?”

“Uh, I don’t think so,” said Summer. “I mean, two people, at different times, yes. But at the same time? I don’t know. One would have to detract from the other.”

“Yeah, I have to agree with Summer,” said Freddie.

“Well, alright.”

“How about you?” 

“What,” said Samantha flatly. “About me? I think there is such a thing as a soulmate. I don’t have anything against the idea of soulmates (plural), and I do think a person can be in love with two people at the same time.”

“I’d love to see it,” said Freddie. 

“See it? This isn’t for the eyes. This is all heart. You have to feel it, Freddie. In here.”

Samantha placed her hand over her chest and raised her glass, prompting the waiter to come over. 

[insert more]

Levi and Ethan were on her mind after midnight, on the L train home. It was technically Friday, the third of October, by the time Samantha got back, brushed, and showered. She reached for the collection of letters she’d been thinking about on the bedside table since halfway through dinner, when nostalgia or something similar overtook her. She read only part of the letter to Nelson Algren, Her love: 

*“I am not wise but rather a bit coward…Loving you so much means I can suffer very much because of you, when I say good bye, when you are ill-tempered or chiefly if you would love me less. It means now my happiness is in your hands, and in a way I should rather have kept it in mine. But, well, it is done now; I cannot help it any more, I have to admit this dependence, and I do it willingly since I love you.”* 

(Simone de Beauvoir; Friday, October 3, 1947)