---
title: "Public Records"
author: "Elizabeth Kolling"
date: "2025-07-16T08:14:00"
description: " "
---

Dear —, 

High street always leads to Fulton. I should have known, and I had had my fill.

“Boring Hill,” said a Rohan (not Rowan) of London outside Public Records afterwards. I had had hours to kill earlier, emerging from the Hoyt-Schermerhorn station. 

I follow my passion in the ways I can. Sometimes that means an A train after work, 45 minutes downtown and east to somewhere unbeknown (to me) in Brooklyn. The literary networking event wasn’t starting until 8, it was still before six, and I had at least an hour and a half before I was meant to meet a new acquaintance (acquainted because we both chronically go to the same cafe (can be found at the bar, on our high chairs, tap tap tapping away at McNally Jackson)).

“Are you a writer?” I had asked a number of weeks ago.

“Yes…” 

A literary connection! I gave the MFA student my email, and he insisted that he’d send some of what he’s written. I never promised to do the same (too personal). I’ve never liked sharing what I’m writing. I have an ego when it comes to my ideas. They’re pure genius, and other writers are vultures (I’m being facetious but there is some truth to this feeling). Plus, they are works in progress and some of my writing is bad writing. Any way, this was weeks before a very special person with a PhD helped me code a website for my writing.  He asked what icon and color scheme I wanted. I liked the lone rose with a tall stem and sparse leaves, and I like the color pink (because, it's girly). Any way, weeks later, the MFA student had invited me to a literary event. 

“My friend can’t go, and I have an extra ticket,” he had said (dialogue is not verbatim). “It’ll be good for networking.”

His professors and peers would be there. That sounded good to me, as someone on the outside. 

“There’s this biweekly writer’s group I go to (I’ve been once), and one is on Wednesday, but send me the info and I’ll let you know.”

“Okay, but let me know, or I’ll ask someone else.”

In everything there is opportunity cost. I’ve never been a networker (it’s icky and weird to me to pursue a connection with some ulterior, self-aggrandizing motive or to some aim, and asking for a job doesn’t scream merit-based to me. Leeching off of other people isn’t any way to make it in this world, at least for me. Then again, maybe I just don’t know how to ask for what I want). I want community, and friends with similar interests. I’ve never taken a creative writing class. I know no professors who may be able to write me a recommendation (I do know a film professor who is a little stuck up and has recommended that I not apply to fellowships before (I applied any way, and didn’t get in)), and for every application it seems you need at least two or three. So, the opinion of others does matter and maybe networking is just meeting people. I do like meeting people, and I think I’m good at it (I learned that from someone). The more the merrier. 

Any way, I don’t like committments (I can only name one). He didn't send me much info about it, but I ultimately decided to give up going to the writer’s group and instead go to the mysterious literary event. Who knows, maybe a book deal would come of it.

As my grandmother used to say, "Life is not a problem to be solved, but a mystery to be lived." (Popular quote, not sure who to credit)

So, there I was, walking south down Bond Street, unknowingly in the direction of Cafe Kitsumé. It looked like a nice place to sit and read for the next hour or so, so I approached the door. This is when I saw the hours posted. Closing time was six, so that left me 16 minutes of potential bliss. Not worth it. I pulled up Maps and searched cafes. I saw I was in a place called Boerum Hill, which I knew was where my friend Mia moved to. I hold her dear even though she hasn't invited me over to cook dinner (hehe), and I wondered what Mia was up to. I almost sent her a text, but I didn’t. *Cafes* was not the search, so I searched *coffee shops*. Perfect, one nearby that closes at seven. That would give me a good, dedicated hour to reading. I turned around and started walking northwest to it. Upon approach, an employee was out front collapsing chairs. It was 5:57 pm and the space was empty. 

“Are you still open?”

“Uh, no, we’re closing, we close at six, but we could make you a drink to go.”

(Basically) I don't care for coffee or expensive iced teas. I'm interested in third spaces for the sake of them, to sit and read or write in a place with good feng shui. I said, “Oh, that’s okay, thank you,” and loitered outside a Cuban restaurant to scheme a spot. I stood there thinking and then without direction turned around and started walking the way I came. One facade did catch my eye, and I peeled off to read the menu. Mediterranean (no, not whalers). There was a burger (a few) on the menu, and an old woman bent at a 90-degree angle brushed slowly beside me and pushed the door open. I continued to investigate the menu, while subtly aware of her standing just on the other side of the door. I opened it, and squeezed past her as the hostess greeted me.

"I'll be with you in one second." she said. 

This old womanan and I were side by side, and she came back a few minutes later to seat me....I chose a seat at the bar, and I read the Chowder chapter and asked for a burger (medium-rare).

"It comes with lettuce, tomato, and onion, would you like to add blue cheese or cheddar cheese or goat cheese or bacon?"

"Ooo, could I hold the tomato and hmmmm, I usually go blue, but goat cheese sounds good."

"Goat cheese is my go-to."

"Let's do goat cheese."

"You got it."

I asked for the check and walked to the top of the block to meet the MFA student. At Grand Army, I didn't order a drink. The man behind the bar had on a white t-shirt with a Krabby Patty and Spongebog, and square pants. Tattoos were on his arms, which were long enough to reach over the counter to the edge of the bar, where my tall glass of water was nearing empty. 

“Nice reach!” I said.

“Thanks,” he said and turned to fill another’s. 

“Square sponge Bob,” I remembered a wise woman say once, and I was thinking of —

I told the MFA student that it was 8:04 pm, and we left. Walking down Bond Street, I brought up my boyfriend as I have before. 

"Oh, I quit long distance back in college," he said.

"Wasn't for you?"

"No, not at all, total nightmare, wouldn't wish it on anyone."

"I think it depends on the person," she said. "Whether or not the relationship is important enough to you both."

"I guess." 

"This is my first long distance relationship," I said. "It's my first relationship, actually, and I hope my last." 

"Oh, so you were a party girl in college."

"No," I said, censoring a stronger rebuke (internally rolling my eyes at the suggestion). "Quite the opposite, and I never met anyone deserving."

"Okay, ego."

"I mean, I never met anyone who I wanted to be in a relationship with until I did. I was never interested in being in a relationship for the sake of it, and I have standards." 

Ultimately, I felt a little duped. It wasn’t a literary event for networking as it had been represented to me, not really. It was kind of like going to the club, loud, dark, with people holding cocktails in their hands, which I couldn’t care less about. I started talking to someone who worked in marketing for a B2B software company. 

“Stripe?” I asked.

“No,” he said. “Have you heard of Rippling?”

“Yes! I see their ads everywhere. So, that’s you.”

“That’s me, I guess.”

This man was the plus one of the man next to him who had just slipped away to the bar. He introduced his boyfriend as a self-proclaimed poet.

“So cool,” I said.

The poet came back with a sparkling Yerba mate, and the MFA student made his way over. We cheersed (I with my pantomiming hand around an imaginary beverage) and all talked for a bit and then released one another to the rest of the room. The MFA student told me he saw none of his professors and none of his fellow MFAs. That made complete sense to me, and the reality of the evening was sinking in.

“So, what do you do?" 

"I like to write," I said. "I actually just created a website. My boyfriend helped me make it."

"Oh, cool!"

"I've been thinking of it as my very own MFA (self-funded)."

"Okay."

"It's a form of structure, and I guess external accountability. It helps me write every day, or at least most days. Just to not think about what I'm writing, not care whether it's so edited," I said. "So, I just write and push it up to the ether. Every post is in support of an idea I have for a character. I'm basically developing a universe of characters who are all connected in some way, and eventually they'll all converge in one way or another. It's really fun for me."

I wasn't confident that the self-proclaimed poet could hear a thing I said. I also hate talking about it. It's such a bore (don't talk about it, just do it, get it done already, hit 'em with the link, or let it speak for itself).

"So, have you found your community?" 

“Me?” 

“Yeah,” the self-proclaimed poet said to me. I had also started to space out. Other things were on my mind, per usual. 

"I don't know," I said. "Maybe, I mean, writing has always been a very solitary activity for me. It still is."  

The event was at Public Records, where I’d been once before, on April 1, 2023 (Fools’ day), which has left an indelible mark on me and also not even close to one at the same time. 

I was ready to leave, so I cut loose after a conversation with a writer based in Red Hook that I could only half-hear came to a natural end. The MFA student saw someone he knew, and he b-lined it for her. This was a blessing (no offense) and my opportunity to save my ears and get the heck out of there. So, I did just that, having been there for at most a half hour. I made my mad dash out of the place. As I was reaching the point of starting to think less about leaving and more about walking to the station, I looked up to see that none other than Mia (!!!) was walking towards me. 

"Ah!" we both exclaimed, surprised and happy to see each other.

She was on her way to the event herself just as I was on my out?? What a miracle, and another gift from the universe. A guy who I would learn was from London and named Rohan with an H instead of a W walked up to her and she greeted him. She introduced us, and we three spoke for a while as a man knelt on the pavement beside us in a sea of cans, sorting.

"Oh, a high school friend..." Rohan said (a bit impressed?).

(We go way back)

"How was it?" Mia asked.

"Super loud," I said. "So wear your earplugs." 

My favorite moment from today was running into Mia out in the wild. Also reading the chowder chapter at a restaurant bar. I couldn’t cop a cafe, but I could a Bijan burger. It wasn’t the best burger but it was good with the goat cheese. For the record, the fries were thin and shriveled, dry and slightly hollow on the inside (reminded me of In N Out). 3/10, would not recommend. Sometimes you go to something, because someone invites you and you think it's the right thing to do. It's hit or miss, likely there's a miracle to be had. At one point, I looked down at my wrist. My whale charm had come undone from my pink and green friendship bracelet. Only an avocado remained, and Mia texted me shortly thereafter.

"Bro it was terrible...so loud and crowded...came and left."


Love, 

Elizabeth Kolling
