project:
  type: website
  output-dir: docs
  resources: CNAME

website:
  title: "Elizabeth Kolling"
  navbar:
    right:
      - about.qmd
      - fiction.qmd
      - nonfiction.qmd
      - text: "LinkedIn"
        
        icon: linkedin  # optional icon
        target: _blank  # optional to open in new tab
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header: header.html
    include-after-body: _footer.html



