---
title: "Derin Dribben"
author: "Elizabeth Kolling"
date: "2025-08-22T21:50:00"
categories: 
description: " "
---


Derin Dribben was an author who liked to write in women, for the challenge. Yes, he was twice divorced and the waters were choppy with his third, but he still felt like he understood them. This didn't mean he cared how they felt. He was obsessed with himself, after all, always writing himself in. He had a character that was basically his name backwards.

"I think I’m interested in why relationships fail. So often, and then only once, maybe never in one's lifetime, is there this rareness. I think that's what arrests Red Bird." 

"It is her catalyst, in a lot of ways. Have you experienced it?"

"I know I haven't." 

His third wife was sitting in the second row from the front and didn't appreciate what the one true love of her life had just said in front of all these people. She could take the more private moments of disregard, but she hated above all else being embarrassed. She gave him silence on the subway followed by a stern talking to when they got home. 

"How could you say that. With all those people there."

"I'm sorry, but it's how I feel."