---
title: "Ethan XI"
author: "Elizabeth Kolling"
date: "2025-07-012T12:15:00"
categories: 
description: " "
---


“I don’t even know what chapter we’re on, but I’m just going to dive right in. My first thought was why did Queequeg leave the chapel before the Benediction.” 

“I also found that odd or at least interesting,” said Ethan. “Also, oof, what’s a Benediction?”

“It’s basically the point in the service when the people sitting in their seats are blessed.” 

“By the priest?”

“Or the pastor, or the minister.”

“I fear I don’t know what is different about these titles.” 

“Have no fear, but we can come back to that.”

“Sorry, I know I always put you off your course. So, what were you saying about missing the Benediction?” 

“Yeah, I mean, Queequeg leaving the chapel early, before the Benediction, it almost says something about his character. He isn’t attending the service in his own self-interest. He doesn’t feel the need to be blessed, which I think is why a lot of people attend church or chapels or whatever. They want something, they want to be blessed or at least feel blessed, like everything is going to be okay for them.” 

“And Queequeg you’re saying already feels blessed?”

“Yeah, or at least he doesn’t take what’s free before him. He doesn’t need to take the blessing potentially given to him. While others really rely on this blessing to be okay, maybe he wants to take the harder route to blessedness. Really work for it, you know.”

“Maybe his spirit is already blessed, I mean he’s carrying around a little idol that I’m sure is blessing him. Here, it says he’s ‘peering hard into its face,’ so maybe it’s a work in progress.” 

“He wants answers.” 

“And he’s not afraid to change his idols.” 

“What do you mean?”

“He’s with his ‘jack-knife…whittling away at its nose.”

“Gently, so he cares.”

“Oh, did you hear Mabel got a nose job?”

“I didn’t hear that.”

“Yeah, apparently she did in the summer so she can recover before the school year.”

“Oh.”

“Yeah apparently it fucks up your whole face, like you get all puffed up with huge black and blue bruises under your eyes and you look like the kiss of death or like you’ve just been in a car accident.”

“That sounds painful.” 

“Yeah, you’ve got to be a little mentally ill, right? It gives me the shivers just thinking about it.”

“Yeah, I can’t imagine.”

“I would never date a girl who got a nose job.”

“Really, why?”

“It’s just so unattractive.”

“Isn’t the purpose to make a person more attractive?”

“Yeah, but like feeling the need to change your face and carving into it like that.”

“Hmm.”

“I mean, if you’re someone who wants to get work done, it sounds like you have a lot of work to do.”

“What do you mean?”

“Like you’ve got a lot of inner work and healing to do to get to a place where that’s not an option. I don’t know, you gotta get right from the inside out, in my opinion.”

“I think everyone should feel good, so whatever that means for them.” 

“I bet Mabel is still obsessed with her nose, even after the new one.” 

“Maybe,” said Levi. “Would you break up with Samantha if she got her nose done.”

“Hah,” Ethan said. “You’re good.”

“You don’t have to answer.”

“No, it’s a good question. Yeah, I probably would.”

“Damn.”

“I mean the nose is very important. A new nose can change your whole appearance.”

“Do you think—”

“But Samantha would never. She likes the way she looks.” 

“Yeah, do you think Mabel is unrecognizable?” 

“We’ll just have to wait and see.” 

“I’ll bet you like 20 bucks.” 

“I don’t know.”

“Fine, let’s say ten.”

“Betting money on that feels bad.”

“Fine, how ‘bout I bet you a blunt.” 

“Wait, that just reminded me—”

“Yeah?”

“I liked the part where Ishmael claims he is a good, a good Christian.”

“Oh, yeah.”

“It felt like a tone shift.”

“What does it mean to be a good Christian?”

“Uh—”

“Maybe loving the body God gave you, to start.”

“Right,” said Levi, turning to the page. He was trying to decipher his own annotations in the margins and in-line (above and below the black print) with the text.  

“Okay, I’ll be serious.”

“Here, he effectively defines what it means to be good.”

“Where?”

“Here, he says, ‘…the will of God?—to do to my fellow man what I would have my fellow man to do to me—*that* is the will of God.”

“Interesting.”

“So, he’s equating goodness with the will of God as well.”

“And the will of God is worship?”

“I guess so.”

“I like how he expresses the importance of respecting other forms of religion.”

“Mmm, yeah!”

“He basically confronts God.”

“Mmm.”

“Here, he denies that God is a jealous person—God, I mean. He says, ‘Do you suppose now, Ishmael, that the magnanimous God of heaven and earth…can possibly be jealous…’”

“I think the ending of that sentence is also important to consider. He goes on referring to Queequeg’s beloved idol as an ‘insignificant bit of black wood.’ Frankly, he’s insulting other belief systems. Or saying, yeah, I’ll respect your religion or its existence, as long as mine is the superior.”

“So, he’s still establishing a hierarchy.”

“I think so. Also, separately, framing this as a question addressed to Ishmael is kind of inception-like. It’s like, okay, is this God speaking to Ishmael through Ishmael, or is Ishmael’s interior just fully out there. The difference between first and second person, I guess, is my point. And Melville chose to invoke second person here.”

“Back to the hierarchy,” said Ethan who hadn’t really been listening to what Levi just said (thoughts had a way of slipping through the ___ and he wanted to remember what he had thought of to say). “He does though recognize the need for mutual respect.”

“Mutuality, definitely, right, the idea that belief systems are not mutually exclusive, here he says that unity is achieved by participating in each respective form of worship is what it means to doing the same unto others.”

“I low-key read it as conversion, but mutual conversion, so like is anyone just one thing—Christian, Muslim, Buddhist, Daoist, Jainist, Jewish, Hindu, or are we all of them, together One. Not to be cheesy.”

“In a world that is overwhelmingly lactose intolerant.”

“Lol,” Ethan said (actually said it aloud).

“Also, Ishmael is pretty subversive, and he’s evolving as a character.”

“What do you mean?”

“He walked the talked and followed through,” said Ethan. “He did the worship ritual with him.”

“Now, for the knocking of hats off.” 

“What do you worship?”

“My nose. Oh, and my calf muscles,” Ethan said as he lifted his leg and flexed. “See?”

“Oh, I see.”

“What about you?”

“I’ve never thought about it.”

“Come on.”

“I guess whatever book I’m reading currently.”

“Hell yeah.”

“Melville’s resting happy.”

“When did he die, by the way?”

“I don’t know.”

“Let’s look it up.” 

“Got it,” said Levi. “1891?” 

“Okay, so 1819…he was what, seventy—”

“One, 72.” 

“What about you?”

“What about me what?”

“I’m just thinking about what we were talking about,” said Ethan. “Would you date a girl who had a nose job or wanted to get one?”

“I would.”

“You would?”

“Yeah, I mean, it’s her body, her choice,” said Levi. “Either way, it’s about the soul, as Melville says.”

“Where does he say that?”

“Well, he brings up the soul.” 

“When, where?”

“Uh, third paragraph. Here, ‘you cannot hide the soul.’”

“Some souls I prefer to others.”

“What if it’s all one soul,” said Levi. “One body, one soul.”

“Do you believe in soul mates?”

“I think I do.”

“I don’t,” said Ethan. “Would you ever date someone with tattoos?”

“I think I would.” 

“What if they were unearthly?”

“What does that mean?”

“Samantha wants to get one on her back.”

“Of what?”

“She wants an avocado with the pit still in it.”

“Okay.”

“It’s a nightmare. I’m trying to convince her.”

“Why on her back?”

“I don’t know,” said Ethan. “Maybe so she doesn’t have to see it.”

“That’s harsh.”

“Well, I’ll be the one who has to look at it.”

“I don’t know dude,” said Levi. “You should support her.”

“When are you gonna get a girlfriend or at least a bosom friend?”

“Patience, my friend.”