---
title: "Maximilian XVIII"
author: "Elizabeth Kolling"
date: "2025-09-21T11:49:00"
categories: 
description: " "
---


The cup of tea on the table across from him made him think of them; they weren’t together, but they were once together. They once looked at a cup of tea, nothing like this one, together, and his heart still ached at the memory of standing there, at just the slightest distance behind her bare shoulder. She was wearing a summer dress, white, even though Labor Day had passed and fall was the season. It was Room 824, if he remembered correctly, and she knew what she was doing. 

"Technically, I’m breaking the rules of fashion and the ancient customs of East Coast high society," she had said to him.

“What do you mean,” he had said to her.

She had told him that whites were only allowed if they were winter whites, cashmere sweaters or corduroy. Anything merino wool would do. 

"I think I want to live on the West Coast, because people out there don’t care about summer whites when it's autumn, and things like that.

He wondered why she was so adamant about rejecting where she came from, and blasé. Her life seemed pretty perfect, from the outside, but maybe that was the problem. Perfection breeds apathy.  

“I hear California has no seasons.”

“You don't know what I wouldn't do to abandon the seasons.”

“Really, why?” 

He looked at his phone, which seemed to serve no purpose besides the constant reminder that she never did answer the question he asked of her. There was one more day of summer left, and he saw her there, eyes tracing the canvas, like his pencil on the sketchpad in front of him. He followed the outline of his flat hand, with the palm outstretched and pressed had against the thin sheet of stark white, each finger, up and down, to practice form. He was no prodigy, and he remembered being hard on those who had come before him. He had to admit, he hadn’t perfected the hands either, even all these years of practice later. It looked like the turkey that a third grader would draw before Thanksgiving break.

“I always see the flowers first,” said Max. “I don’t know why.”

“One of the flowers is wilted.” 

“Wilted or wilting?”

“What’s the difference?”

“It’s the same as saying old or aged versus aging. You’ve either reached self-actualization or you’re still aspiring."

“I think the flower has reached old age, but it still has further to go.” 

“Aging versus dying, maybe.” 

“I wonder if Mary originally painted this woman with her hand holding her stomach,”said Sara. “It looks almost like it’s painted over to instead reflect the ripples in the fabric. Maybe she thought that was too sexually suggestive or intimate a scene for an older woman.” 

“I think it’s funny how you refer to every male painter in here by his last name, and Cassatt you call Mary.”

“Huh, that is interesting. Maybe I’ve internalized the patriarchy and am to critical when it comes to the second sex.”

“Look at her ear,” said Max. “Do you like it?”

“It’s like a black hole.”

“A brown hole of beeswax.”

“Not a fan.” 

“She has a look of love on her face.”

“Not romantic.”

“It’s more maternal.” 

“Like the love of a child.” 

“The teacup is tilted toward her.” 

“Do you think she’s about to drink, or she’s just drunk some?” 

“I think she’s going in for another sip.” 

“Do you drink?”

“Alcohol?”

“Yeah, alcohol.” 

“What do you take me for?”

“An ordinary high schooler.” 

“Extraordinary, to you.”

Sara takes a step towards the painting to the left. 

“I like this woman with her hand on her hip.” 

“The nanny?”

“The servant, it says.”

“Unofficially La Servante.”

“She must’ve just made dinner.” 

“She’s just served it, and now she’s looking at the kids with a look that says you better like what I made for dinner because it’s what’s for dinner.”

“Totally.” 

“What my eye goes to is the ring on her left hand.” 

“The ring finger.” 

“She must be married.” 

“And you know what comes of marriage?” 

“No, What?” 

“Kids. Whether happy or unhappy, a marriage always seems to bring about children.”

“So that makes me wonder who is cooking her children dinner?” 

“The shape of her eyebrows and eyes make her look sad.” 

“They do point down.”

“It’s like she’s faking a smile.”

“She does look sad, doesn’t she.”

Sara takes another step left. 

“Still life with peaches.”

“Peaches and a few pears.”

“And maybe one apple?”

“The foremost pear is an apple, you’re right.” 

“And what’s all the green foliage in the pot?”

“It does not look like peach leaves.”

“It looks like kale.”

“This is what I hate about Renoir’s still lives.”

“What?”

“They are always so curated.”

“Like look at this painting over here, it’s the same bowl of peaches, but now it’s grapes on the table instead of pears.”

“And an apple, don’t forget.” 

“Now here he brings some life to the peaches, more naturalism, because look at the peach at the top of the pile here.”

“It still has its stem and leaf, which suggests a life before that of the interior.”

“Life on the branch, in the orchard.”

“Doesn’t the leaf imply that the peach was picked prematurely?”

“Huh?”

“Like when you wrap your palm around a peach it should give itself freely from the branch. But if it’s unripe there will be resistance and you’ll end up with this here, a leaf attached.”

“I don’t know. I’m too busy looking at this solo green grape.”

“The last grape in the bag is always the mushiest.”

“That’s my experience too.” 

“What kind of pottery is that?”

“Pottery? You mean, the china?”

“Porcelain, right.”

“So why do you think Renoir did essentially the same still life with this bowl of peaches?” 

“I think he was playing with the background.” 

“I prefer the minimalism of this greenish blue one.”

“Definitely, the other is too busy.” 

“It takes away from the peaches. It kills their animation.”

“These orange flowers in the first painting with the pears reminds me of the Ibis in the other room.”

“Oh, the Degas?”

“Yeah.”

“Interesting.” 

Sara steps towards the other woman in the room with a ring on her finger.

“I like what he did here with the mustard yellow, how he carried it through, throughout the fabric.” 

“And the rose in her ear complements the needlepoint."

"The needlpoint?

"Do you see the rose in the bottom right hand corner?”

“Oh, yeah.”

“Do you think this is a married woman, or an engaged woman?” 

“I don’t know.”

“I wouldn’t know the difference.”

"Really?"

“I think she’s only engaged, because look how eager her left hand is. Those two fingers, I mean.” 

“It’s like she’s inching towards her husband.” 

Sara then took a step away from Max, who never let himself believe she would be the woman he’d marry. Disbelief was far easier to recover from than believing in something that couldn't be. He saw some of her in the old woman with the tea cup and saucer across from him in the cafe, and he wondered how she might spend a Sunday in San Francisco. The hardest part was he felt he knew exactly where to look for her. Maybe he'd buy a ticket and go there to surprise her. She had never actually said she hated surprises, she just didn't receive them well was all. 
