---
title: "Summer VIII"
author: "Elizabeth Kolling"
date: "2025-09-23T23:26:00"
categories: 
description: " "
---



Summer took the 6 train from Spring Street and transferred to the four-five at Brooklyn Bridge-City Hall.

Adrian first took the E from Queens Plaza, at a certain point the 4 to the seven towards Queensboro for the trip back.

Igor rode a bike across the Manhattan Bridge, since he lived in Dumbo. 

Alexis took the red line, local, from Christopher Street, after walking Barrow. 

Samantha took the L from Williamsburg on the days she worked from. Otherwise it was an A after a walk from the Hudson Yards office. 

Matthew who went by Matthew took the F train from Rockefeller, even though the 4 from Grand Central would’ve been faster. 

Jamal took the express line from 125Th and Malcom X, and transferred to the 1 at Chambers Street.

Kirk came straight from Flatiron on the R/W.

Nia passed Holy Cross Cemetery on the way to Church Ave for the Manhattan-bound 2 train.

Jonah walked all the way from Greenwich Village. 

Freddie was staying seven streets and one avenue southwest of the lobby, where a skinny young man with the word security stitched over his heart was nodding off as Summer entered. She walked up to him behind the desk.

“Excuse me,” she said. “I'm looking for the—”

“Third floor,” he said. 

"For the School of Drama?"

"Third floor." 

[insert more]

They came from the north and the south and the east and the west, as a matter of chance, for acting class. Each, for a different reason.