---
title: "Madison"
author: "Elizabeth Kolling"
date: "2025-07-06"
categories: 
description: " "
---



“Why was Sally always such a hard ass towards me?”

Maddie brought her hand up to her mouth and turned her face to the writers' wall to hide her laugh. They were standing at the water bubbler (which Max like to call the watering hole in this hole in the wall of a cafe), and Maddie had just finished putting her card back into her wallet when she looked up (saw him seeing her). 

“Well hello to you too, Maximilian.”

“Hey, sorry, I’ve been keeping that in for some years, but I’ve genuinely always wondered.”

“Did you not know?”

“No, know what?” 

“Sally had like the hugest crush on you.”

“What?”

“Big time.”

“I had no clue,” he said, holding back. “I had the biggest crush on you.” 

“You did?”

“Yeah. I thought it was so obvious, I mean—”

“It wasn’t obvious to me.”

“I wish I’d told you then.”

“Why, so we could've held hands on the way to fifth period?”

“No.”

“We were just kids.”

“It was high school.” 

“Big kids. Plus, I wouldn’t have done that to Sally. I wanted to be a good friend. I think that’s just what any of us wants.”

“I heard about her and Oliver.” 

“Yeah.”

“I’m sorry, that’s pretty shitty…of the both of them…but especially her…I’m guessing you’re not that great of friends anymore?”

“Pretty much.”

Max looked at her. She wasn't just pretty. 

“Every day for six years I wanted to tell you how beautiful you are.”

“Max, thanks.”

“It’s true.”

“My—”

“I think people should go after what they want, full force.” 

“It’s not always that simple.”

“Of course it is. Life’s short.”   

“My boyfriend’s actually meeting me here,” she said, turning towards the street to pluck him from the crowd of passers-by and people in line. “I think you’d love him.” 

"I'm actually meeting someone here too."

"Oh." 

"Yeah, I mean maybe we could—"

"Totally, I mean we wouldn't want to interrupt but we'll totally come say hi, maybe sit for a second."

"For sure," he said, looking around. There was maybe one free table.

"If there's somewhere to seat, at least."

"Sounds good, so what have you been up to?"

"Besides spending my life savings on coffee shops?"

"Naturally."

Maddie liked to perform a degree of poverty. She wasn't as rich as Sally, whose forefathers' surname could be seen engraved along the steps leading up to the Impressionists (swing a left at the top and go straight), but Maddie was well off. Her parents had a second home in Cape Cod (which she always referred to as the Cape, and reminded people that the correct preposition was *on*, not *in*), and she lived in a brownstone on 83rd between 3rd and Lexington, but her parents' pipe dream was this one stretch between Park and Madison Avenue. Hence, her name. 

"Oh, I see him."

"Awesome, actually I have to pee," he said, immediately regretting it. "I'll stop by your table."

Max had no plan to stop by the table, but he said it. If he had it his way, he would've holed up in that godforsaken restroom until closing. There was always piss on the ground, but the grafitti and poetry on the walls could keep him busy for a few hours. Of course, he wouldn't do that. He wasn't crazy. As he loitered at the toilet seat, he couldn't help but think what Maddie meant by it (how she wouldn't have done *that* to Sally. What was that? Had she liked him too? Did she still? Was there still hope). See, Max didn't actually need to pee. In fact, he hadn't even been thirsty. He had seen Maddie standing in line, and he'd seen her walk in, up to the counter, and point to the cherry and cheese danish, and he had timed it perfectly even though the timing was off. She was always in a relationship with some guy from a happy family. 

