---
title: "Summer XIV"
author: "Elizabeth Kolling"
date: "2025-10-15T19:24:00"
categories: [Summer]
description: " "
---

[insert more]

She tried to focus on the scar tissue. Adrian also had it, though in a different location, for different reasons. She stared at his scars, up and down his forearms across from her, and thought maybe he'd been through some things that had made him grip and push down on her waist like that as she pulled back. There was something dark and twisted, or innocently kinky, inside of him. 

[insert more]

She had developed a subconscious habit of staring at the wrists of the people around her, and the long sleeves that he wore as an extra layer under his graphic tee were scrunched towards his elbows. This one was even more surreal than last week's, more tasteful. Instead of an anthropomorphic carrot dancing in the nude under dreamcatchers, there was a snake growing a tree out of its rattle and birds and bees were chained to the trunk while Christian crosses fell like leaves. 

Summer would look anywhere in the circle if it meant she wasn't looking at Freddie. She'd even risk Adrian's eye contact, flattered brow, and shrugging shoulders, until she couldn't take his ego any longer. 

[insert more]

"So," said the voice and speech instructor. "We're going to incorporate some movement this week."

The voice and speech instructor reached behind her back and passed a stack of white pages to Adrian who turned to Jamal who turned to Alexis who turned to Jonah who turned to Summer who turned to Igor who turned to Kirk who turned to Nia who turned to Matthew who turned to Freddie who turned to Samantha who saw that it was a printout of *A Midsummer Night's Dream*. 

[insert more]

She had never read it, and Summer didn't need to watch to know how he walked around the room. She already knew how Freddie walked on his tip toes. It was restraint mixed with a desire for ascent. He was a rocket launch at gravity's behest. 

[insert more]