---
title: "Don III"
author: "Elizabeth Kolling"
date: "2025-07-03"
categories: 
description: " "
---

“How was the game?”

“Good,” said Levi. “Well it wasn’t a game per se.”

“Oh?”

Levi’s flaw was that he couldn’t tell lies (easily). He always had to say the thing with precision, but he was working on it.

“I mean, it was technically a scrimmage, pre-season, for practice.”

“Oh, that’s nice of the other team.”

“I mean, we were kind of doing them a favor.”

“Oh.”

“They’re like thirteenth string.”

“Oh.”

“Seed, thirteenth string, I mean,” said Levi. “But technically, I am too. String, I mean.”

“Oh?”

“I hardly played.”

“Oh.”

“But that’s okay.”

“It’s your freshman year.”

“Yeah, but these guys grew up playing on traveling teams, you know, club.”

“Oh?”

“Yeah, so they have all this fancy footwork and high esteem.”

“It’s good to have high self-esteem.”

“Some of them are pretty pretentious, and they make fun of the freshmen.”

“Well, don’t judge them on first impression, it’s still early, get to know them.”

“I made a friend.”

“Oh yeah?”

“Yeah, another freshman. The upper classmen have nicknames for him. I don't know if it's endearing or bullying. He doesn't seem to mind it.” 

“What’s his name?”

“Ethan.”

“Ethan, nice.”

“He was sitting in the same row as me on the bus. He was reading *The Catcher in The Rye*.”

“Ah, I loved that book when I was your age.”
“I read it in middle school.”

“I don’t think I read it until 10th grade,” said Don. “Are they assigning it now in ninth grade? And what?!Where was I when you read it? It’s not exactly age appropriate for high schoolers, from what I can remember.”

“I found it in one of mom’s boxes.” 

Without a word, Don turned to the cupboard and took out a mug. The hot water wasn’t even on, and he hadn’t had dinner yet. 

“Tea?”

“I’m okay.”

“You hungry?”

“I’ll probably just make something.” 

“You sure?”

“Yeah,” he said. “We still have some Annie’s, right?”

“Yeah, I just stocked up,” said Don. “So tell me about this new friend. Ethan, where’s he from?”

“I don’t know much about him, really. He’s really good at soccer.”

“Well, I’m very excited to hear more about him.”

“I don’t know, we may start a book club or something.” 

“Very cool.”

“What’ll be your first book?”

“I don’t know, Dad, again, I just met him.” 

“Sorry, sorry.”

“I’m gonna go shower.”

“Okay,” said Don as Levi turned towards the hallway. “You know you can talk to me, right?”

Levi turned around, even though it was only half-true. He knew he couldn’t, not actually, but he didn’t want his dad to feel bad. He seemed to be doing better, lately. 

“I know.” 

"Hey, Levi?" 

"Yeah?"

"Let's do dinner tomorrow."

"Sounds good, Dad." 

"It's important to eat together."

"Pizza?" 

"Perfect."
