---
title: "Summer XI"
author: "Elizabeth Kolling"
date: "2025-10-02T23:26:00"
categories: [Summer]
description: " "
---

[insert more]

They walked each other to the corner and turned around at the same time towards Samantha and Jonah and Alexis who were trailing far behind but surely making their way west along Maiden Lane.

“Hey,” said Summer, stopping to face him as he followed through with the return to Broadway. 

“Mmm,” Freddie said, looking back over his shoulder, with inflection. 

“Have you read any Jeffrey Eugenides?”

“I have not.”

“I think you may like him, or might (might like him).”

“Then what am I reading?” 

“Middlesex," she said. "I think is good. But also The Marriage Plot.”

“I’ve been meaning to read the first,” he said. “I haven’t heard of the second.”

“I think they’re both good.”

“Do you have them? Copies, I mean, that you could bring to class Tuesday?”

“I don’t think I actually have either anymore.”

“Anymore?”

“Every time I move in the city, I shed some of my library.”

“Oh, no,” he said. “That’s too bad.”

“Yeah, it’s a bit touchy.”

“Sorry, I didn’t mean to—”

“Oh, no, I was joking.” 

“Oh,” he said. 

A beat of silence.

“Or—”

“Sounds like my worst nightmare,” he said. “Shedding the library?”

“Like it’s dead skin. A bit of me dies each time.”

“I don’t think I’d be able to part with my annotations.” 

“You’re a big tater? Annotator?”

“A true tot. No, not in an academic sense, but I do write what I’m thinking, or feeling, at that crucial moment of reading any one sentence in the margins. It makes reading slow, but I don’t know, the books on my shelf have kind of become my—”

“Diaries?”

“Well, I’d prefer the word journal, you know, in defense of my manhood and all.”

“I think real men keep diaries. The others have issues.”

“I’ll have to work on that, those issues of mine, I mean.” 

“Sorry, I didn’t mean to—”

“Don’t worry, I was joking.” 

[insert more]