---
title: "Maximilian VI"
author: "Elizabeth Kolling"
date: "2025-07-01"
categories: 
description: " "
---



Everywhere he looks are people suffering, hot, cold shivers, without health care. A man sleeps on a vent (warm in winter, cool in summer) outside the school he goes to on scholarship (merit-based), and against the facade of a multi-billion dollar high-rise that they named Steinway, and Max was a serial quitter. He quit piano when he was nine years old. It wasn’t for him. It was his mother who couldn’t afford it anymore, and his dad didn’t find out until years later, when he found himself in a room of people egging his son on, asking the two of them to play Joy to the World together. He was getting skinnier then, though no one seemed to notice all but the leftover peas on his plate. They’d been boiled a few days prior and left for spoil on the stovetop, then saved, and the thought of food made him lose his appetite.

He was sitting by the window seat, staring at a raisin roll, which was basically a cinnamon roll without the cream cheese frosting, with raisins and all, wondering whether or not he should eat it or save it for later when he really was starved.  

“You know” he said to her. “I’m not hungry.”

“Oh, really?”

“I shouldn’t have gotten this,” he said. “I was just going to get coffee, and then I don’t know.”	

“I don’t know how you drink it straight black.”

“Huh?”

“The coffee,” she said, with a nod of her head towards the scratched-up white mug. 

“Try it.”

She took a sip of it, while maintaining eye contact, swallowed and stuck out her tongue. 

“The coffee’s pretty shit.”

“Isn’t that why people come here?” He said. “It adds to the aesthetic.”

“The aesthetic?”

“Yes.”

“And what would you call it?”

“Dim, intellectual…communal bathroom, soupy, definitely sweaty.” 

“Aesthetic you say,” she said. “So that’s your final answer?”