---
title: "Ethan XVII"
author: "Elizabeth Kolling"
date: "2025-08-01T19:56:00"
categories: [Ethan]
description: " "
---


He said the prompt in his head and thought of how he’d answer who in your eyes is a sage.

“Do you think Queequeg is a sage?”

“Hmm?”

“Queequeg,” said Ethan. “Do you think he qualifies as a sage.”

“I don’t know,” said Levi. “What’s your definition of a sage?”

“Uh, I don’t have a definition. I mean, I don’t have a personal definition that differs from the normal definition.”

“So what’s the normal definition?”

“Come on, dude.”

“What?”

“It’s like you think I’m stupid.”

“What, no.”

“It’s like you don’t think I know what sage is and you’re trying to trap me or corner me into saying something stupid to prove that you’re smarter than me.”

“What, dude, no.”

“Whatever.”

“Do you want to just call it off?”

“No, I want to talk about the goddamn Ship.” 

“Okay. Fine. Then talk to me about it.”

“I think you don't know what sage is and you’re projecting your ignorance onto me.”

“Hit me.”

“Sage, a noun, a spice you cook with. An herb, rather.”

“Ah.”

“Sage, a noun, a wise man.”

“Or woman.”

“Sage, an adjective, possessing wisdom.”

“That’s all?”

“That’s all.”

“Mmm.”

“Mmm? Don’t mmm me. What? Why the wise assness.”

“You forgot one.”

“No I didn’t. Sage, sage, and sage. I got all three.”

“Whatever you say.”

“Fine, tell me.”

“Sage, as in sagebrush.” 

“Ugh.”

"I really want to see it, or smell it. Apparently it has a super nice scent. We should do a road trip to see it."

"To where?"

"Uh, I think further south, where it's drier, like south of LA, maybe."

"You want to do a road trip for 8 hours so we can smell a flower?"

"It's technically a flowering plant."

"You're crazy."

"So you're in?"

"Obviously."

"Sweet."