---
title: "Frieda"
author: "Elizabeth Kolling"
date: "2025-07-04"
categories: 
description: " "
---


Max had a habit, among other ailments, and made patronizing the Metropolitan Museum of Art a priority. 

It was to this aim of understanding, with the purpose of becoming a renowned modern-day painter. He studied the Greats before him, save Seurat. He couldn't stad pointilism and didn't get the point. Each dot was a frog in his throat. The applicatiion, he imagined, like getting choked up or being unable to speak words to a pretty girl. But that was back in elementary school, and he'd grown hard of heart since then. Now he’d take his dates there, as a screener. 

"What's up with that?" she had asked.

“You can tell a lot about a person from what they can say about a bit of oil on canvas,” he had said to her. 

She was his best friend, Frieda, and didn't exactly like the way he treated women, but she saved face by feigning the fact that she couldn't really relate either way or didn't have the whole picture. So, she hardly questioned him. 

If that's the point of friendship, she wondered (moral allowances, rooted in a sense of alliance).