---
title: "Levi X"
author: "Elizabeth Kolling"
date: "2025-08-02T12:05:00"
categories: 
description: " "
---

"I hit the jackpot," said Levi.

He said this to Ethan who was keen on visiting Samantha at the ice cream shop every Saturday evening. After book club, Levi would walk the bike path too and then peel off to catch the book store before closing. He was looking for the Cherry Orchard, but they weren’t there yet. Levi was taking his merry time, stopping at particularly juicy sections of the bramble. 

“Come on,” Ethan said. “It closes in 14 minutes.” 

“One sec, I’ve hit a gold mine.” 

Ethan wasn’t the most adventurous fifteen year-old, and he hated being late to his own plans. He watched as Levi reached some more. 

“Sam says the new flavor this week is killer.”

“Okay, okay,” Levi said as he reversed himself from the little daggers and came over with a big purple mess of a smile. One of his hands was covering the other, which was cupped, as a safeguard. “Check these out.”

“Woah, what are those?”

“Loganberries.” 

“Loganberries? They’re, like, long.”

“They’re sweeter, less of a tang.” 

“Levi, I think you just don’t know how to pick ‘em. All the blackberries I’ve ever had have been big and sweet and delicious. Zero tang, until you started picking them. The ones you’re handing me are small and sour.” 

“Hey, I’m working with what I have. It’s not like these are the same berries. These aren’t the same berries as even a few years ago.”

“What do you mean, the bush is not pushing the same berries as before?”

“Yeah, for a bunch of reasons.” 

“Okay, enlighten me.” 

“For one, we’re in a drought. There’s not enough water to juice them up. You know how the ones in the grocery store are so huge all the time? It’s ‘cause they’re irrigated.”

“They just pump water into them?”

“Yeah. And now there’s all this eucalyptus here blocking the sun.” 

“The trees grew fast.”

“Yeah, cause they’re invasive. And they’re not even originally from here.”

“Okay, xenophobe.” 

“You know what I mean,” said Levi. “They’re not native.” 

“Neither are blackberries.” 

“Not the Himalayan, but there is a coast berry that grows up the coast.”

“Naturally.”

“You wouldn’t like them.”

“They’re small.” 

“Hey, size doesn’t matter.”

“Just try these loganberries already.” 

[Ethan takes a berry from Levi’s hand and tries it]

“Mmm, I like that.” 

“Right?”

“Mmm, get me more of those.” 

[Ethan grabs for a few more. Levi lets him have them.]

“There’s only one bush, and I pretty much cleaned it.” 

“Alright, we’ll come back in a few weeks.” 

“Oh, that reminds me,” said Levi. “When do you want to go?”

“Where?”

“To the sagebrush?”

“Don’t we have enough bushes around us already?”

“Come on, it’ll be fun (It’ll be an adventure).”

“Fine, okay.”

“You’re no fun.”

“Yeah I am.”

“Then act like it.”

“Okay, some time next week?”

“I mean, yeah, but, like, when?”

“Uh, well, I have this summer info session thing I have to go to on—”

“What day?”

“Uh, Tuesday or Wednesday,” said Ethan. “Tuesday, I think.”

“Okay, so then let’s leave early Thursday morning. I’m thinking 5 am.”

“Hold, on, Levi, I mean, are these bushes even growing right now.”

“It’s August.”

“So?”

“So, yeah, it’s like peak season. They bloom in late summer.” 