---
title: "Summer V"
author: "Elizabeth Kolling"
date: "2025-09-14T08:07:00"
categories: [Summer]
description: " "
---

Summer didn’t even want to acknowledge her, but she figured peace in the home was better for everyone.

“Morning.”

“Hey, how’d you sleep?”

“Not well.”

“No?”

“No, because someone came home at 4:30 in the morning and woke up the whole household.” 

“Clubs close at 4,” said Kim. “I was doing you a favor.”

“What does that even mean?”

“I’m making tea. Do you want any?”

“What kind?”

“The green kind.”

“Only if it’s oolong.”

“You know I don’t drink oolong.”

"You don't drink yuja-cha either, so what do you drink?"

"Sencha, sister."

For minutes, it’s silence between the two of them. Kim watches the water rise, simmer, boil. She makes two cups and places one next to Summer who has her head particularly pointed down at the page. She wants to disappear into this textbook, and she already feels she’s lost her soul to the upcoming exam (in January). She only notices the tea once Kim passes behind her chair and sits down on the couch.

“I’m good, thanks.”

“Okay, don’t poo your pants, it’s a peace offering, and it’s good, see?”

Kim imitates a sip to break the ice but burns her tongue in the process (Ow!).

“The tea’s hot.”

(You don’t say) Kim sets her tea down on the coffee table.

"You should really use a coaster."

"It's a glass table." 

"It's the principle."

“So what are you up to today?”

“Nothing, studying.”

“Summer, promise me you’ll go outside today.”

“Kim, you’re so dramatic. I just got back from being out.”

“What, you walked a block and a half for a cortado?”

“Mado bout it?”

“That’s not good enough. Seriously, We’re all worried about you. You’re so pale, it’s like the sun hasn’t ever touched you.”

“Come on, that’s a little dramatic, it’s raining right now.”

“Whatever, my point is you can’t just be holed up here in the apartment like you have been all summer long. It’s fall.”

“Technically it’s summer until the 22nd.” 

“Technicality my ass.”

“Oh, actually, can you be out of the apartment at 12 pm today?”

“What do you mean?”

“Can I have the apartment to myself at 12 pm.”

“Why? Is Philip coming over?”

“What, no. I have a meeting.”

“Okay, whatever, for how long.”

“An hour.”

“I’ll think about it.”

“Seriously, Kim, please.”

“Why do you need the whole apartment for a meeting.” 

“Because I don’t want you eavesdropping like you always do.”

“I don’t eavesdrop.”

“Yeah, you do.”

“Okay, that one time, because I was worried about you.”

“Stop worrying, you’re aging.” 

[insert more]

“I was planning on being out of the apartment then, for the record.”

“Thank you, I love you.”