---
title: "Ethan VI"
author: "Elizabeth Kolling"
date: "2025-07-02"
categories: 
description: " "
---


“Mom?”

“Hi, honey, how was Levi's.”

“I don’t want to go to college.”

Laura was looking down at the Architectural Digest in front of her no longer. She looked up at him, curly-haired like his father and already as handsome as a man, standing there across the kitchen island. 

“Sorry, I’m listening, honey, what did you say?”

“What I'm trying to say is, is I don’t want to go to college unless it’s this one college.”

She set her glasses down on the counter (marble, remember). 

“Everyone has their school of choice, honey, and then they have, what do they call them, their safeties. It’s normal to have options."

"No, you're not listening."

"Okay, I'm listening." 

“I’m just going to apply to one school.”

“I trust you, but how about we sleep on this? College is very important, and not everyone gets into their top choice.”

“I know, and I’ve thought it through.”

"What are you going to do if you don't get in."

"I'll get in."

"Ethan, you're worrying me."

"Thanks for being supportive." 

"Ethan," she said. "You know I support you. I'll always support you." 

