---
title: "Maximilian"
author: "Elizabeth Kolling"
date: "2025-06-12"
categories: 
description: " "
---

Let’s see, where to start.

See all the art. Haystacks at sunset. Light becoming bristle and brushstroke, becoming city and sea. There they were, and there they weren’t. Impression, Sunrise and the painter here alone, not lonely, dumb-founded and lost fishing, for some reason, looking, just looking at oil on canvas as though the square were a Rubik’s Cube, cubism, or something, his eyes wide, open to long game, looking a little bit longer, one-night stands and short-term relationships until then, standing too close for comfort, causing the security guard, already on edge, a great deal of discomfort in Gallery 819, which, 8 + 1 + 9, is a nine, her life path number, rolling shoulders, cracking knuckles, rocking heel to toe like the letter H, the humble sail, that one boat over green water, his nose now in it, sniffing, snorting, as high as the horizon line at 10 in the morning on a Sunday, after Saturday night had fallen aside like hail, hard, for him, and leaving, leaves of absence (easier), with these impressions of her own, this farsighted vision, tortoise to correct and frame amber lenses, a dream and no one buying, without the same talent or softening effect, that 19th Century attention span and perceived value system, those long lost cataracts, lying, stealing, cheating, looking, just sussing out the subway car, grasping at railing, rail thin, reeling, forever off the actress who had thought the last name of what’s his name, Édouard, who came before Him, sounded the exact same as where she had come from, the thing that didn’t grow on trees, money, which He had never much cared for, growing respectfully distant and disenchanted, on to the next, now more than ever set on and in pursuit of the reader who was so hard to get. Max didn’t get her, reading her text.

“Hey so sorry to cancel, but I can’t actually make it to the MET tomorrow.”