---
title: "Levi"
author: "Elizabeth Kolling"
date: "2025-06-10"
categories: 
description: " "
---

“Hey,” Levi said to him a second time. 

Ethan was reading *Catcher in The Rye* on the bus, and he was getting to the good part so it took him a second to understand that someone was talking to him and not their mother on the phone insisting on the play by play of the school day before the game. 

It was Levi, one of the other freshmen on the team, leaned back in the bench seat next to him, across the aisle, with his cleats off and feet dangling. His socks hadn’t been washed for a few games and he was a shorter fellow, second string. Coach had been substituting him in, late in the second halves. 

Levi wouldn’t play much, but he'd put his best foot forward when he was out there, kicking rocks, and he'd have a way of always seeing the silver lining in any sort of messed up situation.

“Hey,” Ethan said back, as he turned to face him. “Levi, right?”

“Holden’s kind of a dick.” 

“Really?”

“Don’t you think?”

“I don’t know,” he said, still wondering if he'd guessed his name correctly. It'd only been two weeks since the start of the season. “I mean, I think, for me, it’s too early to tell.” 

“Huh, how far are you?” 

“Huh?”

“In the book,” he said. “What’s happening right now in the book?”

“Oh, right,” he said. “I’m at the part where he’s in a cab.”

“Which cab?”

“There’s more than one?”

“The first or the second?

Ethan took his thumb out from between the pages and turned the book, now closed cover to cover, so Levi could see where the book mark was. Levi saw the width of the pages towards the back cover, thicker than he had previously thought. He nodded his head in the affirmative and then shook it left to right as he let out a disappointed sigh.

“There’s not more than ten,” Levi said. “But there is more than one.” 

“I’ve got that to look forward to.”


“You don’t like it so far?”

“No, I mean, I like it.” 

“It’s a classic, but I know what you mean.”

“Yeah.”

“Well, we should talk about it when you finish.”

“Yeah,” Ethan said. “Okay.”	

“We could start a book club.”

“That’d be cool.”

“For sure,” Ethan said as Levi turned back around and readjusted only to pull his foot to his face. Ethan threw up in his mouth a little bit at the sight of it, but Levi thought the sock smelled all right. 

The school bus was making its way over rolling hills, back through West Marin, and Ethan was well past the part about Holden debating the pimp, by the time he checked his phone. One missed call, and Samantha had sent him a text.

“Have a great game my forward,” she said. “Go score some goals, I love you.” 

Even though her less than sign next to the number three formed a heart, he sent a colon with a closing parenthesis and called back. 

“It was good,” he said to her. “I scored two goals!”

“Congratulations, honey!” 

“Thanks, Mom.”

“So,” Laura said. “What was the final score?” 

“Two to one, us, them.”
 

