---
title: "Sara VIII"
author: "Elizabeth Kolling"
date: "2025-12-20T08:54:00"
categories: [Sara]
description: " "
---

It wasn’t Saturday, December 20, after Semester's end. The eggs weren’t there, in rows of six, under the heat lamp. Beyond the window pane, Sara couldn’t see through to the kitchen where two cooks were angling in their own corners. The one with the double chin oiled no cast iron pan handed to him by the other who crossed into the dining room towards the bar seating and glass case of small plates and long platters. She was here, inhaling no scent of sardines, anchovies and cocktail sauce, with her head down in her home town. The city of pomp and circumstance, she thought as she shifted her weight on the wooden high chair, which wasn't red leather, and wrapped her right twice around her left leg towards *Adam’s Curse*. If she had nothing else in this life, no other reason for being, she’d have one thing: *a thought for no one’s ear but his*.

Sara had found him, pure as the driven snow, and then lost her way as he had. 

[insert more]

After a few moments, she felt the eyes of a stranger on her. So, she looked. There was a young woman who sat two chairs over from her, staring back before looking away and back again.

"Sorry, but I couldn't help but wonder," said Summer. "What is it you're reading?"

"Yeats," said Sara. "William Yeats."

"Mmm."

"Do you have a favorite?"

"I haven't read anything by him, actually."

"Oh."

"But I have a friend who's a poet, and I know she likes him."

"Oh, nice."

"Sorry, I just must be missing her. Sorry to interrupt."

(Summer starts to turn back towards her book.)

"What are you reading?"

"Oh, just a chapter on inorganic chemistry."

(Sara takes a closer look at the book in front of Summer. Realizes its not a novel. It's more so a textbook.)

"Is that for the MCAT?"

"Yeah. I'm sitting for the exam soon."

"Well, good luck."

"Thanks."