---
title: "Maximilian XX"
author: "Elizabeth Kolling"
date: "2025-11-01T13:04:00"
categories: [Maximilian]
description: " "
---


It had been a week and six days, and Max awoke as Alexis did, dreaming of a stick of butter, but not for the same reasons. 

He wanted to watch her spread it like she had last Sunday, like the lace veil of a bride, all delicate over the face of the dinner roll. Dinner in the Ascher household was at 5 pm on Sundays, so he knocked on their door, promptly at 4:55 pm. After a minute of self-doubt and steps backwards towards the elevator, it was a man with her eyes on the other side, standing tall and narrow and  intimidating. Her father, Max thought.

“Honey,” said the tall and narrow and intimidating man who turned to look behind him, where a long hallway was empty. “A young man is at our door.” 

The man turned around after no answer, to look Max up and down. 

“Hi, sir. I may have the wrong apartment number. I swore I wrote it down right, 9A.”

“Nine, eh? What’s your name?”

“Max, sir.” 

“Honey, a young man by the name of Max is at our door. Do we let him in?”

“I’m here for dinner, sir, sorry, I was told this is where the Aschers live?”	“Honey, a young man by the name of Max is at our door asking for the Aschers, and he is hungry. Who told him? Do we let him in to feed him?”

Since the man hadn’t at this point closed the door on him and instead opted for an investigation, Max started to consider the possibility that maybe, just maybe, he was the butt of a joke, and this strange man who stood tall and intimidating at the door was (maybe) trying to humor him. Maybe, just maybe, he was standing on the welcome mat of the correct stranger’s door. 

“If you let me in, you may have to roll me out.” 

“That starved, eh?”

As the corners of the man’s mouth rose towards his temples, and he cracked a smile, Max saw Sara emerge from a door at the end of the hallway. Her bedroom, Max thought as she walked the aisle. Max was far too unaccomplished to be thinking about Sara in a wedding dress, but this was the effect that she had on him.  

[insert more]

“Dad, stop torturing our dinner guests.” 

Hearing these words was a sort of paralysis, as Max started to wonder whether a dinner invitation to the Aschers at 5 pm on a Sunday was standard practice, nothing major in terms of meaning.

[Insert more]