---
title: "Samantha VII"
author: "Elizabeth Kolling"
date: "2025-08-21T16:09:00"
categories: [Samantha]
description: " "
---

“We’re going to be reading Plato’s Symposium this semester, since it’s fall and all.”
	
Ethan and Levi looked at each other, neither knowing what exactly Mrs. Zimmer meant by it.

“What do you think she meant by ‘since it’s fall and all?’” 

The three of them were walking together to the picnic tables after class. 

“Well,” said Samantha. “Fall is the season people fall in love.” 

“But we started dating in the spring.” 

“We’re obviously the exception.”

“But I think I started falling for you earlier, back in November or December or something.”

“Hah,” said Levi. “Save face much? Samantha, you must know Ethan had been crushing on you since he saw you in Philo the first day of school last year.” 

“Okay, way to kill my cool,” said Ethan. “I would argue it wasn’t love at first sight. It grew like a—”

“Square of filo dough in an oven set to 375.”

"When is your Grandpa going to pass down that goddamn baklava recipe?"

