---
title: "Maximilian XVI"
author: "Elizabeth Kolling"
date: "2025-09-03T21:41:00"
categories: [Maximilian]
description: " "
---


After he ran into Maddie at the cafe, he was thinking of Sara all over again. He thought he’d done the work to let her go, but it had been years since the summer after senior year, and those four years, still more since middle school, and he was still not over her. They grew up together, and the only person he ever really knew was her. She was the only one he thought he’d ever really know, in a city of millions of people. So, why had she disappeared on him like that, without a word? He had to ask her, face to face. He wanted answers. So, he asked a question.

“Hey," he said. “I don’t know where you are in the world and I know it’s been years since we last talked, but I still think of you. Are you still in New York City? This is Max, by the way.” 

Sara read the text as soon as it delivered, but she didn’t respond. She was addicted to her phone and had made a promise to herself that she’d never let him make her feel that way, out of control, ever again. But then a day passed, two, another still, and she discovered a habit of checking her phone for the stale message forming. So, she decided to respond for peace of mind. 

“Hi, Max,” she said. “I still have your number in my phone. It’s good to hear from you.” 

He saw the text hours after she sent it and couldn’t believe the sight: her name on his screen.

“Are you still in the City? Would you want to grab coffee?”

“What day works for you?”

“Any day, I’m free,” he said, then thinking himself too noncommittal. “How’s Thursday? Tomorrow, I mean.”

“I can’t tomorrow.”

“Friday or Saturday?”

“I could do Sunday.”

“Let’s do Sunday.”

“Sounds good.”

That was the end of the conversation, for now. 