---
title: "Don II"
author: "Elizabeth Kolling"
date: "2025-06-21"
categories: 
description: " "
---

June was half done, and the baby was about to leave the nest.

“I can’t,” Don had said to her before she too leaned in for a kiss, after their game of Twister back in May (that following Saturday). They were beside the hearth (no fire), bent over backwards in his living room, shoes off, one manicured hand on yellow. Another, on green. Laura had her socks on blue, and was flexing her high arch against the mat as Don spun the arrow. He was all on red, still somewhat guarded (same as her), and the tip landed on green. 

“Ah!” Laura said excitedly as he lifted his left leg up and over her lower back and reached for the far circle. It was too far, and he lost his balance. On the come-down, Don wrapped his arms around Laura and rolled onto his side to protect her from all the weight. He was 6’2 and 180 pounds. She was 5’5 and 125, perfectly fine, and crying happy tears.

“I like your laugh,” he said to her as she rubbed her eyes red. 

Don was on his left side, facing her, and she was on her back, staring up at the ceiling. 

“It’s kind of awful,” she said. “Where hyena meets Santa Claus.” 

He smiled and let out a small, sweet *ahah*, still looking at her. 

“Why do you do that?”

“Do what?”

He followed her eyes as she turned over on her right side to look at his sky blue. 

“Put yourself down like that.” 

“Compliments make me uncomfortable.”

“You’re not comfortable?”

“No,” she said. “I am.”

There was a beat of silence, and then Laura sat up. Don felt the moment fall away from him, and he pressed his palms against the rug (Persian, floral) to sit up too. 

“Is everything okay?”

“Yeah,” she said. “It’s just…”

“What?”

“I should go."

It was still early in the night, not even after eight, and they hadn’t even gotten to the part where they took a walk around the neighborhood. 

“Are you sure?”

“I’ve got an early morning tomorrow.”

“Right,” Don said. “Vinyasa with…?” 

“Kundalini,” she said. “With Stan.” 

“I still can’t believe Stan is your yoga teacher.”

“What do you have against Stan?”

“No, nothing.” 

“Okay.” 

“He’s the one with the coy fish on his arm, right?”

“What?”

“The one with the tattoos?”

“Yes, he has tattoos, and?”

“Nothing, just checking.”

“You’re being weird,” she said. 

Don brushed it off and took one corner of the Twister mat as Laura took another at the other end. They folded it once, so that green met red and met in the middle. They stood there facing each other, holding up the mat, knuckles touching knuckles. Only the thin plastic mat separated them, and the game was over. Don leaned in and kissed her. She kissed him back. Then, he pulled away. 

“I can’t….” he said. “We shouldn’t.” 

Laura didn’t say anything at first.

“I’m so…stupid,” she said. 

“No, you’re not—my mistake.”

“I should—go.”

“You don’t have to,” he said.

“I think I do…have to.” 

Laura plucked her empty wine glass (his tea mug) from the coffee table and walked straight past him to the kitchen sink, where she filled the lipstick-stained glass with tap water and tilted her brain back, twice. She reached for the soap and sponge and started at the rim as Don stood still in the living room, thoughtless, pretty paralyzed. He had felt something, which scared him. 

By the time Don returned to himself, Laura’s sandals were no longer next to his boots in the breezeway. Halfway home, she had walked the dead end back to Main Street and jaywalked across two lanes of traffic going in opposite directions. She reached the bike trail, alive with feeling, hurt but happy it happened. Bay laurel beckoned, and eucalyptus spread its seed but the mother owl was long gone as the newborn (Great Horned) nested, abandoned. The weeds were everywhere, and the soil on either side of the new pavement was piecemeal picked apart. The blackberries weren’t yet ready, but the bird-box library was aplenty, whispering sweet nothings. 

*Take one, leave one*, it said to her (and every passer-by). *Live, and let be.* 
