---
title: "Catherine"
author: "Elizabeth Kolling"
date: "2025-07-19T13:01:00"
categories: 
description: " "
---


Catherine was waiting up for him downstairs while Sara was over at Maddie’s (standing Monday sleepover during summer), and it was almost midnight when the keys jostled in the lock. She had been on her phone, scrolling Facebook, but managed to pick up a book without a peep by the time she heard the door creak open. 

His phone hit the hardwood floors as he bent down to untie his Oxfords. They were dark brown leather, and his footsteps were as heavy as ever through the breezeway. His lack of precision was a good sign, Catherine thought, and he didn’t seemed surprised to see her.

“Hello, my love,” he said, gently holding each of her shoulders as he leaned in for a kiss on the  cheek. She took it on the chin. He didn’t smell like alcohol, which was maybe a bad sign, she thought. Having an affair sober was even worse, and she would rather he have fallen into a hard drug addiction than so easily out of love with her. But, that's not love to think that way, so she bowed her head in shame at the thought. What had she not done? Nothing. She'd been massaged and micro-needled and rose-watered in lieu of perfumed and manicured, overall everything. She hadn’t at all lost her youtful looks. She looked the same as she had in college, for heaven’s sake, so what gave?

“Hi,” she said without flourish. “How was your day today?”

“Busy,” he said, leaning back in the grandfather chair across from the couch. She saw his choice of seat as a bad sign, because he wasn’t going out of his way to be close to her. He knew very well physical touch was her love language. 

“How was work?”

“Busy,” he said.

“You stayed late.”

“Investor meetings.” 

"Are you hungry?"

"I am hungry."

“Have you eaten dinner?”

“No, I may make something.”

“I’ll make you something.”

“No, that’s okay, actually.”

"So you're not hungry."

Catherine was suspicious, and there was silence a moment.

“Where’s Sara?”

“Maddie’s?”

“Oh, right, Monday.”

“Hey, are they?”

“No, James, jeez.” 

“Sara likes Max.”

“Who’s this Max?”

“He’s a very nice boy.”

“I think I’d like to meet him to see about that.”

“James, they go to school together.”

“Where does he live?”

“I believe he’s on the West side.”

“Where?”

“What does it matter.”

“I want to know if he’s good enough for our daughter.”

“James, I don’t think we need to worry about that.”

“Why?”

“I have a feeling Max likes Maddie.” 

“Why do you think that?”

“It’s just a feeling,” Catherine said. “I saw the three of them together. I always see him on Saturdays.”

“Why is that?”

“He wants to be a painter.” 

“I don’t like him.” 

“James, don’t be so judgmental, you haven’t even met the poor boy."

“Then let’s have him over.”

“What?”

“Sara’s birthday is coming up, so let’s throw her a party.”

“That sounds nice, I’ll plan everything.”	

“So how do you know Max likes Maddie instead of our Sara?”

“I saw him look at her the way you used to look at me.”

“Used to, honey, what are you talking about?”

“I don’t know,” Catherine said. “You tell me.”

“My eyes are weak from looking at reports all day, but that has nothing to do with you, my love. I feel as strongly towards you today as I did the day we met. Even more so.”

“I’d like to think so.”

“My love only grows.”

“I don’t want there to be secrets between us.”

“I tell you everything that matters.”

“No, see, that there, that’s not enough. I want to know everything, not just what you deem to matter.” 

“Okay,” he said, rising from his chair. He stepped towards the couch and knelt before her. 

“Why are you looking at me like that.”

“Because I love you so much.” 

“Then why don’t you come home earlier.” 

“Can we talk about this in the morning?”

"No."

"Please."

"No, James."

"Pretty please?"

She couldn’t resist him when he looked at her like that. After all, she knew that look and believed she was the woman he loved, the only one (besides Sara) he had chosen to build his life around. So, she let him as he leaned in to kiss her. 
