---
title: "Red Bird II"
author: "Elizabeth Kolling"
date: "2025-08-13T10:43:00"
categories: 
description: " "
---


“Just give me a second!”

“You-you-you,” said Red Bird whose whimper then was pink salt down the cheek as the gentleman methamphetamine user continued the search for a vein up her varicose leg. “You can’t speak to me that way.”

“I’m sorry,” he said.

“You know I’m a sensitive person.”

“It’s just frustrating. I can’t find a good vein to save your life.”

“Hey,” she said sharply, with a smile. “What are you trying to say about my veins?”

“They’re the worst.”

“I’ve seen worse,” she said.

“I’ve seen better.”

“That’s why we work,” said Red Bird, looking for his eyes as they saw exactly what they hadn’t seen before. There was a bright blue vein like ebony framing an Italian Renaissance painting around the right eye of Red Bird.

“I found it.”

“We complement each other, and it’s you I found.”

Red Bird blushed, savoring the words he'd never say in the space between blinks, thinking then and there how life was lovely at long last. Her heart was beating fast, even though she hadn't been looking for someone new. Was she in love with the gentleman methamphetamine user, who had stolen a pen for her expression and offered her his spoon and searched her veins before his own even though he too ached? Yes, no, Red Bird decided to solemnly swear. She would tell the truth, the whole truth, and nothing but the truth about her name and where she came from andhow she had come to know herself, so help her God.

“Hey,” she said, sincerely.

"Hi," he said.  

“What’s your name?”

“If I told you,” he said. “I'd have to kill you.”

It was the way he said it. The words shot an electric current of intuition through her nervous system, and the earth fell away from Red Bird before the gentleman methamphetamine user could even smile wide with teeth. Not grinning, endlessly forgiving, she inhaled, exhaled, and smiled back weakly, wondering what exactly he meant by it. Giving in, she looked once more across the way and back at him.

“Kill me, then.”

Holding soft her cheek, the gentleman methamphetamine user traced the skin above her eye with the tip of the needle, pointed the bevel, and pushed the plunger, as she wished, and licked his lips as eyes, wide, watched the viscous elixir fall like Lucifer, down the barrel. In an instant, Red Bird was blue, spread-eagle across the sidewalk, silent as spring.

“You killed her!” screamed the old woman in the wheelchair.

“I didn’t kill her,” whispered the gentleman methamphetamine user to himself, as he held her heavy head. His eyes welled with tears, as he heard the mourning song. 

“So much potential!” screamed the old woman in the wheelchair. “Wasted!” 

“And let her instead waste away like this?” said the voice in the head of the gentleman methamphetamine user. 

“This is fate. This is justice. Everlasting peace of mind, even for the demon, and justice prevailing on a Holy Sunday in the Tenderloin of San Francisco, where at least one is well, is a deed well done!”


“I didn’t kill her,” said the gentleman methamphetamine user to no one certain who would
listen. “I didn’t kill her!”

The gentleman methamphetamine user looked one last time into her eyes. They were open,
staring up at the sun.

“I never realized,” he said. “They’re greenish-brown, with gold, carats of amber, at the center.”

He closed the lids, and laid Red Bird to rest. He looked right. He looked left, and then left her there pressing his thumbs to his eardrums as the old woman in the wheelchair called after him. Each word was like an ambulance on its way, roaring like the sugar-high kids in the classroom. They had laughed as Sister Mary finally fell, and he even started to believe her.

“Judgment will fall upon you, you killer!”