---
title: "Levi XI"
author: "Elizabeth Kolling"
date: "2025-08-05T19:45:00"
categories: [Levi]
description: " "
---

He read through the texts, and kicked himself for trying to be clever when he could have told the truth. He decided not to text her. Maybe, he'd go grocery shopping just to feel something. But she didn't work there anymore. She'd moved out of state for college and on to bigger, better things.  

Before all of this, he turned towards the automatic doors. Seeing Samantha there, and talking to her, made Levi forget why he had gone to the grocery store in the first place. What for, he thought. So he left. 

"Did they have any ripe ones?"

Don was sitting at the kitchen table under the dim chandelier, writing what looked to be a letter.  

"Uh," Levi said, still unsure what it was. "They were all out."

"Oh, weird."

"I mean, there were none ripe ones."

"Thanks for checking."

"Yeah, no problem."

"Something the matter?"

"Huh? No."

"You seem—"

"I'm pretty tired. I think I'm going to do some reading, or take a nap, before Ethan's tonight."

"All right."

"What are you up to tonight?"

"Oh, not much. I think Laura's going to come over for dinner."

"Oh, cool."

"I better start cooking, actually."

"Or, maybe you could cook with her, could be nice."

"Instead of having everything ready?"

"Maybe just save the potatoes to do together and the salad or something."

"Potatoes?"

"Or whatever side you're planning on."

"Potatoes are a little presumptuous."

"Dad, you eat potatoes for breakfast, lunch, and dinner."

"They're a staple, what can I say?"