---
title: "Summer X"
author: "Elizabeth Kolling"
date: "2025-09-30T23:26:00"
categories: [Summer]
description: " "
---

[insert more]

Summer picked pineapple. 

Adrian wanted to do a banana. 

Igor, an apple.

Alexis chose strawberries.

Samantha, avocado.

Matthew picked quince.

Jamal, red grapes. 

Kirk chose kiwi.

Nia picked the durian.

Jonah, an orange. 

Freddie picked the mandarin. 

[insert more]

“For next week, we're going to explore action. Now, what is an action? Anyone?"

"Stepping on someone's heels," said Jonah. "You know, when you flat tire someone."

"Thanks, Jonah. Yes, actions can be physical, but they can also be psychological. That's what we're interested in, the psychology. So, in the example of stepping on someone's heel, the actor doing the stepping could be trying to do what?"

"Embarrass the person in front of everyone."

"Yes, so the action is to embarrass. It's a verb. So, homework for next week is to explore an action. I want you to develop a character who is 80% one thing. The question is why, What motivates you?” 

“Fear,” said Jonah. 

“Yes, fear, that’s a good one.”