---
title: "West Side Road"
author: "Elizabeth Kolling"
date: "2025-12-26T08:38:00"
description: " "
---

Dear —, 

The other day I drove West on the way back instead of East Side Road, which has to mean something worth writing about. 

"Don't end a sentence in a preposition." 

The other day, Dad warned us with the softness of speech that comes from missing someone. What would she think? How would she feel? Grandma, who was an English teacher.

[insert more]

We're in the Italian market next to the Italian restaurant, next to the Gun Club. I've never seen proof, but I know somehow. The kitchens connect, and you can order at the bar. 

Sonja is restocking the chicken cutlets. She puts out paper sleeves and a pair of tongs to grip the flattened breasts.

[insert more]

Mom spots a little bottle of chili oil, like the ones on the tables in the tall glasses nextdoor. It's just chili oil. Still, something about Diavola's is different. 

"We can bring this to Pizzaiolo. Carry it in our purse!"

We like to drown the crust.

"Ooo!"

My eyes are on the cards overhead, in a basket above the pasta case. I consider the pomegranate. The golden delicious, and I don't know what the two of them are talking about. 

"What is it?"

My sister hands it to me.

"Careful," she says. "It's oily."

I've been holding the inheritance for no more than a few seconds, and already I've exercised no care.

"Should I oil the ends of my?"

She looks at my curly mess. The air always has a way of (stripping each strand of well intending conditioner) taking the moisture out.

"Ew, don't."

"Do we really want this?"

"No, it's okay."

"Where does it go, here?"

I set it on the wooden table and don't consider the imminent stain. It's invisible to the two of them who head towards the counter, though I hesitate, as regret overtakes, before pairing up my palms. I move on, rubbing in the neon orange. I don't believe in lotion. Lotion is mostly water, and water dehydrates you. 

She gives me a look that says, *you're so strange, but I love you any way*. 

[insert more]

I drink four or five short glasses during lunch. 

[insert more]

I believe in coasters on a glass table, and Venetian glass rings. Every thing owned is an exercise in care and intention.

[insert more]

"Should I get it?"

"Hmm," she says. "How much is it?"

"Seven dollars."

"Uh, not worth it."

I put back the apple, but for some reason I can't let go of the fuchsia. I remember how we sat there, shoulder to shoulder, staining each other's pastel cashmere sweaters as we plucked each bead from its bed into a bowl on Thanksgiving. The pith reminds me of the skin a snake sheds after hibernation season (winter) come spring.

"Good salad."

"What's in it?" 

"____ ____ ____ ____"

"What kind of lettuce is it?"

"Uh, green leaf."

"Oh, right."

[insert more]

Each sentence ended in a preposition, started in the passive, is subversive. Call it a literary flare.

[insert more]


Love,

Elizabeth Kolling