---
title: "Derin Dribben II"
author: "Elizabeth Kolling"
date: "2025-08-26T17:02:00"
categories: 
description: " "
---


“How did you two meet isn’t something I would ever ask.”

“No?”

“No, I would never ask the couple sitting across from me that awful question, for instance…”

“Because—”

“Because, it’s a bore,” said Derin Dribben who leaned forward on the long sigh, reaching for the short black that had just been set down (by one of the summer interns, on the table in front of him). He took the shot and inhaled through gritted his teeth after the swallow.

“Not a fan?”

“Should’ve been bourbon.” 

“Do you want bourbon? We can get you bourbon.”

“I would,” said Derin Dribben. “I would like bourbon. Too bad I’m 20 years sober.” 

“Shoot, I’m sorry for offering.” 

“Have to keep your sense of humor.”

“Of course,” said the woman with the microphone, letting out the nervous laugh. “Well, that may be the perfect segue, so pivoting slightly, if that’s okay, but…what’s the story behind the character Herb.”

“The story?”

“Yes, or what was your inspiration?”

“Oh, I haven’t been inspired since 1970,” said Derin Dribben. 

"My notes here say you were born in 1982." 

“Herb, by the way, hard H.”

“Herb, hard H, sorry. So, where does it come from then? I can’t help but notice some similarities between him and—”

“Are you asking me if I’m Herb? If so, I can’t help but wonder what I think you are wondering when you ask it. I mean, Herb is an alcoholic. Are you asking me if I’m one? In front of all these lovely people?”

“No, no, of course not, no.” 

“Because that would be extremely uncouth.” 

“No, I’m so sorry, I absolutely was not implying—”

“Oh, I’m just giving you a hard time. So, why don’t you ask me something else, or where were we before your people poisoned me.”

“We were discussing chapter 19, and what it means for Red Bird to finally meet someone. My original question was how the two of them met, since it’s not completely obvious to the reader or explored.” 

“Ah, right, I remember, your question…that god-awful question everyone who hasn’t read the book asks…” said Derin Dribben. “Kidding. It’s all in there, if you really look for it, but if I’m being honest, and I’ll try to put this lightly. In this life, paths cross, and people call each crossing a miracle, Clotho, Lachesis, Atropos, they usually come in three, you see. In some ways they are miracles, fate personified, blah, blah. What I’m interested in, or what is truly miraculous, to me, are our degrees of separation, minuscule, in my opinion, like intricately spun social webs. Have you ever read Charlotte’s Web? I’m interested in how the world is small, large at the same time, and why people stay together. Forget the meeting. I mean, the point is that the two of them, Red Bird, Buck Wilde, they don’t necessarily remember meeting each other. It wasn’t love at first sight. It was interest peaked at first sighting. They were both curious, cautious. He saw her walking down Capp street that one day in late August, and that was a major turn-off. He was over her the minute he saw her, until he wasn't. Any way, it wasn't like she liked him either. In the beginning. But then, the fall happens. He sees her sitting on that peak, the one they each go to for different reasons, and she surprises him just by being there. I don’t want to say any spoilers, but…”

“Interesting, thanks,” said the woman with the microphone.

[Insert more] 

“I think I’m still stuck on what you said earlier. So, if we come across a couple, what should we ask them.” 

“I’d ask them,” said Derin Dribben. “How did you two meet halfway?”   

“Mmm, meeting each other half way, because compromise is so important, in any relationship.” 

“War and peace, love and compromise.” 

“Sometimes you don’t get what you want.”  

“It’s true.” 