---
title: "Fran"
author: "Elizabeth Kolling"
date: "2025-08-09T12:07:00"
categories: 
description: " "
---


“Hey, Sam, it’s 2 pm!” 

The cute checkout girl reminded Samantha of Fran (the old woman (checkout lady) who was age 62 when they met), because of her loudness and enthusiasm, and suddenly she was back there on memory street, and it was the summer before junior year (Ethan was teetering on being out of love with her): 

Samantha took her lunch break outside at the back of the store, where there was a milk delivery happening and Fran was smoking a cigarette. She ate her peanut butter and jelly sandwich softly, in small bites. She chewed as if each bite down were a —

“What is that?”

“PB&J”

“Strawberry?”

“No, uh—”

“Raspberry?”

“Blackberry, actually.”

“Huh,” said Fran on the exhale. “Three more years of this hell, ‘till—”

“Wait, what’s in three years?”

“In three years I’m 65 years old, thank Jesus, Mary, and Joseph.”

“Oh, I see,” said Samantha. “Hey, happy retirement.”

“Not celebrating yet, but yes, social security is saving grace, and I’ve saved some.”

“Nice.”

“So, what’s the first thing you’re going to do when you retire?”

“Sweetheart, I haven’t a clue what I’m doing for dinner tonight.”

“I don’t either.”

“But I have given it some thought, and I’m gonna go to Italy.”

“Oh, wow, that sounds awesome.”

“Have you been?”

“Oh, no, just heard great things.”

“Me too.”

“My boyfriend’s actually there now.”

“And you aren’t?”

“Well, I mean, I’m on the schedule through August.”

“Who’s he in Italy with?”

“He and his mom are doing a little European tour.”

“The mother? Oh, that’s not too bad. Better than a solo.”

“Fran, I’m not really worried about him—”

“Cheating on you? Of course not, I mean, look at you.”

“Oh, haha, thanks for saying that.”

“I mean what I say, I mean."

"Thanks."

“So why’d they not invite you?”

“They did, or he did. I mean, he mentioned that it’d be nice if I could join them…he said he wishes I could join.”

“Samantha, let me tell you something, now I know I may not look it these days, but back in the day, I had men fawning, fighting over me.” 

“I believe it.”

"Whatever you do, Samantha, don't start smoking."

"Thanks, Fran. When did you start?"

"It'll take your looks before anything, the skin it starts to wrinkle, and then you'll really want to—”" 

"I think you have nice skin."

"You're sweet." 



