---
title: "Maximilian XVII"
author: "Elizabeth Kolling"
date: "2025-09-05T21:25:00"
categories: 
description: " "
---


Further still, there’s a Rodin of a woman compressed like an unflung coil. Unhappy and overburdened, she carries an urn on her shoulder and leans into the elbow for comfort. This silence and succor from no one else but herself, and is this where we part, he wondered, shoulder to shoulder, dead silent in front of—

“There’s a fish at her feet.”

“Huh, what I’m wondering is why there are slits in each side of the wooden boxes.”

“It seems Cupid shot the painter with his arrow.”

“But Cupid’s still aiming his arrow. To me, it seems he hasn’t even shot the bow yet. So it begs the question of whether the painter didn’t even need angelic intervention to be taken with his model.”

“His model is half woman half stone.”

“Technically, marble.”

“You’re right.”

“I feel wrong about most things.”

“One thing is for certain,” said Sara, looking at the two heads with their mouths wide open (she yawns in response).

“What?”

“She has a nice butt.”

“Tired? 

“I think I’m getting there.”

“Maybe we should call it. Besides, I think it’s almost closing time. 

“If we don’t get out now we may very get locked in here.”

He wanted to be locked in, with her for forever.

“Good point.”

“But first, back to the heads on the shelf to the right. Are they shocked that the two of them are making out?”

“They may be trying to warn them or alert the rest of them.”

“The face below, also, the one on the bronze shield is making the same face as the heads.”

“Maybe there is a fish at her feet because she is just one fish in the greater sea of sexual exploits.”

“You think the painter has had many lovers?”

“I mean, doesn’t everyone?”

“No, not everyone, I think.”

“Meanwhile Cupid is sly with his expression overhead.”

“Yeah, he knows what he’s doing.”

“He has really nice arms, and hands.”

Max didn’t know what to say to that. He thought maybe the fall was starting.

“The woman in the background is holding a mirror to her face and holding her chin.”

“She is, good eye.”

“See how Jean-Léon Gérôme creates this tension between the hand of the painter figure and the mirror. It’s like the Sistine chapel, again, Michaelangelo’s hands touching, and I wonder: are the women in the background, those sculptures, his former lovers, lined up in the back of the room like how we line up all of our lovers in our own minds?”

“I don’t know, do we?"

“The woman to the left of her has a child.” 

“How many children did he have?”

“Who?”

“The painter.”

“The painter in the painting or the painter painter.”

“The painter painter.”

“I don’t know.”

“There are also figures in long red capes in the painting on the wall. Are they women? I think they’re women.”

“One of them is ascending the stairs, and it looks like the others are in line.”

“What do you think’s the meaning of the mallet on the floor at the center of the foreground?”

“The artist abandons his art when he is in love.” 

“But aren’t you supposed to be inspired when you’re in love?”

“Maybe he’s just in lust here. And like you said. she is probably one of many that came before, many who have yet to come.”

“Maybe, it’s that the artist abandons her art when she is preoccupied with her lover.”

“It must mean they are different from each other, differently gifted or at least interested, not to presume talent, no?”

“Yeah, otherwise I think they’d be making the art together instead of taking each other away from it.” 

“I’m just now seeing the stairs in the foreground behind this embrace.” 

“Looks like they are sort of mirroring the painting on the wall.”

“Good job Jean-Leon Gérôme, you’ve created the perfect painting, very self-referential and intentional.”

“Should we read the plaque now?”

“Sure.” 

“Let’s see what it says.”

“Oh, said Sara.” 

“We were way off.”

“It’s about Metamorphoses.” 

“Hmm, well, we will try again next time.”

“Hey, since you’re sleepy (yawning and everything), do you want to see something. Also, since it’s the beginning of harvest season?”

“What a way to refer to fall or really the end of summer, I would love to.”

“It’s just over there.”

They turn around. Across the aisle and a few paces down the corridor towards the rest room is a painting by Pierre Puvis de Chavannes. There are women in the field, sleeping, and men too. 
