---
title: "Levi XVI"
author: "Elizabeth Kolling"
date: "2025-11-18T11:16:00"
categories: [Levi]
description: " "
---

Dear Mom,

I was born on a Tuesday, which means something. You could have named me Kobi or Kwabena or Ebo. You didn't. I do like the name Levi. I know it’s been a while since I last wrote you, but I knew you would understand and give me grace. It's not a reflection of the love I hold for you. And I’m writing you now, in the hopes of working through the why. Thank you in advance for reading what may only be described as a never-ending stream of consciousness. As Heraclitus says, we never step into the same river twice. Life changes. *He* says, “the death of her child…is the worst thing that can befall her.” He’s talking about a mother, of course. If I were to talk about a child, a son, I’d say, the death of his mother (or father) is the worst thing that can befall him. He talks of not knowing the exact day he was born. His reference is a cargo ship, a shipwreck. He says, “she lies today…deserted by all but the surf that destroyed her.” You didn’t desert me. You didn't destroy me. You breathed life into me and made me better. You’re with me, everywhere I am. 

[insert more]

Love,

Your Levi
