---
title: "Don"
author: "Elizabeth Kolling"
date: "2025-06-15"
categories: [Don]
description: " "
---

Sundays were for popovers, a family recipe passed down from Nana and Papa on Ethan’s mother’s side.

Laura would creep downstairs in the early morning, as a force of habit. She’d go first into the kitchen and then carry an ice cube into the bathroom. She’d stand in front of the mirror, look at the fine lines and carve the freezing feeling like a slab across her face, from her lower cheekbone to her forehead. She’d close her eyes, and bring it over her lids, but the *beep-beep-beeping* would bring her back to earth. Soon enough, every time. She’d brace the edge of the sink, bow her head and inhale deeply before slamming the freezer shut. She was out of body, sometimes. No matter how many times she tried for closure, she’d always fail to close the door completely, and it would start again. 

*Beep, beep, beep.*

With a beet-red face, she’d take out the eggs and the milk, pasture-raised, and place them on the counter, next to the butter and flour from Saturday. It was gold Calacatta marble, imported from Italy (Carrara), and she’d made a mornay sauce with Don the night before. The pasta was fusilli, the twisty kind. There he was at her front door, dorky-looking, his veins protruding from strong arms that had hugged her goodbye.

“Come over,” he had said. “I’ll cook for you next time.” 

“I’d love that,” she said back, leaning against the frame. “Saturday?”

“Saturday.”

He had said it with a smile as he started to walk backwards (a few lingering glances) towards the cul-de-sac, and everything was calculated in the mind of Laura. She’d use about eight tablespoons for the mashed potatoes, emulsified for texture, and cut a slab for the table, leaving about six tablespoons, just enough to double the recipe and bring a few to Edith who was 92 years old and had no next of kin next door. Laura didn’t like to be left alone and Ethan tended to spend Saturday nights with friends or Samantha, so she’d call up Levi’s father.

“Hi, Don.”

“Laura…”

“So,” she’d say. “I have a whole bunch of heirloom potatoes that I just picked up from the farm stand, and...I was thinking...the boys are going to that party tonight...so...would you like to come over for dinner?” 

“I don’t know, I was just going to have a late lunch.”

“Can’t start skipping dinner, now Don.” 

He didn’t want to say yes, but he couldn’t say no. 

“Dinner sounds good.”

“How’s seven, or six?”

“Six works,” he said.

“How about this,” she said. “We’ll make it together to buy you some time, build up an appetite, and we’ll eat later.”			

“Laura, you know I’m a bull in a china shop when it comes to the kitchen.”

“I can show you how to use a cutting board.”

“What can I bring?”

“Nothing,” she said. “You can bring yourself.” 

Laura was flirting with him, and Don knew it.
