---
title: "Laura III"
author: "Elizabeth Kolling"
date: "2025-07-03"
categories: 
description: " "
---

Laura hid with her shopping cart behind the sweet corn. It was the day before the Fourth, and she didn’t want him to see her looking like this, wearing flip flops. She wheeled her cart away as he reached for the sweet potatoes. 

I’ve always called them yams is what she had said to him, as he took out the sheet pan back in May. The oven had been set to 400 degrees Fahrenheit, which she thought was too harsh, he was 51 years old, and he’d never read Ray Bradbury. It was all coming back to her, like a motion picture. 

“I can’t believe it,” she had said to him. “It’s an absolute classic.”

“I’m just as shocked as you are.”

“Why didn’t you read it like the rest of us?” 

“I went to a private school,” he said. “Nothing about our curriculum was status quo, which is something I’d say I regret, but I’ve never been inspired to revisit it or make up for, I don’t know, lost literature.”

“We better do something about it.”

“Oh, yeah?"

“Yes, I’m going to bring you my copy,” she said, hoping to be the inspiration he’d need to read it finally. “I definitely still have mine, it is packed away somewhere, but it’s somewhere. Maybe Ethan knows. He’s always fishing around in the garage for things.”

“That’s nice of you, Laura, but really—”

“Just please, whatever you do, don’t judge my annotations,” she said. “It’s more underlining than anything.”

“Ah, the great underline.” 

“Yes, it’s an act of pride, really.” 

“Mmm,” said Don, after swallowing some chamomile.

“I mean, what is it?” She said. “This overwhelming need to underline?”

“I think we underline the lines that make us feel seen or a little less strange, and maybe we can’t put that into words so readily.” 