---
title: "Madison III"
author: "Elizabeth Kolling"
date: "2025-09-28T12:53:00"
categories: [Madison]
description: " "
---


“Good morning,” he said to her softly as her eyes fluttered open.

Those green eyes were his loss of words (~loss for words), every time. She looked at him, speechless, unblinking, and had a feeling that they had, at some indiscriminate moment, entered into an unspoken staring contest. Meanwhile, he was lost in thought about how her lips so perfectly halved. She pressed the one harder into the other half as her smile broke. Her nose scrunched as she let out a laugh that ended up sounding more like a cry. He noticed she was holding her forehead in a rather dire way.

“My head hurts,” she said as she started to massage her temples. 

She was so cute when she was hungover, a light-weight, and he loved her.

He was the first to say it, which freaked him out, though she insisted that she was the first to feel it. 

“I knew I loved you when I started peeling you that cutie in the library.”  

He brought her two hands down to his chest and started massaging her temples for her. She closed her eyes, even started to doze. Freddie was the one who needed the sleep. Ever since he could remember, he was always last to fall asleep, first to wake up. This meant he hardly slept four hours through the night.

[insert more]

“I didn’t know what a Manhattan was,” she said. “Now I know never again.” 

“Maybe stick to your Hugo Spritz.” 

“Mmm,” she said, stopping herself. 

“What?”

“Nothing.”

“No, tell me.” 

“I like the name Hugo.” 

“I do too.”

“You do?”

“I do.” 

“Good to know.” 

“You’re very mysterious this morning.” 
 
[insert more]

“If we get married and have kids,” she said, stopping herself. 

“Yeah?”

“If we have a boy,” she said. “Can we name him Hugo?”

“I don’t see why not.” 

“Nevermind, it’s a stupid question.” 

“No,” said Freddie. “I didn’t say it how I meant it.”  

“Oh.”

“What I meant was, I can’t imagine an alternative world where we don’t get married and have kids and have a boy named Hugo.”

“Gee, you’re so subtle.” 

“Okay, Miss Marry Me.” 

“Who’s Mary!”

Her foot was a hook, all of a sudden, latching onto his ankle as she lifted her left leg over his torso and pulled herself upright on top of him. She pressed her palms against his palms and looked down at him.

“You look like the emoji of the man with his arms raised over his head.” 

“And you, my love, look like that zombie lady.” 

“What!” 

(She did look a little dead, after the night out they’d had).

She leaned forward, now nose to nose with him. 

“Sorry, I meant a mix between the zombie lady and that woman blowing wind.” 

“You’re tell *me* I have bad breath? Take it back, or I’ll kiss you.”

“I take it back. I take it back! So foul and fair a breath I have not smelt. Emphasis on fair, my dear maiden.” 

[insert more]

He watched her get dressed while he lay in bed.

“So,” Maddie said. “What are we going to tell him?”

“Who?”

“Our son, Hugo.”

“That we love him.”

“No, no.”

“That we don’t love him.” 

“About his name. I mean, are we going to tell him the truth?”

“The truth?”

“That we named him after his mother’s choice of cocktail.” 

“We lie.”

“That’s what I was thinking.” 

“We tell him we named him after Victor Hugo or Hugo Häring.” 

“Who are they again?”

Freddie sighed inside, even though he didn’t blame her for not knowing. 

“The first guy is a writer and a poet and a playwright and a politician, and the second guy was an architect.” 

“Häring sounds a bit too much like a fish, so let’s go with the first guy.”

“Fine choice,” said Freddie, reaching out his hand. “Nice doing business with you.”

She shook his hand, and pulled him towards her. 

“Alright, rise and shine.”