---
title: "My First Writer's Group"
author: "Elizabeth Kolling"
date: "2025-06-11"
description: " "
---


Dear —, 

At the liqour store on Nostrand Ave, an old woman sits, asleep, in a beach chair, behind the bullet-proof glass. The store is mostly an open floor for customers, and it's a narrow aisle bordered by shelves that are chock-full of bottles for the owner to reach for. I walk up to her, towards the end of the long runway. There's a sign that warns about being 21. I'm 25, under-accomplished, and my *excuse me* rustles her awake. I say, "How much for the Josh?"

"18."

She sees it on my face, the sure reluctance of a working woman spending what could be savings. 

"15 for this one," she insists, holding up one of the Projects. 

"And the Bacchus?"

"13." 

I ask for both, and carry the paper bags a block and a bit.

Two and a half hours later, it's 10:24 pm. There's an A train in 8 minutes from the Nostrand Ave station, and I just left my first writer's group. I said the experience of reading the young woman's writing was like standing in front of the stovetop, searing something in a cast iron pan. The steam, rising. I stand on the platform, in front of the Fire Department Standpipe Outlet as the rat's tail threads the third rail. 

Today an acquaintance asked me if I had a black eye. No, I said. It was just my face, the blood in my veins, blue beneath the surface. A thin man is bent over, reaching into a backpack. He's wearing purple pants made of a shiny fabric with a matching jacket and has a bottle of vodka. Either that, or water. 

The young woman asked if anyone had ever seen *La Ciénaga*. I couldn't remember the name of the fillmmaker, but I remember thinking she was like Alfonso Cuaron, except a woman, without the commercial viability. I mean, success. I Googled her later. Apparently the ex-CEO of Google just purchased a 24 million dollar home in San Francisco, and her name is Lucrecia Martel. Sometimes we consume what we don't crave. I've been staring at the screen for at least eleven hours today. 

Love, 

Elizabeth Kolling
