---
title: "Maximilian XIV"
author: "Elizabeth Kolling"
date: "2025-08-07T07:30:00"
categories: [Maximilian]
description: " "
---


Bananas, beans, almond butter, whole wheat always, no cheese, small green cucumbers and tomatoes out of season, even though it all tasted like water to him. He had a list, and he didn’t feel anything when he went grocery shopping. He wanted to make a salad, and salty-sweet toast for breakfast, so he reached for the bread. 

Max didn’t know when it started, when he started to feel nothing instead of everything. He thought maybe it had something to do with his dad leaving. Just like that, even if it was his mom who had messed up. So what if she—

He didn't like thinking about it. He could’ve at least stayed in the same city for his sake, and—

Just like that, he up and left, and was—

“Next in line.”

Max took a few steps towards the corral.

“Nine.”

Max raised his chin towards his forehead and walked on. The cashier was pretty cute, but her voice was pure shrill.

“Hi! How are you?! Find everything okay?!”

Max never knew the point of asking, or what the question meant. Of course the store was a conundrum, but sorting it wasn’t some big feat. Yes, the place for some particular item did seem to change, visit to vist, but it was *grocery shopping*. It wasn’t rocket science, or the Collatz conjecture.

One simple thing changed everthing. He was now mad but mute at checkout. 