---
title: "Freddie VI"
author: "Elizabeth Kolling"
date: "2025-12-21T14:00:00"
categories: [Freddie]
description: " "
---

After the dough had been kneaded and folded, and it rose in the oven, Freddie worked the counter. 

[insert more]

Twenty minutes to closing, a young woman walked in with an urgent eye on the cake case. 

"Hi," she said. 

Freddie, who hadn't noticed her enter, looked up from the page and set the play face down on the counter.

"Hi, may I help you?"

"Yes, please. I came here for cake." 

"You came to the right place."

"Great. Let's see..."

She looked at the carrot with an expression that Freddie couldn't quite read. 

"We have quite the selection of cupcakes too, or cookies. You probably aren't interested in cookies."

"Cookies aren't quite like cake."

"Right."

"Don't get me wrong. I love cookies. But, for a birthday..." 

"Ah, I see. Well, the red velvet is our bestseller."

"Mmmm."

"You don't seem sold. You know, I'll leave you be. I don't want to hover. I'll be over here. Just let me know when you're ready, and I'm right there."

"I think I'm ready actually."

"Oh, great."

"I'll do the lemon drizzle." 

"Good choice. That's my favorite." 

Freddie reached into the glass case and lifted the round onto the butcher block.

"Would you like me to write anything in particular?"

"Uh, maybe Happy Birthday."

"Happy Birthday, right. Happy Birthday,-"

"Maddy. Happy Birthday, Maddy, sorry." 

"Maddie," he said. "Is that with an *-ie* ending?"

"Oh, no, it's a *y* actually."

"Got it, not a problem."

The young woman watched him administer the (red frosting) cursive letters and then tie a red ribbon around the white cardboard box.

"Thank you," she said. "That's perfect."

"Of course." 

The young woman paid and left. Although he had every reason to think of Maddie, Freddie was left thinking more so of Summer. 

[insert more]