---
title: "From Eden"
author: "Elizabeth Kolling"
date: "2025-08-11T05:38:00"
description: " "
---

Dear —, 

Parting the lift today, I noticed the wrist of a young woman (blonde, mid-twenties, holding a broken-down box). It was the gold ball that caught my eye, and immediately I recognized it for what it was. 

As she turned right in the direction of the refuse room, I turned left towards the lobby bouquet. My head told me to keep going straight through the revolving door, but my heart told me to turn around. So, I did. 

“Hey,” I said, turning her around.

"Hi..."

“Is that a Cape Cod bracelet?”

“Uh,” she said, looking down at it. “Yeah, it is.”

“I just noticed it back there.”

“Oh, haha.”

“My mom’s from the Cape, so I go most summers (not vacationing, visiting family).”

“Oh, cool.”
 
“Is it from Eden?”

“Honestly,” she said, looking down at it. “I don’t know.”

“Oh.”

“My aunt just got it for me for my birthday last year, so I kinda don't know much about it.”

“Oh, nice.”

“My parents just bought a house in Chatham.”

“Very nice,” I said. "I just moved in on the 19th floor."

"I'm on 22."

“Cool, well, it’s nice to meet you.”

“You too.”

Sometimes, something in common isn't enough for a long-term connection. Perhaps each of us was a bit guarded, a bit closed off, thinking the other stranger. We stopped short of exchanging information and went on our way.   

This reminded me: a few years ago (2022, me thinks) on the downtown One, I spotted one in the wild. Silver band, gold ball. I asked the young woman about it, introduced myself, and got off on the next stop. Eden Hand Arts in Dennis is the jewelry shop of the original (O.G.) Dennis Bracelet (now known more generally as the Cape Cod Bracelet). The founding metalsmith (John Carey) and his wife (Eve, who was a potter) started the shop in the late 1960s, when my mom would've been just learning to walk a few towns over, and sometimes we feel the need to extend the interaction or extrapolate it to another time, another place. The want of connection creates this obsession with conservation—clinging to the same feeling, the magic of meeting a stranger, and recycling the social context. I try to find peace in what is, fleeting in the now, instead of what may be, knowing that sometimes mutual recognition just once is enough to feed your faith in people. People think Chatham is the nicest place on the Cape in the same way that people go out of their way to place themselves in Sonoma proper (the town). It has a fine downtown, and rich history. But honestly, Sebastopol is where it's at (close to the Redwoods and Pacific) and those in the know, know that the Bay side is better. Besides, Ocean side is shark-infested.

I will probably never see her again, but I don't mind it. Catch and release, I caught a fish my first time casting out. In retrospect, the cod had some growing to do (it was too small, below regulation (hardly 23 inches)), and I should've thrown it back instead of killing it.


Love, 

Elizabeth Kolling
