---
title: "Church of the Heavenly Rest"
author: "Elizabeth Kolling"
date: "2025-07-11T22:53:00"
description: " "
---

Dear —, 

There are a few things I’d stand a line for: a little Faith after the week we’ve been having, I think. And what would Ishmael do? 

I almost didn’t do it, but I did. I walked through Central Park and took a breath and rest on a bench that looked northwest towards a hill. Fathers and sons were playing frisbee on the flat part, before the slope. Someone lay on a rock (Manhattan (mica) schist).

“I can’t stand it,” we once said. “The system is so broken.”

We were saying it again, and after a bit I took my earphones out; I stood up to start walking again. I passed the MET. I passed Neue, where there was a line wrapped as usual around the corner, and I wondered whether the Gallerie had moved its first free Friday of the month to the second week given that last Friday was the Fourth. July’s already going by fast, and I passed the stark white (the colossal Utahraptor-esque Guggenheim, that is). I think I’m numb to it. East 90th Street was just ahead, and I looked across to catch the light.

I passed the Church of the Heavenly Rest. There was a line up the block, and a big sign that said “Candlelight.” I was curious, a few steps past it, and I figured a mysterious event at a church may help me heal something of mine so I turned around. I was wearing all black and sweating in my denim jeans and high-collared short-sleeve shirt, though no one knew why. All these people in summer dresses and shorts knew what was happening inside, and had made plans. Meanwhile, I started to realize the tickets were presale only as people started to prepare their QR codes. Perfect, and too good to be true, as it were. Still, I thought I may stand an off-chance of buying at the door so I stayed in line and inched forward with the rest. Eventually, I looked up at the arched entrance. 

*They shall come from the east and the west and from the north and from the south and shall sit down in the kingdom of God. And, behold there are last which shall be first, and there are first which shall be last.*

The nice young man said technically the 6:30 (p.m.) show was sold out but this one was on him. 

“Really?” I asked. He said yes, to walk up the stairs and ask for section C. 

I took a seat for free and proceeded to listen to a beautiful string quartet concert. 

I tried to read the other side when I exited (ended up taking a pciture to decipher later), and this sort of happenstance and opportunituy is what I love about New York City. On the way home, I stubbed my toe on a piece of uplifted concrete and now my toe hurts.

*There is one body and one Spirit, even as we are called in one hope of your calling. One Lord. One Faith. One Baptism. One God and Father of all who is above all, and through all, and in you all.* 

In terms of word choice, I would've punctuated the sentence with another word. Always, instead of all. Ah, well. Life's what happens when you're making other plans. All's well that ends well. Que sera sera. 

Love, 

Elizabeth Rose Aurora Bee Rain Kolling
