---
title: "Maximilian XV"
author: "Elizabeth Kolling"
date: "2025-08-10T09:15:00"
categories: [Maximilian]
description: " "
---


“What time of day do you think it is?”

“I don’t know, it’s hard to say.”

“I think it’s dawn.”

“Not sunset?”

“No, maybe before sunset.”

“Or, maybe just after sunset.”

“Dusk, maybe.”

“Do you think it matters?”

“I mean—”

“I feel like dusk is the same as dawn, and same with sunrise, sunset.”

“I think they’re incredibly different.”

“Okay, how?”

“Well,” said Sara. “You know, scientifically, obviously, the earth’s rotation and all that, and then symbolically, you know, one represents an ending…the sun rising, you know, is the beginning.”

“Sara, I’ve never heard you argue something poorly.”

“Okay, okay, now.”

“I mean, I guess it depends where this pond is. Is the exposure towards the northeast  or the southwest.”

“Where even is this garden? Italy? It looks like Italy to me.”

“Well, it is Monet, so I’d say somewhere French.”

“Yeah, you’re right.”

“I, Maximilian, am right in your eyes? Wow.”

“A personal record, I know.”

“Do you—”

“What about this one?”

“The Van Gogh?”

“I like it better than the Water Lilies.”

“Really? Why?”

“I mean, I like Monet, I do, how his brushstrokes wash over you, but the texture here is like—”
 
“The texture of life”

“I was going to say tortured. He can make something that is become its opposite.”

"Do you think opposites attract?"

"Keeping on with the lame questions."