---
title: "Madison VI"
author: "Elizabeth Kolling"
date: "2025-11-16T08:04:00"
categories: [Madison]
description: " "
---


[insert more]

"You buy me flowers, and I watch them die."

"Freddie," she said. "What are you saying?"

"I'm saying...you haven't been here. You just leave. Like it's nothing. And when you *are* here, you're never *here*."

"What do you want me to do?"

"You've been gone all fall and summer, since we moved in together." 

"What do you want from me? You dragged me back to a city I had no intention of returning to." 

"You made the choice."

"And I've been choosing to work on my music."

"You have to go to Husdon every week in order to do music? Do you know what that does to our relationship?"

"The city doesn't inspire me, Freddie. Upstate does."

"If you're not inspired here, I think you should move there."

"I think I will. I think I'm done."

"You're done? Done with the city, or done with us?"

"Us, I think. I think this isn't working. It hasn't been working for a while. I think you should find another place." 

"Okay." 

Freddie turned towards the bedroom and took a breath in front of the closet. He pulled his clothes off the hangers and folded with precision. He packed one suitcase (all of his possession fit, with room for more, into just one). He wheeled it out into the living room, where Maddie was sitting in silence on the couch, staring ahead at the black screen of the tv. He looked at the front pieces that he had fallen for back at Brown. They were just kids back then. They still were, and they'd fallen out of her loose chestnut bun to frame her face, but it was the face of someone who was foreign to him now. She turned to face him.

"Are you leaving?"

"You asked me to."

"I mean, you can still sleep here. Take the couch for as long as you need."

"Thanks."

"Hey," she said. "This isn't me putting you out on the streets. I still love you."

"Thank you." 

"I'm sorry."

We tried." 

"Yeah." 

Maddie got up from the couch and turned the corner towards the bathroom, with a lingering glance and an intuitive step closer. It only felt natural to hug her after everything they'd been through together, but he figured she wouldn't want that now. She wanted exactly that, though she'd never tell him. She continued past him.  

[insert more]

She washed her face and flossed in the mirror. Brushed her teeth and sat down in the shower, holding her shins together with her one free forearm. She couldn't see her reflection afterwards. The steam had turned the shower into a sauna. She wiped off the condensation, but still it turned cloudy again. 

[insert more]