---
title: "Sara IV"
author: "Elizabeth Kolling"
date: "2025-07-19T11:14:00"
categories: 
description: " "
---


After William would be Gold Street, she'd later learn. 

“What isn’t beautiful about her?”

“Her lips are small.”

“Mmm.”

“Her nose is too narrow, and you can tell there’s a curvature to it.”

“You mean it’s not a flat bridge?”  

“I don’t know much about noses,” Max said. “Is that what it’s called?”

“My mom had her nose done,” said Sara, still facing the woman in the painting. “She doesn’t know I know.”

“How do you know?”

“I just do."

“That’s not very convincing.”

“I have a good sense of plastic surgery.” 

“Why’s that?” 

“I don’t know. It never looks right.” 

“So something’s just off about your mom?”

“I guess. She’d say the opposite.” 

“What do you mean?”

“She thinks my dad’s having an affair.”

“Oh, I’m sorry.”

“What for?”

“Your dad having an affair, that’s too bad.”

“He’s not though.”

“Oh.”

“I know he’s not.” 

“So why don’t you tell her?”

“My mom? She wouldn’t believe me. She’s someone who has to find out for herself. So, it’s just a matter of time that her investigation draws no conclusion.”

“Sara, that’s kind of wack.”

“I don’t know.  I try to stay out of the drama.”

“Yeah,” Max said (acutely aware that Sara has been the one to bring just that into his own life as of late).

“So what else about her? 

“Who?”

“Her,” Sara said, raising her chin to the woman in the painting. Max wasn’t looking at her. He was looking at Sara, and he didn’t realize it but his toes had even drifted from the painting and towards Sara. He remembered what he’d read about how desire is subconscious expressed through the positioning of our feet. It was a mistake, so Max quickly turned his ankle towards her instead (Madame Frederic Breyer, ca. 1858).

“The length of her face is too long. She has a short jaw and her forehead is like—” 

“A man’s,” said Sara. 

“She has nice eyes." 

“Big, round?” 

“Blue,” Max blurted out, but Sara didn't realize that the color applied to her too, he continued. 

“Her hair is thin. Her hair line is receding.”  
                                                                                                            
“She has an Adam’s Apple.” 

“Only men have those, right?”

“Yeah, and there at center, the dip is really severe where her collar bones meet.”

Sara brought her thumb up to her own and pressed down, not sure what hers meant.

“Is that unattractive?”

“I think it means she’s unhealthy.”

“How?”

“I think it’s called the jugular notch,” Max said. 

"That's a terrible name."

“I think it sticks out, or gets more pronounced when you lose weight.” 

Sara traced his neck down with her big, round eyes and noticed how his was also pretty pronounced.

“Do you want to get some food after?”

“Maybe,” Max said, not really interested.

“There’s always extra left over, and it's super tasty.” 

“I do want to find this painting.” 

“Right,” Sara said. “Do you want to keep looking?”

“Yeah," he said, still looking at the dark canvas. "You can’t see half her face.” 

“She’s a bit mystifying.”

“Maybe that’s her appeal,” Max said. “Maybe that’s why Courbet wanted to paint her.”  

“I think he was paid to paint her, which is why he wanted to paint her, and he painted half of her into a sad, dark obscurity.” 

“See her hands?”

“You can tell she’s uncomfortable.” 

“She probably doesn’t think she’s a worthy subject.” 

“She’s hiding behind her forefinger but her thumb is the brave one,” Max said. 

“If you couldn’t have one finger, which one would it be?”

“Pinky,” he said. “You?”

“I think the one next to that one.”

“Your ring finger?” 

“Yeah, I guess the left hand would make sense,” she said. “You’re left handed.”

“Yeah.” 

“I’ve noticed.” 

“Okay, stalker.”

“That’s not what that means. It just means I’m attentive to detail.” 

“It means I’m smarter than you.”

“I don’t think so.” 

“I think it means you’re always right.” 

“You’re funny, also on to something.”