---
title: "Levi XIII"
author: "Elizabeth Kolling"
date: "2025-08-28T16:58:00"
categories: [Levi]
description: " "
---


Somewhere in Angeles Forest, there’s a road that leads to nowhere now. A creek runs through it, technically beside it. Even in the torrid heat of late August, water is rushing and broken glass is as equally a part of the terrain as the tears of those lonely souls who drive away from there afterwards, drunk. There was a crash up ahead, and Levi was driving Samantha back home after auditions.

“How did it go?”

“Hmm?”

“The monologue you were telling me about on Tuesday.”

“Oh, right, I think I blacked out a bit,” she said. “That happens with me. It’s funny, I honestly have no idea what I do or sound like or look like when I’m up there, my face probably looks...any way, we’ll see.”

“Like this?”

Levi turned to face her on a stretch on open road (no cars ahead, none behind), and made an ugly face at her.

“Beautiful,” she said. “I hope that’s how I look.”

“Trust me,” he said, without finishing the thought.

“Trust you what?”

“Nothing, never mind, haha.”

“So, Ethan said you road-tripped down to SoCal.”

“Yeah.”

“To see some saffron, he said?”

“Close, haha, but Sagebrush.” 

“Right, I must’ve gotten it mixed up.”

“Yeah, he was supposed to join me.”

“Who?”

“Ethan.”

“Oh, yeah, sorry about that.”

“It’s not your fault,” he said. “He ditched me for his mom.”

“Yeah, I get it.”

“Can I tell you something?" 

"Yeah, what is it?"

"I don’t think Laura likes me.”

“What, no, why would you think that?”

“I don’t know, it’s just this feeling I have, like her energy shifts into something dark, it's like dark energy, whenever I’m around her, and I feel like it’s because of me.”

“That's weird...and it’s not you,” he said. “I’m sure she loves you. Who wouldn’t—”

“Love? That's a strong word. I don’t know about love.”

“A strong liking towards you, how about.”

“In any case, can you not mention it to Ethan? Sorry, I shouldn't have said anything. He really loves his mom. As he should."  

"I won't say anything."

"Thanks, so, back to the sagebrush. Tell me more. You went alone in the end?”

“Yeah, I mean, I think it was for the best, because I had a good solo.”

“Was it—”

“Transcendental? Yes.”

“Nice,” she said. “So, why sagebrush?” 

“It’s sort of a long story.”

“Good thing we’re in a bottleneck,” said Samantha. 

(Traffic as far as they eye can see)

“Yeah, traffic’s up the wazoo.”

“Well, I’d love to hear the story, however long.”

“Okay, so, as the story goes, my mom never liked perfume.”

“Same.”

“You know, the kind that comes in a fancy bottle.”

“Mmm.”

“And, so, instead of perfume, she’d use essential—”

“Essential oils?”

“Yeah, hah.” 

Samantha stuck out her left wrist to him.

“Smell (my wrist).”

“Rose?”

“Lavender.”

“It smells nice.”

“Thanks,” she said, blushing a bit. “But any way, that’s what I use too, instead of perfume.”

(Levi already knew this about her, but he couldn’t let her know this).

“One of my first memories of my mom was her dabbing her wrists with it, and well, it was sagebrush essential oil.”

“Levi, that’s—”

“And after she…uh…growing up I’d have this recurring dream where I’m walking through a field of sagebrush, at sunrise, and there’s this super bright light…the sky is pink and orange and purple and blue, and I guess I just wanted to actually experience that.”

“Levi,” she said. “That’s really sweet. What was it like, the sagebrush?”

“Honestly,” he said. “After all these years of dreaming it, it was a letdown.”

“I’m sorry.”

“But I had low expectations, sort of…I tried to.”

He didn’t expect there to be anything out of the ordinary there, water in the desert, for instance. 

“So what exceeded your expectations?”

“There was a man walking a dog with a long, uncut coat and his shirt off. He had these great abs. Like, iron-clad abs.”

“Nice.”

Hi, he said to him. Have a good one is what Levi had said and walked on, and on a piece of rusted metal, someone had graffitied the words that were before him: loner, ale, rip drift, the letter S, like the one he used to write about the margins, or on the inside covers of those Mead composition books. The glass was brown but also amber in the light, like (mead) fermented honey, sometimes green, and a crushed Modelo took cover under an agave, which reminded him of an idea he once had. The tall stalks looked like asparagus and reminded him of the Yucca that grew above Malta’s blue lagoon. The Maltese called it Bejn il-Kmiemen, between the Cominos. 

“What does Cominos mean?”

“I think it means the island where cumin grows.” 

“Cumin, like the spice?”

“Yeah, have you ever been?”

“To Cumin island?”

“I’ve never been outside of California,” said Samantha.

Beyond the old asphalt, he saw two pine trees on a low peak, and it was no one’s fault. The one was a snag while the other was alive and thriving. He went the way back, same as he came, stepping on the rocks that looked nice for stepping on Then, he heard the rustle of the low-lying vegetation. He turned his head and saw the flash of a cat with a long bushy tall. He thought it was weird, that maybe it wasn’t a cat.

“Look, a fox!”

Levi looked to see where her pointer finger was pointing and turned onto her street (where the fox had just fled from), and the wild animal that had gotten away was a coyote, on second thought, and it reminded him of a recurring dream he used to have when he was little; mountain lions were chasing him up and down the hill that led to an open pasture and further still to a boulder that overlooked the Pacific. The mountain lions (good climbers as they were) would follow him up to the very top and hiss at him as he'd stare them down. He’d turn around to face the peaceful ocean. 

“I’d take one step forward, but then look back over my shoulder before forcing a free fall.”

“You’d jump?”

“I’d be ready to jump, and I’d almost jump every time, except, then, a Monarch would flutter by, over my head and towards the mountain lions who I’d see were also watching. As the butterfly flew over them, they’d all of a sudden turn into bucks.”

“Like dollar bills or male deer?”
“Haha, deer. To this day, I tense up when I see a…male deer.”

“I hear it’s good luck if you see a buck,” she said. “Either that or your family is cursed for five generations.”

“Then I’ll think good thoughts for, I don’t know, the next 40 after me.”

[Insert more]

Samantha got home, said hi to her dad who had made her chicken mole tamales. She asked him about his day and then took a cold shower. She got into bed shivering and read through the lines again for the part of Nina, who she wanted to be badly. Then, she went on her phone, opened her messages, and all she saw was blue. Blue, after blue text to him, and nothing in response. He was busy, enjoying time with his mom and grandpa. She almost didn’t double text, but she did. 

“Hey,” she said, adding a colon and closing parenthesis so he might think her happy. “Hope you’re having a nice time the city. See you tomorrow! Sweet dreams, I love you.”  

Samantha was fast asleep by the time Ethan texted her thank you, how was rehearsal. In the morning, she turned herself over and reached for her phone. With his name, on her screen, her heart beat a bit faster, which didn’t bode well for what was to come. 

“It went well!” She texted back, thinking of leaving it at just that until the desire for truth got the best of her. “It was actually just auditions this week. I’ll find out if I’m Nina on Monday.”

“Fingers crossed,” Ethan texted back. 

The weekend would feel like a lifetime of waiting for her, and for him too. Levi really wanted Samantha to get the part. For one, he loved her (though he didn’t know it yet). Two, that would mean she’d need a ride home on Tuesdays and Thursdays at 8:30 pm, which is when her play practice ended, same as his Model UN club (whereas Ethan’s soccer practice ended at six every day). He gave her rides home as a favor, and they all thought he was doing a nice thing (until things got complicated). 