---
title: "Ethan XVI"
author: "Elizabeth Kolling"
date: "2025-07-21T07:38:00"
categories: 
description: " "
---


“Do you want to go first?”

“I dost,” said Levi. "But I dost not."

“Aye, ye dost not?”

“Aye, aye, captain, howbeit...” 

“Is that where it came from, I mean, who the pirates got it from? From the Quakers? Seriously, so what’s up with all this Shakespearean language?”

“I’ve to say they dost defy every preconceived notion I once had of what it means to be a seaman.” 

“They’re sophisticated seamen. Talk so proper.” 

“It’s like these co-captains are co-conspirators.” 

“Yeah, I don’t trust them.” 

“That’s what an education will do to you.” 

“What?”

“Cultivate a distrust, or it’ll bring out the “stately dramatic” in thee and make thou entirely unintelligible.” 

“Huh? Don’t you mean intelligible?”

“No, I mean what I said.”

“But that’s the opposite of what you were saying, right. These co-captains are educated and therefore highly intelligible.”

“I mean unintelligible in the philosophical sense, intelligible only to those who are also educated. They're unable to speak frankly. It's just flowers.”

“I’m confused. What do you have against Shakespeare?” 

“What? Nothing. I think we’ve gone off track.”

“No, I mean, it’s fine, just what’s the philosophical definition of unintelligible again?”

“I don’t know if it’s an official term, but I’m thinking about it as the opposite of intelligible,” said Levi. “So, being able to be understood by the senses instead of the intellect.” 

“So this implies that the person with the understanding has a good sense rather than intellect?”

“I guess.”

“So, is Ishmael not educated?”

“No, I mean I think he is.” 

“He seems like he’s able to understand them. He seems like he has a good sense of the people he meets.”

“He understands that they are phonies, or at least hypocrites.”

“What do you mean?”

“Well, there’s this contradiction, where is it, doesn’t he talk about how they are civility sponges (soaking up Scripture) while meanwhile some of the most violent whalers out there, let’s see, here, he says, “there are…men, who, named with Scripture names…and…naturally imbibing the stately dramatic thee and thou…still…strangely blend with these outgrown peculiarities, a thousand bold dashes of character, not unworthy a Scandinavian sea-king, or a poetical Pagan Roman.” 

“Okay,” said Ethan. “So what’s he saying?” 

“I think he’s saying that every religiously educated man has the capacity or even the inclination to do violence. They can be simultaneously elegant speakers and vengeful fighters with blood on their hands.”

“Where does their anger come from?” 

“Inheritance. The Viking Age, I guess.” 

“And the Romans.”

“The Greeks were all peace compared to them.”