---
title: "Madison V"
author: "Elizabeth Kolling"
date: "2025-10-25T11:21:00"
categories: [Madison]
description: " "
---



Friday meant dinner (on the fly before sound check) and a show. 

All week Maddie had looked forward to the new set list [insert more] followed by bar hopping with the band, shooting the breeze about what had gone right, what had gone wrong, and all the little fires that the audience had hopefully not noticed. There they were, the five of them at the *Fly Lantern* in Bushwick, betting on the kinds of women and men that Ben would attract and how many strange numbers he’d get before the night ended. Freddie was out of his element, but he said five when their undivided attention and high expectations came around to him. 

“Freddie says five,” said Maddie. 

“Do any new texts from unsaved numbers in my phone count?” 

“It was shitty what you did to Katy.” 

“What! I didn’t do anything to Katy.”

“She told me.” 

“What,” said Ben leaning towards her. “What’d she tell you?”

“You never texted her back.” 

“Come on, cry baby.”

“Wah-wah, what’s that I see? Oh, it’s just a breeze. Ben ghosting.”

“Ha-ha. Tell your friend my phone died, or I died.” 

“You are such an ass.” 

“I’ll invite her to the next show. Personally. With a paragraph.”

“This is the last time I’m introducing you to a friend of mine.”

“You just met this girl.” 

“Yeah, so what.”

“You should have higher standards when it comes to friendship.”

“Okay, Mr. He Who Can Do No Wrong.”

[insert more]

Freddie thought about the moment at the bar as he held Maddie on the way home (which was the J train over the East River). He thought she looked drunk and disturbed, and she was.

“Hey,” he said as he held her waist. “What’s wrong?”

“Nothing,” she said.

“It doesn’t look like nothing.”

“It’s just Ben, back there.” 

“Oh.” 

“He makes me so mad sometimes, and I’m not a mad person.”

“I see.”

“Wait, what do I look like?”

“Huh?”

“You said it doesn’t look like nothing, so now I’m self-conscious about what I look like.”

Maddie leaned to the right to look over Freddie’s shoulder and tried to get a clear image of her reflection in the dirty window. 

“Like the most beautiful woman in the world.”

“Okay,” she said. “*Your* world, maybe.”

“I’ll settle for my world.”

Sometimes Maddie felt like her world wasn’t hers, and she didn’t believe the words coming out of his mouth. Freddie had a tendency to wear his emotions like a book one reads, openly, and his eyes told her he was telling her only half the truth. 

“I look tired,” she said to quell the din of her thoughts and kill the silence.

“Do you feel tired?”

“After three espresso martinis and two vodka shots,” she said. “Hardly.”

“You make it look easy.”

“Yeah, no, no reading before bed tonight. Just sleep, please?”

“Sleep sounds great.” 

[insert more]

"Is this our stop?"

"Essex. We transfer to the F."

"Mmm, okay." 

[insert more]

It was early Saturday morning by the time they got back.

[insert more]