---
title: "Levi IV"
author: "Elizabeth Kolling"
date: "2025-06-30"
categories: 
description: " "
---


“So, what’s the deal with New Bedford?”

“To me, it seemed like, I don’t know, New Bedford represents a rite of passage.”

“Mmm.”

“It’s not as sexy a place,” said Levi. “But Nantucket…Nantucket is ‘fine’ as wine, ‘boisterous.’ It represents history, legacy, the industry of antiquity, which must be studied, but New Bedford is new, and there’s something regrettable but also unquestionable about that so I think he has no choice but to document it or bring that into the fold.”

“I guess, what it begged for me was the question of…well, what happened to Nantucket, you know?”

“Yeah.”

“Like why did whaling decline there.”

“Totally, he’s highlighting this shift in the whaling industry, out with the old, in with the new."

"Yeah, but why was that the case?”

“I have no idea,” said Levi.

"We need Samantha here to tell us some history." 

"Look pretty?"

"Dude what, no, I said tell us some history."

"Oh," said Levi, a bit embarrassed. “Maybe they fished ‘em all outta Nantucket.”

Ethan didn't laugh at the funny voice. He was still annoyed about the thing Levi had said, which was totally not cool, about his girlfriend, but he knew that Levi was hard of hearing and he knew he had a tendency to mumble so he just considered it a miscommunication and tried to brush it off. 

“We’ll come back to it.”

“Okay.”

“What else?”

“Well, nevermind.”

“What? No. Tell me.”

“I don’t know,” Ethan said. “I guess I saw some connection to your earlier theory.”

“Pray tell.”

“Okay, starting with what, the second, no what is it, the fourth paragraph, I guess, of Chapter 2.”

“Yeah?”

“So, Ishmael has spent a Saturday night, Sunday, and Sunday night in New Bedford, and only then he looks for a place to sleep, right?”

“Um…”

“So, I think he either stayed awake the whole night into Sunday, or he slept on a bench or in the streets, you know, like a drug addict, like what you were saying before.

“Um, hmm, interesting, but I’m pretty sure it’s still Saturday when he starts to look for a place to sleep,” Levid said, moving his pointer finger down the page. “Yeah, here, it says, ‘now having a night, a day, and still another night following before me in New Bedford.’ So, the ‘following before me’ meaning Sunday is still to come.”

“Oh,” he said. “I totally missed that, and I guess I read it the wrong way. I read the word ‘having’ and then I just read the rest of it as if he had already had Saturday night, then Sunday, and Sunday night again, my bad.” 

They sat in silence, flipping through pages.

"No, wait,” Ethan said. “Here, here’s why I must’ve thought it was Sunday. There’s this lines about how it’s the last day of the week, which I thought, of course, meant Sunday.”

“I thought Saturday was the last day of the week.”

“Jesus.”

“Yeah, I think so, maybe I’m wrong, I thought it had to do with Catholicism or something,” said Levi. 

“You’re Catholic, right?”

“Yeah, you?”

“Kind of.”  