---
title: "Ethan XIII"
author: "Elizabeth Kolling"
date: "2025-07-14T22:50:00"
categories: 
description: " "
---

“So, he settles his and his friend’s bill but using his friend’s money.”

“Are you trying to tell me that you went into my purse?”

“It’s a miracle, the coincidence.”

“You don’t say.”

“Right when Ethan leaves for the restroom, the check comes.”

“I’ll pay you back, dude.”

“No, it’s fine, I’m just doing a bit.”

“If you say so.”

“So, do you think debt is like Melville said a few chapters ago.”

“Which—?”

“Uh, let me find it…Oh yeah, here, Chapter 10, *A Bosom Friend*, page 65, ‘He looked like a man who had never cringed and never had a creditor.’”

“Mmm, right, so he’s basically saying you’re a bad guy if you ask for money.”

“Maybe you’re a bad guy if you succeed in asking for money…like if you actually borrow money that you can’t pay back…”

“So debt has a moral component.”

“It says something about your character, at least that’s how Melville’s using it here when Ishmael is considering Queequeg. He sees through his terrible tattoos to a ‘simple honest heart…and…a spirit that would dare a hundred devils.”

“Wow, that’s beautiful,” said Ethan. “So debt is the devil.”

“Sinners are credit card holders,” said Levi. “At a country level too, right?”

"Hmm?"

"I think the moral implication should have to do with the creditor, and whether or not the lending is predatory. Saddling poor nations with debt to make them dependent, and then exploiting them for their natural resources along the value chain while denying them true means of production, for instance."

"So, like what countries, and what commodities?"

"I don't know, Ghana, for one, and chocolate."

"Ghana?"

"Yeah," said Levi. "Cocoa beans, I mean."

"Where is that?"

"Ghana?"

"Yeah..."

"Africa, dude." 

"Right, I knew that."

"You know where the American school system fails us?"

"Science? Technology? Enginneering? Math? English?"

"Geography." 