---
title: "Richard II"
author: "Elizabeth Kolling"
date: "2025-12-14T11:20:00"
categories: [Richard]
description: " "
---

[insert more]

The bell chimed as the elder and Richard entered. Richard looked around. All the booths were taken except the one with a stack of dirty dishes and someone's half-eaten stack of French toast.

"French toast looks good." 

"I want eggs."

An older woman with blue eyes and green eyeshadow noticed them. 

"Hi, fellas." 

The elder looked at Richard who said nothing.

"Take a seat anywhere you see," she said, taking another look at the place. "Counter's ready for you now, Booth will be a few minutes." 

Richard looked at the elder, and started to speak.

"A booth'll be good."

"Okay, if you want to wait outside, we'll have that ready for you in no time."

It was cold outside compared to inside, but the elder didn't mind waiting on the street corner for five minutes. Besides, where even was he? The elder looked around as Richard peeled a cigarette from his shirt pocket and lit the thing. He took a drag and handed it to the old man. The old man took a long drag and handed it back to 

"You tryin' to kill me, boy, but I'll tell you, it ain't gonna be because of no Sweet Caporal."

[insert more]

Richard ordered pancakes in the end, and two fried eggs, over-easy, with two sausage links. 

The elder read the New Year's Day paper. 

"Twenty-three million," he said. "I'll be damned."

"What's that?"

"All for an aqueduct." 

[insert more]

