---
title: "Ethan XXI"
author: "Elizabeth Kolling"
date: "2025-09-18T22:03:00"
categories: [Chapter 18]
description: " "
---


“We missed the mark.”

“Huh, what mark?”

“His Mark.”

“Whose mark?”

“No, we skipped a chapter.”

“What does that have to do with a mark?”

“Ugh, nevermind, just turn to page 99, will you?”

“I’m just messing with you,” said Ethan. “I knew we skipped to the Prophet.” 

“You disturb me.”

“I know, you’re very disturbed by me. Do you want to talk about it?”

“I would love to talk about His Mark, if I’m being honest.”

“Be honest.”

“So, Captain Bildad accuses Queequeg of not being Christian.”

“Ah, yes, on their way to the ship?”

“Yeah, they’re walking from the hotel or whatever, about to board the ship, and it’s Captain Peleg who tells Ishmael that no cannibal is allowed on the ship.”

“I hate these captains.”

“They are insecure cowards.”

“Seriously, Bildad has to hide behind Peleg in order to demand anything of Queequeg.”

“He calls him the *son of darkness*.”

[insert more]