---
title: "James III"
author: "Elizabeth Kolling"
date: "2025-09-04T22:13:00"
categories: [James]
description: " "
---

"What's wrong?"

It was Monday, but it wasn't to Catherine. She was still stuck thinking about—

“Sunday, I’ve been thinking about what's wrong with Sunday.”

“As in this Sunday, or yesterday?”

“No, yes, yesterday,” she said. "Last night, actually." 

"Okay, hit me."

"It's a delicate thing, and I'm still thinking."

James took his shoes off in the breezeway. Catherine made her way off the couch, towards the kitchen island (the fridge was always his first stop on Mondays after work went late).

“Hello,” he said, leaning in with a kiss on her cheek. “How are you, my love. Have you had dinner?”

“I don’t know, James.”

“Oh, I know,” he said. “Quesadilla or grilled cheese?’

“No, I’m serious, I don’t know.”

“I know, two very different directions.” 

“No, I’m trying to talk to you about something else.”

“Oh.”

“It’s Max.” 

“Maximilian. I like that kid. I’d approve.”

“James, we’re not setting him up with Sara. Honestly, I’m worried about him. He didn’t eat anything.”

“What do you mean? Also, was that a yes or no to dinner for you? Hmm. I thought we had a block of Dubliner in here somewhere.”

“I’m not hungry.” 

“So now you’re not eating.”

“No, I had dinner. I would like you to stop for a second, and look at me when I’m talking to you.”

“You’re right. I’m sorry.”

“Max, on Sunday. He didn’t eat.” 

“Really?”

“He touched maybe the peas, piece by piece.”

“Well…”

“And don’t tell me it’s my cooking,” said Catherine. “Those were Grandma Beverly’s stuffed butternuts. What?” 

“Nothing.”

“Come on, James, this is serious and that’s a family recipe. No one, not even I, can mess it up.”

“Catie, baby, I’m listening, but you’re losing me.”

“Okay, here it is. I’m just going to say it. We invite him over for dinner, and I think that the boy is anorexic.”

James started laughing, because frankly the claim was ridiculous (Catherine had a tendency to overthink until there was an issue, and she liked solving problems that didn’t exist for people in the name of altruism).

“Catherine, he’s just growing into himself. He’ll fill out.”

“I thought that, I really did, but now I think it’s something more wretched.” 

“Catherine, I think we should be worrying about the young women in our lives, maybe Maddie or I don’t know, our own daughter.”

“You’re so sexist. Sara’s fine. He, on the other hand, didn’t even touch Great Aunt Rosaline’s mashed potatoes.”

“Maybe it’s your cooking.” 

“What! You told me you loved my cooking.”

“I tell you a lot of things that aren’t true, because I love you.” 