---
title: "Laura V"
author: "Elizabeth Kolling"
date: "2025-07-27T11:45:00"
categories: 
description: " "
---


Catherine received the morning, turned towards the wall. She saw as usual the two of them in the painting and then remembered her husband already lying there next to her. She rolled over with an expectant smile in her eyes to find James (as usual) not in bed beside her. She thought maybe things would be different this Sunday, but they were the same as she braced the silk sheets with her outstretched palms alone and pushed herself up against the headboard. With a swift adjusting of his or her silk-cased pillows, she settled into the perfect position and was relieved to see the tall glass of iced coffee resting there on the table. There was also a little vase with a singular baby pink rose next to her plugged-in phone, so maybe he did still care.

Maybe he’d risen earlier with a kiss on her shoulder and mixed in a bit of cream and sugar as usual in the kitchen. Maybe he’d brought the glass to the bedside table, where she’d left her phone inches from the outlet and got it charging for her. Maybe he’d gone on a run around the reservoir, as he’d been wanting to do since before the start of the heat wave. Maybe he hadn’t taken his cigar to the same bench as before, but she didn’t want to think about what maybe was. Maybe he'd gotten dressed in running gear to give the appearance of having gone on a run. She was tired of not knowing, not having answers. La Méridienne was an alternate name of the painting, she knew, a gift from Max, and James had a Sunday and Tuesday and Thursday and Saturday tradition (every other day save weekends).

“A reinterpretation of Van Gogh’s, which he reinterpretated after Millet's.”

“Thank you, Max, it’s very nice. I’ll ask Sara and James where we’d like to put it.”

James arose that Sunday as usual. He made his wife coffee the way she liked it (extra sweet, extra ice cold), and then walked a block east to Museum Mile and south past Engineers’ Gate. He picked a bench in front of Guggenheim and sat there a while. He puffed his cigar (essentially), considering the water damage as well as Le Corbusier.  

“It’s tradition," James would say. 

“It’s not some kind of homemade casserole that’s been passed down, James.” 

“It’s time for me.”

“It hurts me that you don’t care that you’re killing yourself.”

“That’s a little dramatic, Catherine.”

“You said you’d quit for me.”

“I will, come fall, but it’s summer.”

Catherine sat in bed, sipping her iced coffee, scrolling Facebook. She saw that her childhood best friend had gone camping, and Ethan was growing up fast. Laura Chase didn’t take it personally that Catherine hadn’t posted on her timeline for her birthday. She loved to post the highlight reel of her life online, and that was fine, but she knew Catherine only kept her profile out of convention and was rarely on the thing. Besides, Catherine had tried to call and did leave a really sweet voicemail. There was no service then where they were, so she only days later received the wishes. 