---
title: "Ari"
author: "Elizabeth Kolling"
date: "2025-06-28"
categories: [Ari]
description: " "
---

Ari was affluent, a sixth generation New Yorker and one thirty-second (1/32) Florentine living on West End Avenue, but no stranger turned acquaintance turned close friend, say, would know it unless he said something. It came somewhat as a surprise to Max, but he wasn’t affected either way. He didn’t really care about what a person’s deceased ancestors had done. He was more concerned with what Ari was doing with his life, whether he was squandering the head start or not.

His great-great-great-great grandfather (he thinks) was born in 1801 and immigrated to the United States in 1818, before it was very in vogue back then. This meant that Ari could, all these years later, escape any sense of discomfort (the humid months) with the slightest will. Sometime, he’d lean into it and maybe defer to some Hamptons seaside, but more often than not he’d spend summers in Fiesole, Italy, where the family villa still was standing. The weather was better. It'd get hot but not too hot during the day, and then cool off at night, and the sun parlor was unequivocally his favorite room (if he had to choose) to watch the sunset. The summer before freshman year of college, Ari invited Max to see it (and *The Birth of Venus*) for himself. It faced south, towards Firenze, but Max was more interested in seeing *Primavera.*  

Il conservatorio, as his Italian tutor, Cate (Caterina) reminded him. The sun parlor looked out at the garden. There were echinacea and chrysanthemum and lilies of the valley, for flowers, and there were tall, tear-shaped cypresses along with fruit trees—pear, mandarin, tangerine, clementine, cara cara, kumquat, loquat, (mostly citrus, and not the season). Also, bushes; yellow raspberries, and blackberries that had to be religiously cut back to avoid overgrowth. 