---
title: "Levi XVII"
author: "Elizabeth Kolling"
date: "2025-11-20T11:16:00"
categories: [Levi]
description: " "
---

Dear Mom, 

I think you’d like this book I’m reading. It’s about a young man who becomes a teacher. Well, he becomes something else after that. And more. I swear. I won’t give away the ending, but first he becomes a teacher. Reading about him becoming a teacher reminded me of you, of course, which is one of the reasons I wrote you the other day. It’s not unusual, you know. For you to suddenly be on my mind. All I can think ~~about~~ of. Something simple does it. My own mistaken grammar. Balsamic on a carrot round, or broken dishes in the sink. I look up to see the Cross on the crown of the church at town center, or it’s the weather. A dandelion grows out of a crack in the sidewalk. You never did do a dish, Dad says. You viewed your refusal of dishwashing as an act of feminist protest, and he loved you for it. His hands are still raisins these day, and he still loves you, you know. But he’s lonely. I tell him he should go out on a date with someone. Start dating. He doesn’t say it with words, but his (almond) eyes tell me. True love is bittersweet. The right shoe doesn’t fit. On Sundays we still set a place at the table for you, since you loved Sundays. That reminds me. Catholicism. *He* talks about converting, and I have all of these questions I never got to hear the answers to. At least, from you. I never got to ask you if you had always wanted to be an English teacher. You know, since you were a little girl or if some other dream came before books. I’ve asked Dad. And he says you first wanted to be a sailor. I didn’t believe him the first time he told me. I thought he was joking. The second time he said it, I started to wonder. My mom, a sailor? I started to tell the other kids at school about my mother, the sailor. I knew what I was doing. Bragging. I felt bad-ass on your behalf, because there aren't many women sailors. The writers never wrote about them, after all. Any way, it’s a lost art. I look out at the Bay, and it’s full of white boats with motors backing them. The men and women are reposed, texting on the phones that have changed the whole scape of this city I spent summers in because of you. They stay where there’s service. *He* talks about the *what if*, and the misery of education. Not the state of being educated. The misery, I guess, that comes with aspiring, the process of getting educated. He says he had “apparently passed the test.” It was the word *apparently* that stopped me. The sentence that made me think about something other than what I was reading, so I underlined it. And I’ve thought about it. I think what he’s alluding to is the idea that the test taker never feels ~~himself~~ herself passing. The feeling of failure, of always failing, is pervasive. That’s where the misery lies, because even if ~~he~~ she passes the test in the end, she still sits with the feeling. She is there in the seat, feeling like a failure, and she can’t forget what she feels. 

[insert more]

Love,

Your Levi
