---
title: "Sara V"
author: "Elizabeth Kolling"
date: "2025-09-16T11:14:00"
categories: 
description: " "
---


“This guy looks like Mr. P.”

“Hmm?”

All the walking in circles through these squares was exhausting. The sat on the bench to take a rest. Sara started doing circles with her neck, as if sore, and Max was trying his best not to look at her. He tried not to imagine what it would be like to work through those knots of hers. So, he looked straight ahead even though he didn't particularly like anything of religious substance.

"Do you think this is how Mr. P is when he’s at a party?"

"Honestly, I see why Manet was so insecure."

"What, about Monet?"

"He’s not very good."

"He could be better."

"Just look at dead Christ here. He doesn’t look dead."

"He looks—"

"Out of it."

"High as a kite."

"And look at his right hand. It looks like a pile of—"

"Shit, you know what?"

"What."

"He kind of looks like Mr. P, doesn’t he?"

"That’s what I just said, dummy."

"Oh, I didn’t hear."

"Do you think you’ll ever hear me?"

“Will have to wait and see,” said Sara. “There’s the serpent slithering away.”

“See, he’s so messy with the scripture.”

“What do you mean?"

“I mean this is not Genesis, so why is there this snake in the corner?”

“This is John, right?”

“Uh.”

“The scene with Jesus and Magdalene and the two angels.”

“I don’t know much about the Bible, honestly.”

“Isn’t there also a snake in John?”

“I don’t know, I’ll say I don’t think so.”

“I think there is, I mean, it’s not a real snake, if I remember correctly. It’s made of gold or bronze or something and mounted on a pole.”

“Like a staff?”

“Yeah, Moses carries it around to heal people.”

“To heal people?”

“Yeah, the people who were bitten when God sent down those venomous snakes.”

“I have a bug bite on my ankle, and I keep itching it.”

“Also, what about Magdalene? She’s not even here. She’s supposed to be here weeping.”

“The angel on the left is.”

“I guess.”

“So, is this the part where Christ is supposed to come back from the dead?”

“He hath risen.”

“Looks like the one angel is trying to comfort him, the other angel has lost hope.”

[insert more]

Max looks east on the MET rooftop.

"It's an interesting shape, the top of that building."

"Yeah."

"It's like a watch tower."

"I can't imagine it."

"Cant imagine what?"

"I can't imagine living there, in one of these buildings."

"Why not?"

"Because, it's just not possible for someone like me."

"Hey," said Sara. "Would you want to come over for dinner?"

"Dinner with you and your parents?"

"Yeah."

"Yeah, thanks, that'd be nice." 

"Sunday? I'll send you the address." 