---
title: "Maximilian XIX"
author: "Elizabeth Kolling"
date: "2025-10-21T11:49:00"
categories: [Maximilian]
description: " "
---


Max sat on the Met steps after school, reading Jack London. 

A woman with a long, red silk scarf set her bag down beside him and reapplied her lipstick.

"Excuse me," he said to her. "Do you know if there’s an event going on?"

"Yes, for members and donors. I know about it because my husband was the entertainement."

"Is it over?"

"It should be starting soon," said the woman who got up to leave. 

Max stood up too before the sun set, and turned towards the entrance where there was a woman in a long black dress. She had pearls in her ears and high heels on, and she was talking to someone who he couldn’t see behind the pillar. He walked up to her.

"Excuse me," he said. "Is the event for donors?"

She stuck her nose up at him.

"It’s a private event." 

"Are members allowed?"

Catherine had arranged a card for him, and he thought it may be good for something like this. He didn't see her, among the crowd of fancy people. The woman before him just rolled her eyes and repeated her line.

"It’s a private event."

So, Max walked away with his head down. His book, open in his hands.