---
title: "Grandpa C."
author: "Elizabeth Kolling"
date: "2025-06-09"
categories: 
description: " "
---

Laura and Owen and Levi and Don loaded into a car together and drove up north each summer for camping, as a family. 

They weren’t family, but they were as close to it as Grandpa C. was suave in his Capper & Capper suit. He’d wear it, ivory and tweed, every other day-before-Christmas Eve, even though Laura called it her “Winter Solstice” party. Laura would throw a big party each year during the holidays and invite all of Owen’s friends and their families. There’d be charcuterie boards but in weird places, which always seemed to coincide with some home improvement that finally completed the house and that Laura was very excited to tell people about, so finding the food was somewhat of a hunt and always a source of gossip on drives home. For instance, one year, Laura put a charcuterie board out on the back deck despite the bitter cold weather they were having, as a way of leading guests to the new landscaping. It was all native species, and drought resistant. 

“I just want to do my part,” she said. “In times like these.”

This year, she put the charcuterie board upstairs in the old guest room that she’d recently converted into an art studio. She paid someone to do it, but it took months beyond the original quote and the whole thing was a nightmare. By the time winter solstice passed and the party came around, the room consisted of blank canvases despite a bunch of brushes that’d clearly been used. The paint was dry, still coating the bristles. 

“I just love it,” she said to the Townsend family who stood at the doorway, careful not to enter. “It's a dream, you know...my very own easel.”

Laura walked further into the recesses of the room and glided her palm across the stool, making her way towards the window.

“Sitting on this seat, watching the sun rise.” 

There was one painting: a four by four of the color green, centimeters thick and projecting from the canvas, with a single patch of blue left of center. She titled it, “Pubbenivasanussati,” which she translated for the Townsends as “the remembrance of former births.”   

The death of his wife is what changed the holidays for him. Grandpa C. would pack into his little Volvo and drive the eight hours or so straight from Brentwood, CA, the last nice part of Los Angeles, or the City of no more Angels, as he’d refer to Home in his old age. He’d stay for as long as it took him to re-connect with his grandson, regain feeling in his legs, or finish off the Humboldt Fog. He swore by it—cheese on a cracker, eating standing, walking as a lifestyle, and saw driving the scenic route as the only exception for sitting idle. 

