---
title: "Ethan"
author: "Elizabeth Kolling"
date: "2025-06-05"
categories: 
description: " "
---

Her son had a lot of friends from high school, to start, but he had a way of dwindling the circle down like it was a jolly rancher getting rotated about in the mouth of the girl with the long brown hair from freshman year. He was a nice guy, and the other girls liked him too, but he didn’t much mind them. He only had eyes for the one, and he was more intent on what he was reading. The guys on the soccer team called him grim or the reader or the grim reader, one after the other, on the way to games. 

“How’s it going, Grim?”

“What’s the reader reading today?” 

“Watch out the grim reader’s right behind you,” Cole would say in the seat behind him on the bus.

 It was just fun and games, a play on the grim reaper, because he always had this look on his face when he was staring down at a page, like he was depressed or something. It was a cool November in his soul, he’d say to the guys, all serious, just to freak them out, but they always knew he was messing around. The thing he hated about being on the soccer team was that it always took him away from the school day. He’d have to leave Western Philosophy early, and he always felt like he was missing the part where everything made sense. He liked Plato best, because Plato was a bit of a romantic despite what the Stoics said. 
 
 Something good did come of it, though. The one girl with the long brown hair who always sat in what seemed to be the farthest seat possible from him, turned around one day and volunteered to take notes and send them to him. She had this incredible handwriting, and her notes were extremely meticulous, not sporadic or like Pollock in front of a tawny canvas. They were complete, converging, and read like little short stories. She was definitely smarter than him, which is why he loved her. He’d had this crush on her for at least a month into the note-taking before he mustered the courage to ask her out. He asked her if she wanted to go get ice cream, and that was that. They both liked mint chip, and before his mother knew it: Ethan, which didn't mean noble or well-born or son of destiny, had a girlfriend in high school. 
 
 Laura hated that they were together. She hated the girlfriend and this was revealed first in small ways but then pretty obviously at a certain point in time, maybe halfway through junior year, so he knew it’d never amount to much. She was pretty and a free spirit, she showed him things, and sometimes didn’t wear shoes when she walked around which upset him and was the only other major tension. It was good for now, not forever, and he was fine either way. Senior year came and graduation day, walking across the stage, and he broke it off with Samantha a few weeks later before she left for college. She was going on a pre-orientation water rafting trip, and he was able to do that sort of thing—be present and apparently sincere, but critical of himself and others on the inside. He had his best kept secrets and he cared a lot about what others thought, especially his mother who had decided early on to hold a grudge, never let it go, and let it fester like her toenail fungus, which she painted with prescription Ciclopirox every morning after yoga.
 
 “I want you to experience everything in its fullness,” he had said to her. “Not in distance.” 
 
 Even in the bitter end she believed he was sweet, and maybe she looked just too good in flip flops.
	

