---
title: "Alexis II"
author: "Elizabeth Kolling"
date: "2025-09-28T21:14:00"
categories: [Alexis]
description: " "
---


Alexis awoke wanting a croissant. She stood in line for one, but when she got to the window, something demonic intervened (overcame her) and she ordered four. 

“One plain, please…and can I get an almond, actually…and one of the pistachio ones…and a *pain au choc*?”

“Will that be all?”

“Uh, yeah, thanks.” 

Alexis tapped her phone, and took a look at the baguettes behind the counter. Bread and butter before nine in the morning had sounded really good to her, in theory, but regret and shame started to sink in as she held the hoard of paper bags. She was supposed to be doing keto, except for one weekend treat. 

[insert more]

She remembered what she almost let slip her mind: she also needed to stop at the ATM before her *fall refresh* facial. She wasn’t cash-strapped, but she was in need of cash. She had a dedicated practice of stockpiling twenties in her various purses and pockets. A pocket here, a designer pocket there.  

[insert more]

She made her way to the Garment District.

[insert more]

As Alexis approached the Theatre Book Store, she saw two men who appeared to be camping out just outside in swivel chairs. They were surrounded by takeout containers, clothing, and the scent of something sour. She stopped beside them, and reached out her pinched thumb and forefinger. The first man took the money and blessed her. The second man ripped the twenty dollar bill from her hand, and it tore along Jackson’s ear lobe. 

“Bitch.”

“I’m so sorry,” she said. “Here, have this one.”

This time, she let go before he reached out.