---
title: "Ethan II"
author: "Elizabeth Kolling"
date: "2025-06-16"
categories: 
description: " "
---

Dear Dad, 

Yesterday was Father's Day, and I thought of you. So I thought I’d write you a letter of all that I remember.

When I was really young, you’d take me on hikes on Sundays. I’d wear my superman sneakers and think the S shield was my life force. I’d pick up every possible walking stick and pretend I was an old man. You told me the difference between right and wrong, the madrone and manzanita, and for so long I couldn’t see it.

We were living just outside of town then and Muir Woods was our backyard, the three of us. At age five, I learned how to ride a bike because you taught me. I was scared at first of falling off, but you called me a natural and all of a sudden I was ready for two wheels. You told me not to worry, as long as I had my helmet on and eyes open, I’d be safe. I remember one day on our walk I told you my superpower was knowing exactly what mom needs but I wish it could be flying like the ducks in front of us. We were sitting on a bench by Phoenix Lake, sharing a bag of orange slices, and you said your superpower was protecting water. I remember being confused by that. I didn’t know what you meant by it. 

Mom asked if I wanted to go on a walk to the lake with her yesterday, but I wanted to go alone so I said no and then snuck out later without telling her. I felt bad, but sometimes being around her is like a sad reminder, and I just want to talk to my father. I hate that I sometimes refer to you as father. I wish you had wanted to talk too, Dad. I wish I had asked you more questions, like *why water*, or knew what you were going through. But I understand, and I’m piecing it together even if I can't remember or don't know everything. I hope you're proud of the young man I'm becoming. I miss you. Mom misses you. We both wish you were here. 


Love,

Ethan
