---
title: "Ethan XII"
author: "Elizabeth Kolling"
date: "2025-07-13T10:42:00"
categories: 
description: " "
---


“Have you heard of paper towns?”

“Is it a band?”

“More so a phenomenon…of times past.”

“A phantom, more like.”

“Good one,” said Levi. “It had to do with map-making.”

“Map-making? Like when they’d whip out their scrolls and hold it up to the sea?”

“Definitely. I guess back in the day, when mapmaking was an actual profession, cartographers would insert fake places or streets or green spaces on their maps so that no one would try to copy them.”

“So no one would copy them?”

“It was like a trap. So, if one cartographer did all this great work and another cartographer wanted to use it to cash in themselves…basically, if the second cartographer stole the other guy’s map, the court would be able to tell because the second guy’s map would have the fake towns of the first guy’s so it’d be obvious that they stole their design or map or whatever.”

“So it was like a legal claim over their work?”

“Yeah, it was for copyright basically.” 

“That’s what I tell Mrs. S every time I turn in an essay and she comes back with corrections.”

“You tell her—”

“I tell her this misspelling or this floating comma was all to ensure my claim.” 

“You’re so full of shit.”

“It worked the first time.”

“No way, dude.”

“Yeah, you’re right.” 

“So that’s basically what I thought of with the mention that ‘true places never are,’ on maps. It implied that fake places always are on maps.”

“Nice catch,” said Ethan. “So Kokovoko is not a real place?”

“I don’t think so.”

“I’ll look it up…yeah, no, it’s not.”

“Sweet.”

“Melville kind of has a sense of humor.” 

“How so?”

“I mean he titles chapter twelve Biographical and then proceeds to give us the anti-biography of Queequeg.”

“That’s kind of an exaggeration, no?”

“I guess I’m just referring to his choice to start out with a fictional island as the basis of the origin story.”

“So then it begs the question, is Queequeg even a real person?”

“Or a figment of his imagination.”

“I have a feeling he was definitely inspired by someone real.”

“I started to feel that in the last chapter, Nightgown, like I started to feel like Melville was writing about a woman or a past lover or at least thinking of someone like that when writing it as Queequeg.” 

“There’s definitely an intimacy there.”

“It’s not sexual I don’t think.”

“And like this yearning for a wife.”

“Is Ishmael gay?”

“Could be.”

“Constantly he brings up the idea of a wife.”

“And women are notably absent from this book.”

“The only time he refers to them is when the street people of New Bedford are terrorizing them.”

“Where?”

“Uh, in the walk through New Bedford chapter. Let me see.” 

“Oh, here, wait they’re not street people,” said Levi. “It’s the Mediterranean mariners who are jostling ‘the affrighted ladies.”

“So women are only characters when they’re frightened and nervous.”

“Wait, women are in the chapel too right?”

“Oh, yeah, maybe.”

“Yeah, here, in The Sermon, with reference to the ‘shuffling of women’s shoes.”

“Right.”

“Back to Queequeg and whether he’s really a woman,” said Levi. “It’s kind of a heterocentric lens to look through.”

“Maybe, but it’s probably more likely, right?”

“What do you mean?”

“As far as statistics go?”

“Respectfully, what are you talking about?”

“There are more straight people than there are gay, right?”

“I don’t know about that, according to who?”

“I don’t know.”

“I think there are confounding variables also affecting your statistic there.” 

“Maybe.”

“It’s a spectrum right?”

“I guess.”

“But also, like, it’s a hypermasculine lens as well, right?”

“I mean—”

“Look at us,” said Levi. “We’re bed mates but we don’t want to have sex with each other.”

“Yeah, true.” 

“Some guys are so insecure and feel like they have to be a certain way.” 

“Talk a certain way.”

“Walk a certain way.”

“Cole walks on his tip-toes, and he has a girlfriend.”

“He hasn’t come into himself yet.” 

“I kind of want Ishmael to be gay.”

“You do?”

“Hell yeah,” said Ethan. “That would make Moby-Dick like so subversive for its time.” 

“Yeah.”

“It’d be a cool legacy.”

“Speaking of, are you going to apply to Stanford?”

“Why?”

“I mean—”

“Because I have legacy?”

“I mean yeah.”

“Obviosuly.” 

“Stanford’s like hard for legacies.” 

“I was talking to Cheryl the other day.” 

“Yeah? About college?”

“Yeah, and she was so fake, by the way, speaking of fake places, any way, she said ‘our school has a successful track record of Stanford acceptances.’”

“You’re gonna apply?”

“I might, haven’t decided, we’re only sophomores” said Levi. “Or about to be, any way, what she failed to also say is all of these accepted students had at least one parent with Stanford as an alma mater.”