---
title: "Guy"
author: "Elizabeth Kolling"
date: "2025-12-23T20:23:00"
categories: [Guy]
description: " "
---


Guy and Richard met on a boat in 1906. He was the eldest son of five, and they were both fleeing for their lives from the Bay. San Francisco had cracked open a thousand times over and was now on fire. The smoke plume rose against an otherwise clear day.

"What did you reach for?"

"I didn't have so much time. Saw them flames coming. How 'bout you?" 

"The first thing I saw."

"What was?"

"Sea Wolf."

"A sea wolf?"

"Some book I'd been meaning to read."

"Hmm."

"You heard'f it?"

"Never heard'a no wolf in no sea. And sure as hell woulda taken no book if it was the last thing I seen."

"A friend of mine thought I might like it." 

"Hmm. Figures." 

"Huh?"

"What's her name."

"Uh." 

"Any way, why'd she think that? What's the book about?"

"I don't know yet. But I liked the first one he wrote." 

"Who's he?"

"You haven't heard'a him?"

"I don' keep my ears open for no one."

"I can't seem to close mine."

"Listen...what's your name?"

"Richard."

"Richard, you go by Dick, Richard?"

"No, sir." 

"Well, nice to meet you," said Guy. "Though I'll say in not so nice an occasion." 

Richard watched the Marina burn as the ferry sent forth towards Sausalito. Guy's eyes were on what lay ahead: house boats.

[insert more]

What was said and unsaid when they met depended on who was telling the story. Guy told it differently (to the men interrogating them) than Richard did.

"When I met Richard, he didn't say a goddamn word. I felt bad for the kid. All stupor. And, rightfully so. I could tell he'd seen something that no man should ever. His family, you know, jus' been burned alive." 

[insert more]

(Guy thinks Richard talks pretty. Richard progressively starts to adopt Guy's vernacular as their storyline progresses.)

[insert more]
