---
title: "Ethan IV"
author: "Elizabeth Kolling"
date: "2025-06-25"
categories: [Ethan]
description: " "
---

Ethan was sprawled out on the corduroy couch (orange), sideways, staring intently at the wall. There were no fissures, only a fresh coat of paint—Pantone 399. There was sweat above his lip, where he was trying in earnest to grow a mustache, and Levi was across from him (sitting on a foot stool, leaning across the coffee table).

“I don’t know,” he said.

Levi half-heard him. He sealed the paper and slid him the rolled joint, to no reaction. Levi knew why. Sometimes he got like this, unreachable. Ethan’s eyes were already glazed over by the thought of his father.

“You don’t know what?”

“I don’t know what he was thinking,” Ethan said, turning to face him. “He could’ve just packed the orange whole.”

“What?"	

“He cut it up and he put the pieces in a plastic bag.”

“Huh?”

“He could’ve thought of the skin.”

“Ethan.”

“The skin is what held the pieces together. It was already built in.”

“I know.”

“For years. He asked if I wanted orange slices, and he handed me a plastic bag.”

“Ethan!” Levi said, finally raising his voice. “Why are you saying this?”

“I’m saying this, because you know what that is?”

“What is it? Tell me."

“Taking an orange and cutting it into pieces and putting each wet piece into a plastic bag to take on a hike when it naturally has a whole protective layer which you can peel, that’s depression.” 

“Are you sure?”

“We should’ve taken turns peeling, and split it in half and peeled each piece one at a time, together. Instead, we were creating trash. It's everything he was against. It doesn't make sense.”

“I’m sorry,” said Levi.

Ethan looked down at the table and didn't say anything for a few minutes.

“Is this mine?”

“Yeah, it’s yours.”

He put the joint between his lips and patted himself down for a lighter. It was already out, beside him on the couch.

“Hey,” Levi said. “Do you want to go on a walk? Outside? Fresh air? Change of scenery?

Ethan lit the thing and leaned back on the exhale.

“Change of scenery? Where does that come from?"

“I don’t know,” he said. “Sometimes, everyone needs a change of scenery...It’s something my mom used to say.” 

Ethan looked at him.

“Okay.”

It was 101 degrees that day, the peak of summer. Fourth of July was just around the corner, and Laura was planning to throw a party for after the parade. 
