---
title: "Three Sisters"
author: "Elizabeth Kolling"
date: "2025-09-08T22:38:00"
description: " "
---

Dear —, 


Saturday, Sunday, Monday, Dad tells me what Grandpa Walter told him: this too shall pass.

I won’t get over it. 

One day, maybe, I’ll write about it.

Those lingering lines are intracranial and scenes from Titanic flash before me, as the water rushes in.

The four of us are there, taking cover under the gazebo.

Thank God it's not a pergola. 

We can't see dry ground.

It rains hard, soft, and harder for longer. 

But before this, I wake up. 

I awaken at eight or so, which is late for an early birdie like me. By nature, I am a night owl.

I toss. I turn. I feel stranger than when I went to sleep. 

I make eggs on toast with toasted fennel pork sausage, for breakfast. 

I drink a liter of water, because I’m thirsty. 

I rub in the sunscreen until it’s on like pale skin, after nine, 75 degrees, and 76% humidity outside. 

I am wearing these low-set baggy jeans and a maroon long-sleeve. 

I see the fabric darken, feel the wetness down my back. Already, I sweat. 

I have got to move through it, that heat and high water.

I take it standing all the way down, knees bent, rocking heel to toe.

My wrist is against the metal railing, and there’s a young woman sitting next to a young man.

She has on a crossbody bag. 

*Little Miss Sunshine* is her claim.

I think of Summer in New York at this time last year. 

The weather can change like a rerouted train, unexpectedly.

You don’t know when the rainstorm is going to stop. 

I see his hand in hers. 

Hear the music playing on an endless loop in my ears. 

What is Life, George Harrison? 

What is my life, if not mine, if not for you?

How can I use my lived experience and imagination to say something that's bigger, more important, than me and spread empathy. 

I feel small in this sea.

Maybe that's what I like about New York City. 

I make it to Fulton, go waterward where the sun is strong at 10:01. 

I take off my sunglasses inside and order a few hours here.

There’s the MFAer in his corner. 

“Were you away?”

He asks, I answer.

The semester’s started. Book will be done by the end of the month.

I still haven’t read his short story. I tell him I’ll have time in December. 

I'm rude. 

He doesn’t like me as a person either. 

The barista places a scented candle between us. 

It's soy, and it stinks.

I've got to get it out from under my abated breath, so I reach out. 

I slide it across the surface as I walk around the counter, which is shaped like the Mandarin character for mountain. 

“Will you be back from now on?”

I don’t know, probably.

He says something mean, and I make him laugh. 

“I’ve been holding a grudge against you.”

Why me? What did I do? 

“Uh, I had one extra ticket, and I invited you to the hottest literary event in the city and you left without saying goodbye.”

I tell him sorry, but he should have invited someone else. I’m Irish. I exit. 

On my way out, I run into my old roommate at the bottom of the staircase.

She enthusiastically says my name and hugs me. 

Her hair is shorter. Her spirit, lighter.

I am happy for her.

“It’s so nice to see you. So, where are you now?” 

Upper East Side, I tell her, in so many words.

“Oh, I could never live there, it’s so sterile.”

I don’t know, I’m a stone’s throw from the museums, and so close to Central Park. 

She lives in Chinatown with 15 people. 

“I’ll send you the info about that writer’s group.”

We say goodbye and promise to make plans.

I decide to go upstairs to see about Fernando Pessoa. 

The young man behind the counter has been meaning to read it. 

He asks if I'd like a bag.

I don't want it, but I do.

I pass by Chatham Square, and notice it for the first time after all this time.

I need to call Nana Pretty.

At 1:23, I walk Orchard street in search of answers.

A bean and cheese is waiting for me, hot and ready.

By the way, I’m off the carne. 

I’ve *been* off the carne. 

All it was, was meat and tortilla. Very few beans. 

After a while, very little ooey gooey.

I am overheated, so I sit on the bench inside to steal some AC.

I lean into where wall meets window. 

Minutes later, the woman in white approaches.

“Elizabeth?”

Yes, I say, thank you.

She smiles.

I smile back.

I don’t know why, but each time I get my order I stick my nose in it to check that the salsa crema is there at the bottom of the bag. 

Indeed it always is, they’ve never once failed me. 

I do this for two reasons. 

I have my own experience in food service, and the stakes are high.

Sometimes the sauces are forgotten. 

Sometimes systems fail.

There it is, under the surface, always. 

The system is as broken as the song I break. 

I get addicted.

I reply.

I replay.

It's neverending.

There's never peace of mind. 

I turn right on Stanton. 

I pass my sister’s favorite pizza spot, and I think of—

The bar where they look and look away with occasional eye contact.

The outdoor stools are only starting to fill, and today it smells fishy (like fish) at Allen.

I make it to the Bowery, where construction workers guide traffic.

A Sudan blocks the intersection, then does a U-turn.

I reach the point where Prince intersects Elizabeth. 

I jaywalk left after another car goes right on the green light. 

I take my chances, and I'm not the exception.

Everyone has the same idea on a sunny Saturday.

A woman sunbathes on a bath towel.

I scour, until I see one lone chair next to a woman on a bench. 

I ask, are you using this.

She shakes her head, then nods.

I understand her without hearing the words.

I lift the chair with my one free hand. 

I feel strong. 

I carry the seat to a spot under the northern tree. 

The man who reads on the other side of the trunk is perturbed by my (respectful distance) nearness.

Immediately he moves his chair some three odd paces.

Three men have red cokes on a green table in the garden. 

The verde is good, spicier than I remember.

I see the sky about to rain. 

Lyrics are again in my head. 

Neil Young from the stereo.

I used to listen with my mom on early morning drives to the farmers’ market.

We like Ambulance Blues, and On the Beach.

“Though my problems are meaningless / that don’t make them go away.”

The atmosphere is doing something different.

I chew, swallow, the last bite and move my station to safety.

Under the gazebo, I get comfortable. 

I’m ready, happy, to wait out the storm. 

Three sisters take cover once it starts.

Hebba, Noor, and Leen are visiting from Houston and Dallas, Texas.

I’ve never been. 

I hear there’s a good food scene.

“What are you reading?”

A book my friend recommended, the Book of Disquiet.

It’s Hayfa’s favorite. 

“No one writes like this anymore,” she wrote me.

This book will be my ruin (in a really good way), I write back.

I have just started reading, but I can tell.

He equates the word distance with decadence. 

It’s raining hard now. 

I see the erosion, the newly raked over wood chips going with the flow, eroding the volunteer work. 

[insert more]

I ask if they'd like a photo, for the memories.

Leen says, oh no.

Hebba pulls out her phone and prepares the camera for me as Noor aims a selfie at the four of us.

The son of the man who started Elizabeth Street Garden (I'm pretty sure) walks over to our shelter.

He's been walking to and fro, bearing down the hatches or something for some time, and is soaked.

Now, he is walking towards us.

"Hey," he says. "We're going to keep an eye on this rain, but if it continues for long, we may close early, so I just wanted to let you all know, the garden may be closing early today."

We thank him, and he walks off on some other maintenance mission.

"Oh my God," says Leen. "Who was that? WHo is that man? He is like the real-life Mr. Darcy in the rain."

The other three of us laugh and nod in agreement since it was in fact pretty hot what had just happened.

If only he'd return with a really big umbrella, I say.

I have a computer and three books to protect. 

I think of Pride and Prejudice, since it was mentioned. I have read the book, but I've only seen the Keira Knightley version. I'll have to look up the name of the male actor, because I don't know it. Matthew something.

When was Mr. Darcy in the rain, anyway?

Oh, yes, I remember. 

Leen must have been referring to the scene where he confesses his feelings, and she turns him down. 

I like the last scene, obviously, because they end up together, and it makes me feel something.

I also like the opening shot of the field and the trees and the fog, becasue it's beautiful and reminds me of where I grew up.

"Do you ever think you'll return to California?"

I mean, California is home. I've always thought I'd live in San Francisco at some point, maybe Los Angeles or London. My close friend from college is from there, and for many years she's told me I must come see about it. 

She's encouraging me to apply to an MFA there. I don't think they have those over there. It's called something different.  

"An MFA in what?"

Creative writing, I tell her. I don't know though, I've never been able to justify paying for one. (Who would pay to do what you could do for free. If I want to be a writer, why can't I just write in my free time and have a job that pays for my livelihood. Maybe the point is I'm still then a prisoner, and it may not otherwise amount to anything that's finished one day. It will, or it won't, but it's proven to be a slow, fragmented process. Maybe that is my process...).

"I get that," says Noor.

Noor is a very good editor is what Leen tells me, though Noor denies it.

"No, I asked her to edit my essay for an application, and I ended up getting the scholarship. Really, you are amazing."

I smile and tell them what I think, they are all amazing. I ask Noor if she'd ever want to go into publishing. 

"Maybe," she says. "But I just don't know how to go about it."

I tell her how I relate. There are so many hidden paths forward. 

Hidden in plain sight are people who are doing things. 

They are actors or published authors, and all of it feels very out of reach. 

I don't know how to get my foot in the door anywhere, so to speak. 

I don't like the sound of that either. It sounds sneaky and undeserved.

I was introduced to this girl whose dad is a top executive at Creative Artists Agency (CAA).

She went to the women's college across the way and majored in film. 

I would've majored in economics and creative writing, and film, if I could have. Of course, I could have, but it wasn't the smart choice to make. There was too much uncertainty, and potentially very few job prospects. 

I don't know, I go back and forth.

Her dad got her a job in Hollywood, in a writer's room, after graduating.

Dream job, I had said (or not said) to her.

"But then I discovered something," she had said to me. "I realized I just don't like writing." 

She liked reading, so her dad got her a job in publishing. 

That's life, as it should be. All's fair in love and war. 

If you could for your children, then why wouldn't you, especially if they are talented?

Work hard, build your own paradise.

Some of us mess it up or miss the boarding time.

I see no plane on the tarmac.

My head's in the sky, but I don't tell them any of this. 

"The industry's changed a lot," the daughter had said to me in 2022. "With every book or movie, you need some celebrity attached to it or it's not going anywhere. It's so backwards, so risk-averse. I was so uninspired. So I quit, and now I'm doing what I love."

I wondered what designing new frozen foods had to do with love, but I believed her.

I sent her some of my writing, at one point, because she asked me to.

Back then, I hardly shared what I was writing with a single soul.

So, it was a big deal for me to just send it.

Any way, weeks and months go by, and I wonder if my writing is really that bad. 

I must have scared her away. Maybe I'd done or said something wrong. Maybe she hated me.

So I send a text into the void, and, to my surprise, she immediately responds. 

That feels really nice. I appreciate the follow-up.

She hadn't read it yet, but she was going to soon.

It was the same story the second time.

She never did read it, but I try not to internalize these kinds of things.

We are all busy and have more important things to care about. 

I want to be the kind of person who cares about everything and everyone (some more than others?!).

I don't think I'm there yet. 

Am I her, to the MFAer? 

I am at a loss, as of late.

I am losing more than the present and past tenses, and the rain does not subside. 

The water level rises. 

"Here," says Leen. "Put your feet up on my chair."

She lifts herself up onto the table, and I thank her.

"We should have maybe tried leaving when we had the chance earlier," said Hebba. 

"We were too distracted," said Noor. "Too interested in conversation."

I know it's no good. 

I feel bad and say I'm sorry.

"No, don't be, we really like talking to you."

I like talking to them too, the three sisters who just appeared out of nowhere.

I wasn't expecting to meet them, and then all of a sudden I met them.

I ask them how long they're here for.

Just the weekend, three days, they say.

"I really like New York City," said Hebba. "At the same time, maybe it's because we've mostly been in places that have a lot of people, but it's tiring, just walking on the sidewalk. Plus, the subway. I'm so used to getting in a car to get places. I don't know if I could live here. I do appreciate all of the green spaces, there are so many more than I expected. A lot more than where we're coming from." 

"We went to Central Park yesterday." said Noor. "It was so nice, just sitting out on a rock. I think I could live here."

My sister was here this summer for an internship, I tell them. I think she may move her after college.

"Ah! So exciting. So, did you live together?"

If I had it my way, I say, I would have loved to, but no, honestly, I wanted her to be happy and have her own experience. I think a big draw for me when I moved out her initially for college was the idea of independence. I wanted indepedence. I wanted to be self-reliant. So, I didn't force it or make her feel bad about wanting to room with friends. I want her to have fun and discover herself here, in the same way I wanted to.

"So have you? I mean, have you discovered yourself?" 

I think I've always known what I value deep down, that hasn't changed. But yeah, I mean, I don't know. In some respects I'm a hot mess and don't know anything about what matters. I'll say I'm still figuring out what my life is about, what's possible given the constraints. Why are there constraints in the first place? Are they real, or imagined? What do I really want?

"I guess, what I can't get over is this idea that people move to New York to find themselves. I walk on the street. We've been walking on the street since yesterday, and I just don't see it. I don't see how it's possible to find yourself in this kind of setting. I see people, and I see them standing in lines."

"What are you willing to wait for, and for how long, I guess, is the question."

"That's been the big thing in Texas too, lately, things going viral because of social media."

I'm not immune to it. I consume it. I know I've grown increasingly addicted.

For me, it's the people you meet here. Everyone comes here for some reason that's really important to them (arguably), and that's really inspiring. That's what New York City really is to me, people and inspiration.

[insert more]

"Before this, we were in Egypt for a wedding."

I went to one in Santa Cruz recently. I would want a small wedding, whatever that means.

I guess, people get blinded by whatever this or that about the wedding and lose sight of the why.

I tell them I've always wanted to visit Egypt. 

"Do you travel much?"

I think of what much means. I haven't traveled as much as the people in my life, but I am fortunate enough. 

I'm always waiting for sh*t to hit the fan, really, so I save.

I need to call or text Georgianna, by the way.

(I would add land and groceries, art and culture, to the list, but) The only thing worth spending your money on is travel, she says. 

If your apartment is too nice, you may not want to leave it. 

But life is what happens when you're not in your box.

I did just go to Italy in March, I tell them, from the middle of March or so to April. 

My sister was studying in Florence.

We went to the Uffizi and I got to see *Spring* in person. 

We spent time in Malta too.

We're Maltese and have always wanted to visit.

I met a woman at a cafe there with the last name Vella. 

She said it is as common as limestone, and likely we aren't related. 

We have other motherlands to return to some day too, like Wales and Ireland.

I was split between Ireland and Wales, when we were assigned a research report in elementary school (Grade 3? Seems young, no? But it was before Teddy in 4th grade. I like that name, btw.). 

I ended up choosing Wales, because I really wanted a pet lamb (before I ever wanted a puppy), and I discovered that Wales has historically had more sheep than people. 

It was a no brainer, still sprinkling.

To me, there was an opening.

So, I took it.

I said my goodbyes and stepped on the sand bag. 

I won't get over it, I told myself.

I've got to move through it.

I stuck my right shoe in the water and launched myself to the other side. 

I hardly made a splash. 

A failure of a puddle jump, I know.

With my waving hand trailing behind, I looked back and mouthed the word.

Sometimes one goodbye is never enough when you want to say hello all over again.

I run to the Bleecker Street station, where there's a six train in three minutes.

Hallelujah, I sing to myself. 

Jeff Buckley, man. 

[insert more]

It's Sunday morning and raining, so I decide to take a walk.

I hear the soles of runners.

They squish against the hexagons of 5th Avenue, while the wheels of heavy loads slosh. 

The road is one way, and otherwise safe.

I'm going in the wrong direction, turning left at 96th Street. 

I follow the path towards Thorvaldsen, thinking there's an outlet.

He holds a mallet and a chisel in his hand. 

I walk back the path.

Up ahead, a man exits just before I enter.

I walk west across Central Park, with a red umbrella. 

I see the pool and algae bloom.

The landscaped brown eyed susans are like the ones in the garden we planted with mom when we were younger. 

I cross Amsterdam and 110 and look at the facade.

I am the reason for the line out the door, next to order. 

A few hours, I say, for here, please.

I find a free table facing the street.

At 12:02, I turn with a light stretch towards the back. 

There, I see Peter in his eighties at the staff table. 

Years (three and a half) have passed, and he’s still here folding boxes for his son on a Sunday. 

I remember how he had picked a fig and brought it over with a proffered palm.  

I reach out to receive it.

Where did this come from, I had asked.

“I picked it for you.”

(You picked me a fig, Peter?)

“Yes, from a secret tree.”

(Wow, I’m so touched, thank you. So, where is this secret tree you speak of?)

“Well, there are some secrets I must keep.”

(Of course.)

I bite into the green fig on September 10, 2022.

I have the picture for proof. 

It was reddish-pink, white on the inside.

I write for an hour and sip the weak coffee.

I'm strong enough to sustain this, the lack of sleep, but the better half of me is crashing.

A man approaches.

I shake my head, then nod. 

He understands without the words and motions his two daughters towards the open table.

Come closer, it's okay.

The younger takes the empty chair sitting across from me.

“How do we order?”

At the counter, I tell them, and point to where the line ends.

Beyond the young woman with a Goodnight Moon tote tugging at her shoulder, I see him. 

Outside, the man with the abundance of plastic bags spoons something out of a to-go box, into his mouth.

A homeless woman stirs impatiently in place and then walks out the door. 

I sigh after the sip. 

I text Zach that I'm in the old neighborhood.

I ask if he's around.

He calls to tell me what he tells me. 

He'll be right there.

He doesn't order anything. 

The apps are going well for him, and he’s a bit overwhelmed by it.

He's created the perfect profile.

"I never want to settle." 

So, he plays the field.

He is looking for the woman he'd want to marry.

I wish I knew someone who was perfect for him.

"I met wifey," he says. "We went on a few dates, but she's not ready for a relationship."

She just got out of one.

She needs time, I tell him, to process.

I don't have much more of it.

I need to go soon and get downtown.

I have some business to attend to at 2 pm.

But first I'm headed uptown for something, to do what should've been done a long time ago.

"What's that?"

I have a book in my hand that's been way past due.

We hug goodbye. 

He tells me he's headed the opposite way but that actually he needs to pee.

I wish him luck with the line on his second approach and turn towards Cathedral of Saint John the Divine.

Morningside is closed, so I do the drop and wonder.

Is it safe there?

Did the cover survive the fall?

Will the library ever let me in again?

I myself need to pee all of a sudden, so I go back just for the restroom.

I feel like someone's parasite.

I think of Parasite (2019), and how people from different socioeconomic classes experience extreme weather differently. The wealthy family's plans for camping had to be cancelled. The poor family's below-street-level home flooded, and they lost everything but one another. They stayed overnight in a school gymnasium, while the kids set up a tent in their backyard (If I remember correctly) after the storm passes.

The line is three people long.

“How is the wait, long?”

It’s moving. I think we’re good.

“Sweet.”

I guess time passes differently for each person in line for the restroom.

The young woman looks at me like she’s a question mark.

*Croissant, plain or with butter and jam.*

*Danish, cinnamon, prune, cheese.*

*Apple turnover.*

*Almond crescent butterfly.*

*Hamentash, poppyseed, prune, walnut.*

*Linzer tart, apricot raspberry.*

*Bullseye, apricot, marzipan.*

*Almond horn.*

*Assorted small cookies by the lb. Or a plate of 4 (table service).*

*Lemon slice.*

*Cherry Slice.* 

*Hazelnut slice.*

*Apple Linzer.*

“I told myself no coffee today,” she tells me. “I’m hungover, and I didn’t want to add to this—"

She stops short of the last word and pantomimes rubbing her stomach.

I say the word melange to myself.

So what’d you get instead, I ask her.

“The danish.”

(Ah, cheese?)

“Cherry.” 

(I’ve heard great things about the cherry and cheese.)

“It’s very good.” 

A beat of silence goes by, and she says she likes the painting on the wall. 

I glance up at the one she’s not looking at.

They’re nice, I say, looking around the room. 

I don't think they're all that nice, but I affirm because I want her to feel good.

(You know, I had never much paid attention to the art hanging on the walls in here, and then I did one day, and I was shocked to find this casual nude, just casually hanging out here.)

“Haha, where?”

There, I say, lifting my curled pointer finger.

“Oh, that is a casual nude, totally.”

(But this is a nice painting, you mean this one?)

“Haha, I actually meant the one to the left of it.”

(Oh, haha, well, that one’s also nice. Are you a big fan of the MET?)

"You know, I’m not really a big art buff, but I like the Moma."

I think that's fair.

I like the Moma too, I say. (It took me a long time to find Starry Night. They had moved it to the second floor at one point, but it’s back up on the fifth, I believe.)

The sliding door opens.

I close it as I enter and pivot on my axis with an awkward half-face of mine saying *it was nice to meet you too!* 

I lock the hatch, and find that the restroom has another fresh coat of paint-over.

The freedom of speech must've been too offensive.

I read the wall as I sit on the toilet seat. 

I'm not too proud a person to deny it.

*Let the people speak!*

*Funny thing I only see people doing fucked up things.*

*New horrors daily. Hell is here.*

*God is love. Love is blind. Stevie Wonder is blind. Stevie Wonder is God.*

*Good things are coming for you.*

*Bring them home.*

*My pen died, lol.*

I take the 1 to 42nd, and then the R/W to 23rd. 

The first thing that Adri says to me when she sees me is Elizabeth for emphasis.

"I broke the glass ring."

Oh, no, tragedy!

Allegra looks at me, with an eye roll.

Since they have a wedding in Venice here soon, I tell them, I'll send them Giorgio's info and they can pay him a visit. 

"Maybe we can take the ring back for repair," says Allegra.

I don't think this broken ring can be fixed.

They'll have no issue finding another, I try to tell them.

Each one is one of a kind.

We catch up with the U.S. Open on in the background, and then walk down 5th to 11th Street.

This is where we part.

I never know exactly when is the next time I'm going to see Allegra.

Work, travel, life keep us both busy but we always find our way back to each other.

And it's just the same as before.

"Say hello to Chrussy for me."

I go east to visit with him.

Call us The Three Muskeeters or Les Triplettes de Belleville. 

"I'll meet you on Bond," Chris says.

I think about how Bond Street in Boerum Hill (which I don't think is boring, btw) compares to the one in NoHo. 

The former goes north-south. The latter, east-west. 

If only we recycled and processed plastics like we do street names...

Now, I'm on East 2nd Street before 2nd Ave. 

I see him there, on the other side, as cars pass us by.

He waves.

I wave back.

We're just waiting for the light to change.

He looks so happy to see me, so I take out my phone to take his picture.

He does the same, something to remember me by.

We hug hello.

[insert more]

My heart is so full, but again it's a hard night's sleep on Sunday.

[insert more]

Before sunrise is the time that I check my phone.

I fall back eventually. 

Until 3, again until 5:49.

I don't set alarms.

I listen to my body.

I feel it's time.

The feeling has never once failed me.

It's only made me late to being early.

On Monday, I wake up at 8:07. 

I make a smoothie on the fly and leave before the half hour.

I will try again tomorrow, but I already know there is nothing certain about sleeping through the night.

I do, and I don't think I'll ever get over it.

All things pass, if we let them.

Love, 

Elizabeth Kolling

P.S.

On the subway, I think of them and the weekend.

I wonder what their names mean, so I look up the meaning when it's not spotty.

Hebba is a gift, or blessing.

Noor, light or illumination.

Leen means tender or delicate.

They are all of these things and more.
