---
title: "Madison IV"
author: "Elizabeth Kolling"
date: "2025-10-05T12:53:00"
categories: [Madison]
description: " "
---


*Interesting* is what he wrote in the margin, and *the apple falls not far*. Freddie didn’t want to be like his mother. He wanted to fall only once, hard and far away from the tree. His family tree was not what he was expecting to be thinking about at 6:30 in the morning on Sunday, as he lay in bed and read the book that Summer had recommended.

“Good morning, good looking.”

Freddie rose from the page, closing The Marriage Plot on his right thumb as he turned to face her.  

“Good morning, gorgeous.”

“You’re so handsome when you have a book in your hand.”

“And when I’m watching reality tv?” 

“You’re a total sub-ten,” said Maddie. “More like a four.” 

“Oh, yeah?”

“Yeah, unfortunate for the both of us, honestly, but I’m willing to add back a few integers.”

“I will say, I’ve received outstanding reviews when it comes to my pecks.”  

“Okay, let’s see that chest.” 

Instead of untangling himself from the sheet, he leaned in quickly and started kissing her like a woodpecker on the chin and cheek and nose and bridge between her delicate eyebrows on the way to her forehead and temples. 

“How’s the head this morning.”

“Good,” she said.

“Good head,” he said. “I like the sound of that.” 

[insert more]

“What book are you reading?”

“Just some book a friend recommended I read.”

“Oh, do I know the friend.”

“Oh, no, just a friend from acting class. We just met, I guess we’re not really friends.”

“I’d say you’re friends,” Maddie said. “If he’s giving you book recs…that’s a friendly thing.”

 “And guess what!”

“What!”

“The main character’s name is Maddy.”

“Maddie? Really?”

“Well, Madeleine Hanna, officially.”

“Two first names for a full name. What a name!”

“The author has her parents calling her Maddy, but the author himself really loves calling her Madeleine. Authors do that, I’ve realized.”

“Do what?”

“Refrain from the characters’ nicknames in the prose parts.”

“What do you mean?”

“They preserve the long form of the name, Madeleine versus Maddy, when it comes to the descriptions, because it makes the character more legitimate as a strong literary figure. And when it comes to dialogue, it’s usually the more intimate nickname, because that humanizes the character. Any way…”

“Interesting, will you read some of it to me?”

“Sure.”

“You don’t have to.”

“No, I want to.”

“Okay, I just thought, since you didn’t seem very sure just now.”

“Oh, no, I’m just tired, still waking up.” 

“How many hours did you get?”

“Uh, three.”

“Baby.” 

“I’ll take a nap later.”

“Okay, but we have that thing at…”

[insert more]

He read her the part where their in her bedroom, and Mitchell wipes gel on her.

“I don’t like Mitchell,” said Maddie.

“Because of the gel?”

“Yeah, like what was that.”

“I think he was trying to flirt with her.”

“No, he was just messing with her.”

“He could’ve been trying to do it as a prelude to a massage, a little bit of an upper neck rub.”

“I’ve never heard of an ear massage.”

“You are missing out on massaging the lobes, my love.”

“Ha-ha.”

“He knew he messed up,” said Freddie. “I mean he was almost crying.” 

“Mitchell is immature.” 

“It’s an immature thing he did, but I’m not going to discount him quite yet at 15 pages in, I mean, it’s one silly incident.”  

[insert more]

Maddie had pilates and then a studio session.

[insert more]

He left their apartment with a notebook and pen and the book in hand and did his usual Saturday roll, up sixth avenue and east along Minetta Lane, to the cafe that was green.

[insert more]

Freddie wanted to move to New York City after college to pursue his acting career. Maddie hadn’t wanted to move there, but she did because she wanted to be with him. She wanted to grow old with him. Their relationship was the only thing that gave her life meaning, maybe, besides her music. Her parents weren't thrilled about it when she came to them with the conviction of becoming a professional musician, but they wanted her to be happy so they didn't do as much as protest. They had moved to Massachusetts, and they’d sworn, after high school, to never return to Manhattan. Maybe they would Brooklyn or the West Village where their daughter now was, but never the Upper East Side. 