---
title: "Maximilian IV"
author: "Elizabeth Kolling"
date: "2025-06-23"
categories: 
description: " "
---


Past the catch of the day, Catherine, past Oliver, just before James, the sidewalk is packed (at at least 7 am) like a can of stinky anchovies. 

Max walks past, not looking back, but instead of fish, it’s people—plain, simple. People who haven’t showered or tasted water for some time stand in the shadows of others’ quenched thirst. He is afraid, afraid of their scent and poverty and he steps towards the street. As he threads the furthest edge of the sidewalk, no one notices his suspicious pace or held-back tears or bloodied lip. 

The people hold tight to their garbage bags along Pearl Street, awaiting the small but potent storeowner’s green light. He’s a short, frail main, with stage four, standing at the same doorstep as his father. He puts the neon BIC in his shirt pocket and starts smoking the cigarette. The people breathe in each exhale as he looks out. It’s a mass but not a sea, and it won’t be a record day.

With a sigh, he flicks the butt to the ground and lets the ember glow. Reaching for the broom, he catches a glimpse of his son and daughter who are inside sorting Saturday’s stock. He smiles weakly and then turns away. He waves the bristly end towards the people, and they move back in tandem, like some superorganism, so he can sweep. 

By the time the storeowner recedes inside and flips around the *sorry, we’re closed* sign (which hangs crooked), Max has already passed the abandoned diner and red brick towers and swung a left on Dover, past FishBridge Park Garden, onto Water Street. 

All of this, because *Moby Dick* was his favorite. 