---
title: "Samantha III"
author: "Elizabeth Kolling"
date: "2025-07-13T20:59:00"
categories: [Samantha]
description: " "
---

Samantha was alone, not lonely this time, wearing no nightgown, and Ethan was anywhere else. 

She knew things with him wouldn't work out or last after the year they had had sophomore year, but she'd let her lesser judgement lead and wouldn't give in so easily. She was a try-hard with soft edges, and nothing ever did come naturally. How was love any different?

"Why do you have to assign a double meaning to everything?" 

"I don't—"

"Just take things as they are," Ethan had said to her. "The world isn't out to get you, it's not full of ulterior motives, and there is such a thing as nice people." 

He was split between those who were they themselves divided, his grandpa and mother, for instance, places as well, and she could never get enough of him that lasted to Sunday. She couldn't place him. He was here, there, half way around the world for the summer (service trip to Ghana), and she had no more lines to memorize. 

She decided not to do the summer production. Her single father who raised her and her little brother couldn't afford it, so she got a job at the ice cream shop (at town center). Plus, she hadn't gotten the internship. 

