---
title: "Samantha"
author: "Elizabeth Kolling"
date: "2025-07-08T22:25:00"
categories: 
description: " "
---

Samantha didn’t much care for Shakespeare, but she took the gut feeling with a grain of salt.

She hadn’t actually read any of his plays, *Romeo and Juliet*, for instance, but she already knew they weren’t for her, of course, because everyone else loved them. She preferred the salt of the earth and not to fawn over popular culture, out of principle. However, Shakespeare (she heard) was a woman, so maybe she would read him one day. She was a feminist before anything, even though she was in love and wanted to get married one day and have a family. She wouldn’t cut the crust off. That’s for sure. For now, that kind of theatre was not to be touched (too pretentious), not to mention gate-kept by those drawn to it (actors, namely, steeped like tea in self-regard). The language was too British, posh and high brow for her. She resolved to play Nina and only read real writing. Life was already complicated enough. She wanted simple moments, straightforwardness, a seagull eating a chicken wing for no other reason than because it was on the ground. Chekhov was her favorite, but she didn’t get the part. She was set to play Masha instead. It bummed her out because she couldn’t relate at all to the character. She was happy, head over heals for Ethan, and she didn’t own one thread of black clothing. 

Aside from the deep-seated pessimism, she was a sweet person.
