---
title: "Freddie III"
author: "Elizabeth Kolling"
date: "2025-10-17T22:00:00"
categories: [Freddie]
description: " "
---

[insert more]

Maddie had a show in the East Village that Friday night, and Freddie was not alone in the front row. 

[insert more]

"Alright," she said, gripping the mic stand. "We're gonna slow it down and get a little sentimental. I know, I know. This is a new one I've been working on...and this one's for you. You know who you are."

(Maddie was looking at Freddie.) 

It was a love song, and the lyrics were: 

[insert more]

He went out with her and the band afterwards and gave the waiter his card to start the tab.

"I'm good with water," he had said. 

"I'll have a...Manhattan," Maddie had said.

The bandmates all got beers.

[insert more]

He paid for everyone when the check came, and Maddie forgot to thank him.

[insert more]

"Is something wrong?"

"No," he said.

"Are you telling the truth?" 

"No."

"Tell me what I did." 

"Honestly," he said. "It doesn't matter."

"No," she said. "Be honest with me."

"Ugh, it's okay, nevermind."

"If we don't have honesty, what do we have?" 

"Honestly, it's what you didn't do." 

"Okay," said Maddie. "What didn't I do."

"You didn't thank me for paying." 

"Really? I'm sorry." 

"It's fine."

"It obviously upset you."

"I'm not upset." 

"If you say so."

"I'm fine paying for you, but I don't really want to pay for the whole band, and I feel like that's your expectation. Like in order to spend time with you and the band, I have to be your cash cow." 

"I don't want a cow."

"It feels like you do."

"I don't," said Maddie. 

"Okay." 

"Freddie, you know me. I'm lactose intolerant. You being a cow just wouldn't sit well. I'm getting the tab next time, okay?"

"Thank you, sorry, it just felt bad in the moment."

"Is that all?" 

It wasn't all of how Freddie was feeling.

[insert more]

