---
title: "Maximilian V"
author: "Elizabeth Kolling"
date: "2025-06-26"
categories: [Maximilian]
description: " "
---



The rain came pouring down, and Max took cover under the arms of the elms. 

He was in the middle of his near-twelve mile run, and there was a turtle walking on the pavement. The path itself led nowhere waterward, though the pond was just there. Couples rowed their boats, unawares, and Max watched the turtle pick up pace as a little girl wobbled speedily towards it, with those little legs not moving fast enough for the reach of her outstretched hands. She wanted to pet the turtle and take it home, but before she could pick it up she heard a bellowing *Hey!*

Max turned to see where the abrasive scream came from; it was a Central Park ranger in a golf cart, speeding down the west-side loop. 

“Leave him alone!” said the Central Park ranger, putting the cart in park. “He’s trying to get home.”

The little girl stood back, and they both watched as the turtle headed straight for the fencing but struggled to pass through. The turtle was stuck, and the little girl covered her eyes as it tried with all its might to move backwards. The turtle tried again as Max turned his head to look for a moment at the Central Park ranger. 

He didn’t care what he’d said about not interfering or whether he was breaking someone else’s made-up rules. He walked towards the turtle, and freed it from the metal fencing. He saw blood where the metal had scraped the shell, and the turtle disappeared downhill towards the pond, into the foliage. The Central Park ranger nodded at Max, and took off. 

“Thank you,” said the little girl with a tilt of the head. “Why are you so skinny?"

“I’m a turtle,” he said. “I only eat leafy greens.”

“You’re not a turtle.”