---
title: "Levi XIV"
author: "Elizabeth Kolling"
date: "2025-09-13T12:33:00"
categories: [Levi]
description: " "
---


They were so close to being there, but they weren't close enough. 

“Hurry up and get out of that bush, Levi, or I’m going to leave you in the dust.”

“Dude, chill out.”

“Oh, I’m out, I’m out of here.”

Ethan starts to walk faster. Levi sighs hard, disentangling from the bramble, and runs up to catch up.

“No you’re not,” said Levi. “Not too fast.”

“I thought you ran cross country. You’re out of breath.”

“Don’t judge.” 

“Why do you even have to get there before closing? Samantha has the closing shift, so she’ll be there cleaning up for at least another hour.”

“Yeah, but then she’s going to want me to help her clean and that is not my job.”

“You are unbelievable to me.”

“Believe me, it’s hard work being this out of touch. Constant rebuke from close friends, the whole nine yards.”

“I’m just saying, you should be a better boyfriend, because you’re half-assing it. I mean, what do you normally do when you get there before closing, and what do you do while she’s closing, just sit there with your feet up reading?”

“I walk in. It’s usually quiet right before close, so I walk straight up to the counter. She comes out from behind it and gives me a hug. I ask her about the new flavors. She gives me samples of the old ones too. I tell her which one I want, and she scoops a generous portion into a cup. Sometimes, a cone. She comes and sits with me, and we talk for a little bit about this and that. Then she says she better get back to it. I tell her I’ll go read by the Depot while she finishes up at the shop, and for her to meet me there by the big tree when she’s done.”

“I’m highly alarmed by the way you, I don't know, move through others' worlds as if they’re your own.”

“Any way, I did forget my book today, so maybe I’ll have to pick up a broom.”

“Sweep or get swept, my friend.” 

“Deal, dude.”

“Speaking of, what’s up with Mr. Dealer, the dude is MIA?” 

“I don’t know. I haven’t been able to reach him either.”

"What have you been doing, owl calls?"

"Haha, very funny."

“Want to go there together later tonight?”

“Uh, I am running low, but honestly I’ve been trying to cut back because of school and all. Plus, I think Samantha and I are going to go back to my place. My mom’s on a yoga retreat, so free house.” 

“Nice, well, enjoy.” 

“You’re totally welcome to come hang for a bit, but I may have to give you the signal at a certain point.”

“Honestly, I’m all good. You two have…fun. I have to help my dad with things around the house any way.” 

“Alright, well, see you tomorrow, we still on for the Prophet?”

“Yep, yep.”

“Later, gator, say hi to Hilda for me.”

Levi turned right towards the used bookstore as Ethan swung a left towards the ice cream shop to see about the flavor of the day and also Samantha. He had been told it would be blackberry-rhubarb with jalapeño and mint (the shop-owner and ice-cream maker had told him last weekend), he was looking forward to it. The flavors always sounded disgusting to them in theory. But every time, each spoonful was as blissful as the last crazy combination. Ethan had developed an odd attachment to ice cream, because it reminded him of going to get ice cream with his dad after soccer games when he was still here.

“Are they ever going to brink back watermelon and peppercorn?”

“So that’s your favorite?”

“It was my dad’s.” 

“I’ll ask Patricia about it.” 

Patricia (age 78), the shop owner and ice cream maker, a very open-hearted and eccentric old woman. 

“I’ve been doing this for a long time, and I would do it for longer if I could.”

“Why can’t you?”

“The cost of milk. I can’t make ends meet, the way things are now.”  

“So, why is milk so expensive now.” 

“You haven’t heard?”

[insert more] 

Sometimes, Levi didn’t have one in mind. Other times, he knew exactly what book he wanted to read, usually a recommendation or one whose reputation preceded it. Today, he walked straight to the register to bum a lookup. 

He was looking for one book in particular, the one Samantha had recommended to him. 

“Hi, Hilda, how are you?"

"Well, thank you."

"That's great. I was wondering, can I ask you to look up a title for me, when you have a chance?”

“Your chances are good now, I’d say, so let’s have it, here,” said Hilda, bringing her lime green and aquamarine readers to her eyes, placing her long fingers on the keyboard of the ancient computer. “Title?”

“Uh, The Cherry Orchard.”

“Ah, Chekhov,” she said. “I’m sorry, but I don’t think we have it.”

“Ah, okay, thanks for checking.”

Levi left the register and turned to face the shelves. He went to the section with the plays, just to check for himself, but Hilda was right. The play wasn’t there. He did see The Sea Gull. He remember ed Samantha had mentioned that one to him too. Though it wasn’t her favorite, he tugged it free from the shelf. 

“Mmm,” said Hilda. “The Sea Gull is also a good place to start.” 

Hilda only knew Levi through the books he’d bring up to the counter, and, through the years of him coming here, she had begun to develop a portrait of the young man.