---
title: "Red Bird"
author: "Elizabeth Kolling"
date: "2025-07-20T10:41:00"
categories: [Red Bird]
description: " "
---


In the City of Fog, City by the Bay, on a Holy Sunday, church bells chimed and signaled lunch time, and so it was: they ate under a sun unseen, the sons and daughters and androgynous children of God. Oh, how they ate sundry lunches in each Cardinal direction.

Due east, the gentleman methamphetamine user flicked a lighter beneath her silver spoon and licked his lips as eyes, wide, watched the ice turn to ocean. Ice turned to ocean and then to
dust in the bowl, as he pointed the bevel and pulled the plunger. The viscous elixir rose like Christ, up the barrel.

The barrel ached in the Tenderloin of San Francisco, where heels were tender and none was well. None was well, but all were alive to feel the barrel, belly and loins, and all below ache. The head and heart ached above all, like the belly and loins of the gentleman methamphetamine user whose body had become a cavern place to put his pain. His pain was scalene, an unholy trinity of aches.

Heartache. 
Headache. 
Body aches. 

“Them three together is the feeling,” said the voice in the head of the gentleman methamphetamine user whose knack had always been numbers, geometry, but never grammar or  the English language at large. “In that order, the aches that ebb and flow and underlie everything, these are them.”

“They!” Sister Mary had screamed. "These are they!"

The gentleman methamphetamine user remembered the scream of Sister Mary, still some Spanish, and afternoons of his youth spent in classroom 819. 

“Her whose laws of language were a weapon, and whose ruler was like a yard stick.”

She whose ruler was like a yard stick, striking down on the gentleman methamphetamine user, had not seen his socks leaking the unsold chocolate or the linoleum floor where a puddle formed. He formed the memory, remembering his sweet tooth and third grade side hustle, the black market business of stashing candy bars before school, after paper route, at the Sunset corner store as the sun rose, wearing khaki pants with a long hem and oversized white tube socks stuffed chock-full of Pay Days and Babe Ruths and Butterfingers and Twix bars, working first the monkey bars and then turning treats around the tetherball pole for ten cents on the margin, all to appease and garner the favor of his friends, the sugar fiends of the playground, at lunchtime. He remembered that one Holy Monday that had been slow and oddly hot. He remembered the unsold chocolate and how uncomfortably it melted in his socks, leaking further into the shoes, and he remembered how he wouldn’t dare raise his hand for the restroom so soon after lunchtime and risk the reign of her ruler. He remembered how the voice in his head had taunted him, even then, and how slow the better half of his mind moved in the afternoon, like a sprinkler leak above one lush patch of Mission Dolores, and how all he cared about throughout the lesson on pronouns was counting his grass (coins) and calculating lost profit.

“Drip-drip-drip.”

“Them?” he had answered, in the second row from the back of the classroom.

“They!” Sister Mary had screamed, striking down on him, only to skid betwixt the desks.

The gentleman methamphetamine user remembered the skinned flesh, the skid, slip and fall, of Sister Mary, and the sound of her crushed pelvis like chalk across the chalkboard, and he remembered the unsavory sight as she lay there below, broken-boned and brittle. He had felt unwell, with a belly full of cow’s milk, peanut brittle, and Pay Days.

These were they, his thoughts growing cyclically like the tide. This was the fate of the gentleman methamphetamine user whose body ache was a sneak attack wave, sweeping his child into the Pacific, and whose headache and heartache were like the fog—in and out, endlessly. Neither here nor there and then everywhere, the fog reminded him of her. The fog always reminded him of Father John-Michael Fromm whose unconditional love was the source of their suffering. 

“Unconditional love,” Father John-Michael Fromm had said during Noon Mass at Saint Teresa of Sunset some twenty or so insufferable years ago.

The gentleman methamphetamine user had been only a boy back then, but he remembered. As a young man all these years later, he remembered: Good Friday at School of the Ascension; Saturday at the Ferry Building Farmers’ Market; Holy Sunday through stained glass. He remembered each day, beginning and ending, as if it were yesterday. It was spring, late April.

“May!”

Maybe it was early June or mid-July. The sun was shining, and the birds were screaming. The gophers, undisturbed, were disturbing the peace. The soil above and below, in and around the baseball diamond, was all in a ruin as a stubborn cherry plum tree bore its sour bounty behind the dugout.

“Without equivocation and poor tenses!” said the voice in the head of the gentleman methamphetamine user whose habit had gotten out of hand. 

The gentleman methamphetamine user had a habit, among other ailments. He had hyperthymesia, a photographic memory and an encyclopedic mind, but a habit of telling himself and every set of eyes half-truths. In truth, the sun was not shining in late April or May or early June. The sun had not in fact shone through the fog that Friday, which was far from good, and he remembered the way to that small room at the end of the long corridor.

“Yesterday is today,” Father John-Michael Fromm had whispered as he led the boy astray that Friday. “Today is tomorrow, the first day of the rest of your life, how does that sound?”

There were the Good Fridays and the bad Fridays, the baseball games lost and won. There was the unconditional love of his life and her father’s avocados. There were the Holy Sundays and sermons.

“The demon stands before you,” said the voice as the gentleman methamphetamine user who aimed a skeptical brow before shaking his head, no. “No, you liar.” 

“Unconditional love,” Father John-Michael Fromm had said, interrupting himself in the middle of his own speech about the ascension of the Virgin Mary. 

During Noon Mass at Saint Teresa of Sunset some twenty or so insufferable years ago, Father John-Michael Fromm sent forth a fateful pair of words and a pregnant pause that would come to haunt the gentleman methamphetamine user like the miscarriage of the proud pregnant mother, seated in the front row. She was proud of him there, and neither knew of the imminent ache, at the time. The proud pregnant mother smiled wide and delicately held her belly as the boy’s eyes watched narrowly. The gentleman methamphetamine user watched as Father John-Michael Fromm inhaled and looked longingly out the window. A kaleidoscope of colors seized him. He saw red and yellow, vermillion and amber, chartreuse, green, blue, indigo, magenta and violet, violence in the home, the thorn-adorned rose in the bleeding hands of Her, and the scene of Jesus meeting his afflicted mother. Only he saw the pacific exhale, Father John-Michael Fromm inhaling a memory of his own, and only He saw the boy seeing. 

See, Father John-Michael Fromm saw all. He heard all. Father John-Michael Fromm had eyes in the back of his head and the ears of a serval or something, but he himself was prey, and the boy knew this to be true too. Like a moth to a flame, Father John-Michael Fromm tweaked his neck toward the boy and sent forth a wan smile. The boy smiled back, standing there beneath the altar, holding the wine or the water or the napkins or whatever Father John-Michael Fromm needed as he broke his silence.

“Unconditional love is the source of all suffering.”

The life of the altar boy thereafter was all suffering, a series of aches relieved in small rooms, and the days were all the same. The first day of the rest of his life had come to be about forgetting, remembering, and getting well again, endlessly.

There was no end. None was well in the Tenderloin of San Francisco, where a wind tornado violently whirled a used napkin into the salty air. Eyes, wide, watched it waft like the feather of a blue-winged teal. The lady methamphetamine user, known in these parts as Red Bird, pressed her thumb and forefinger together, pinching the prize. Her hunt was complete, and Red Bird clung to the canvas, watching as the gentleman methamphetamine user prepared a place setting. 

Red Bird softly tapped her lover’s knee cap, clinging too to the pen, stolen from the mom-and-pop tobacco market nearby. Red Bird waited for a flicker, but the flick of his lighter beneath her silver spoon did not inspire Red Bird. Inspiration struck elsewhere in the Tenderloin of San Francisco, across the way, where lay the fentanyl users. There were seven keeled, and one still standing.

The fentanyl users whose numbers had been but three the day before yesterday and contained to the south-west corner of Hyde and O’Farrell, were now eight, inching further, as if the belly and loins were their manifest destiny and theirs to charter, disturbing the peace, too close for comfort. Red Bird watched with narrow eyes and a pointed brow as the last standing fentanyl user jammed the needle into his left foot. Crimson poured out, and the fentanyl user pulled the plunger. She had heard one shot was all it took, for their backs like feral cats’ to arch over, and shook her head in disbelief. The needle fell from the palm, the spine curled like a sleeping infant in fetal position. Eight of them now lay like ducks in a row, across the way. 

“Turk is not their territory,” said Red Bird, whose own territory was uncharted, typically where business was good and married men regular, but lately here, next to the gentleman methamphetamine user, who sat next to her on the curb of Turk Street, shoulder-to-shoulder, outside Tobacco & Market.

“Taco and Market” said the voice in the head of the gentleman methamphetamine user who pinched the used needle as nonchalantly as those Lucky Strikes between the thumb and forefinger of his late father. The gentleman methamphetamine user looked at the light-emitting diodes, and the semi-dead sign of the mom-and-pop tobacco market. The lowercase ‘B’ had gone dark since the last time he’d taken a walk down Turk, and his father had died when he was barely twelve years old. “You are starving, my son. You haven’t eaten for nineteen days, but we’re not breaking fast for that shit.” 

“I hate you,” said the gentleman methamphetamine as he looked away sharply. His eye caught a pigeon who flew overhead. He followed the wingspan, mesmerized, wanting to fly. 

The pigeon landed at the feet of an old woman in a wheelchair who was regularly on display at the far corner. On the north-west corner of Leavenworth and Golden Gate Avenue, the old woman in the wheelchair dipped bird bones, drums and wings from KFC, in a bucket of bleach and scattered the seed across the asphalt concrete. The lone pigeon pecked clean a chicken wing and seconds later dropped dead. 

“You killed him!” screamed the gentleman methamphetamine user.

The old woman in the wheelchair paid no mind to the gentleman methamphetamine user. She decried society between cries, screaming at the indifferent sun. It was a song for deaf ears and a sight for sore eyes. The gentleman methamphetamine user plugged his eardrums, but he couldn’t look away.

“Look away!” the old woman in the wheelchair screamed. “Don’t look at me! Mine-mine-mine! I, the morning bird in mourning, mourn you! You! You! You! It is you to rue noon! It is you I mourn! I mourn the boyish hubris of birthed men! I mourn the name your father gave you, and the way your Father made you! I mourn the pavers and paved road! I mourn the plane and places to go! Be present where you plant your feet and face what you have made of the City of Fog, City by the Bay, on a Holy Sunday! You excavated oil and gas and made the chasms of hydraulic fracturing! Bottled water and stolen springs, shadow banking and crude futures staining American dreams! Climate change and broken accords! Milk alternative spilled across the cowardly sidewalk! Tesla stock! Delivery as afterthought! The blood is on your hands as Michoacán avocados blanket black, burnt toast in styrofoam! Takeout to your doorstep and ne’er a tip! Pay tuition to own your education! Sell or be sold! Or refuse. Live like I do! I love my life! Do you love your trailer towns, AC, and trust fund? I inherit the oppressive sun, systemic oppression and jail cells! Ho Hos and Snickers running low! Commissary and criminal justice like skin cancer. Unlawful simile! Overused alliteration and unused napkins! Leftovers sold again as kitchen-sink stir fry. Failed restaurants and Yelp in pursuit of capital! No! Consumer surplus, sore thumbs and Type A coffee drinkers’ stained teeth! Blue Bottle flies feasting on stale meat! Barbecues abandoned! Forsake your fate and synonym! Jesus, Mary, and Joseph! Mother of God! I am the same as you are!”

“You and I are not the same,” whispered the gentleman methamphetamine user to himself as the old woman in the wheelchair continued to sing her song, sober, as she always did, on and on.

“Battery is an explosive!” she shrilled. “Don’t answer the phone!”  

The old woman in the wheelchair whose mind had, seventeen times, survived shock therapy could go on for hours like this. This, he knew. The gentleman methamphetamine user knew, and knew better than to delay lunch for the free show. He prepared a place setting, setting down her silver spoon, only to feel Her ruler strike his wrist. 

“Ow!” he said, holding his forearm. 

“What’s wrong?” asked Red Bird without an answer.

“Forks on the left!” Sister Mary had screamed. “Spoons and knives on the right!”

The sun cut through the pale, and the gentleman methamphetamine user remembered the scream of Sister Mary, the summer of his youth between grades five and six spent in etiquette school. He remembered his grandmother’s china, silver forks and silver spoons and silver knives and the pride in his pregnant mother’s eyes at Thanksgiving, as he set the table for the whole family. He remembered family dinners on Good Fridays and bad Fridays, morning prayer, penitence and detention, little league, and he remembered the scent of lemon rosemary, chicken and pitted prunes and red peppers and green olives together in one dish to be savored and eaten slowly at the table set by him. His belly and heart ached in the Tenderloin of San Francisco, as he saw her silver spoon, which lay there, on his left side. 

“Idiot,” said the voice as the gentleman methamphetamine user sighed. He knew he had sinned, aching for his failure and failed education, and sought salvation in another order of eating

“Ladies first,” he said to her.

“I’m not a lady,” said Red Bird.

A pin dropped in the Tenderloin of San Francisco, and the gentleman methamphetamine user wasn’t sure of anything anymore.

“Sure,” said the voice in the head of the gentleman methamphetamine user. “Red Bird is not a lady, but she is surely a woman. I assure you, you have already taken Red Bird down and come to know her shores. Just beyond the bluff, remember? And you did so just this morning, as the sun was rising and as the mourning bird was screaming.”

The voice in the head of the gentleman methamphetamine user assured him of her sex and spoke the truth, the whole truth, and nothing but the truth. It was all true. He had already taken Red Bird down and come to know her shores, just beyond the bluff. He remembered. He had done so just that morning as the sun rose and as the mourning bird had started to sing.

“Did you not sail over sea?” the old woman in the wheelchair had screamed. “Charter plane for paradise! Pave road! Drive along the winding bluffs, once? Beat them down further with heavy
tires, the weight of your canted cars and sliding scale morality? Pray they pull you over? Beg justice be served to you on your silver spoon? Yes! You let legislation, graphic tees, bumper stickers and failed systems speak for you while you unbuckled and played backseat jello, felt the touch of another’s shoulder against your own. Let your loved ones lean lest they fall, and they fell! Yes! You let your loved ones lean so far they've fallen. Even I heard the sirens as you sped full speed around the bend. Did you even ponder physics? Centripetal force? Friction!”

Red Bird still felt the friction and felt herself taken further by her lover who tenderly searched her varicose leg for a vein, but she did not have the look of an in-love person. Red Bird wore hate on a long face, though she did not hate her lover. She hated the fentanyl users who lay all pacific across the way. Looking, just looking, Red Bird finally felt the flicker and, with a flick of the wrist, penned a poem on the used napkin. Eastern Tenderloin, she wrote. 

Addicts sleep,
like sloths in the streets,
but I’ve a dream
back west, wistaria and burgundy,
wonted,
awakening.

Red Bird read the poem back, and didn’t entirely hate it. She set down the stolen pen, folded the used napkin into a tiny square, and tucked it into the back pocket of the gentleman methamphetamine user, wearing her heart on her sleeve as she always had. 