---
title: "Maximilian XIII"
author: "Elizabeth Kolling"
date: "2025-08-03T23:55:00"
categories: 
description: " "
---


Max left his apartment especially early that Sunday morning. He went to the cafe, just to see if Herb (hard H) was doing okay. Herb wasn’t there today and part of him was worried that something had happened to him, but he put off the thought of worst outcomes and still decided to take his coffee straight. He sat at the window seat and leaned his bony shoulder against the potted ___ that was sandwiched between two ___ on the sill. The thing about the window seat where the plants were was that this was also where there were gnats, and this cafe for some reason was infested. Max couldn’t be sure, but he started to develop the overwhelming feeling that he had contracted a family of fleas that were doing the waltz on the back of his neck with a pirouette down his spine.

“Am I paranoid or,” he had said to Herb one day. “Or is this a bug bite?”

“Oh, God!”

“What, what, get it off!”

“You got a real eager bugger of a pimple.”

“Herb, Jesus.”

“I almost—”