---
title: "Buck Wilde II"
author: "Elizabeth Kolling"
date: "2025-09-20T12:39:00"
categories: [Buck Wilde]
description: " "
---


Disbelief was the feeling, and only some relief. 

The gentleman methamphetamine user didn’t believe that he’d done anything wrong, for one, and he definitely didn’t believe the old woman in the wheelchair. She treated him like some premeditated murderer, which was off base and wasn't further from the truth. He remembered finally getting to third base, after having gotten himself in quite the pickle. All these years later, he was still somehow stuck in the middle between two home bases: Sunset and Mission.

“She probably hasn’t even read the Republic,” said the voice in the head of the gentleman methamphetamine user who bowed his head as he passed a homeless person who had a dog on Fell Street. He was making his way towards Market and the Mission District, and it always pissed him off how strongly it smelled of urine. It also always made him sad to see it, innocent animals mixed in with this mess they were in. He wondered if the two of them were all that different, and why it was that people tended to care more for their animals than God’s children. There was another one, suffering in broad daylight, and no one, not even He, was coming to save him. 

“You have to save yourself,” said the voice.

There was only one way forward, and the will of God as his guide. 

“Please,” said the homeless man who called after him. “For the love of God, I’m hungry.”

The gentleman methamphetamine user held his own stomach as if the words of the homeless man were a gun wound. He couldn’t remember the last meal he had had, but he would have given the homeless man any banana or burrito in his hand if he had had one. He didn’t know the guy, but he did know a guy. He clocked the cross streets and then continued on towards Market, feeeling sick. He himself was starving.

[insert more]

He asked the people walking towards him along Mission Street. 

"Would you peel a lonesome buck from that wad." 

"I see those deep pockets."

"Sorry, I know these are shallow times we're living in." 

"Though I own no metal detector, but I've even tried the beach." 

"Do you have a spare dollar?"

"I really need one dollar."

"I'm saving up for some lunch."

"Would you be so kind as to support a good deed?"

"All I'm asking for is a bit of charitable giving."

"If I borrow your wallet, I'll bring it back."

"I won't take more than a dollar."

"No cash, you say?"

The people couldn't care less. Besides, they only carried credit cards. 

[insert more]

The taqueria only took cash.

[insert more]

"I only have five dollars and fourty three cents, but I have some good sense about me, and I can work the rest off. I'm asking you for one carnitas super burrito today and a job, goddamn it. I can start tomorrow. I'll come back tomorrow. Sorry for swearing. I don't know what came over me. It won't happen again, if you hire me. If you don't hire me, I'll fire you and everyone in here. No, that's not a threat. But I do mean business."  
