---
title: "The Artist's Way"
author: "Elizabeth Kolling"
date: "2025-05-30"
description: " "
---


Dear —, 

It’s 7:44 pm on Friday, May 30, 2025, which means I just missed my train, and the next F to Downtown & Brooklyn is in 13 minutes. Is it possible just to be, the luckiest unlucky person, or not to be? Now I see a perfectly clean seat to sit on, and have the opportunity to write whilst I wait. It’s my first time sitting on a subway platform bench, in all the (seven) years I’ve lived in this inspiring, (only slightly) dirty city, and the F train is rocking into the 57th Street station as I think of all the years we’ve called each other friends. Part of me wonders how in the world thirteen minutes have passed, and I’ve only managed to pen this much on the back of a postcard. I feel like the woman in the painting, who reminded me of you, deep in thought, with books on the table in front of her, I’m sure, a writing utensil in her right hand, and an infinite number of ideas in her head. She’s very fashionably dressed. Her green scarf reminds me of the denim skirt you wore, and polka-dotted long-sleeve henley, when we met up at the MET earlier this spring. This book I hope will offer you something along your creative path. I look forward to reading what you write, and one day seeing your name on the cover, in the storefront of some independent bookseller on the lower east side of Manhattan, like Sweet Pickle Books, or McNally Jackson on Fulton. Rooting for you, and in your corner—always. Happy birthday, and summer solstice.  

Love, 

Elizabeth Rose Aurora Bee Rain Kolling
