---
title: "Maximilian XII"
author: "Elizabeth Kolling"
date: "2025-07-28T21:57:00"
categories: [Maximilian]
description: " "
---


In a city full of people he looks for her, walks single among strangers, intertwined fingers, gives a turn, double takes, misplaced looks, trips over pieces of uplifted pavement but keeps his balance. He manages, but it wouldn't matter the distance. He could walk a mile in those tired boots, and he'd still cling to the hope that she's just around the corner, crossing the signal to the opposite side. 

"I had this dream," Max said to the stranger who he trusted enough. "She'd be coming from uptown and I'd be walking the reservoir across to just before the steps, and we'd stop looking down at the ground. We'd see each other walking towards each other, and—"

"And, what? Then what?" 

Herbert went by Herb, and Max had developed the overwhelming feeling that Sara was his soulmate, everywhere he was and nowhere, haunting him.

It wasn't like he could just text her out of the blue. Besides, he didn't even know if she was still in the ciy. He hadn't seen her at the MET since after last August, and Catherine wasn't around either. 