---
title: "Freddie"
author: "Elizabeth Kolling"
date: "2025-10-13T09:00:00"
categories: [Freddie]
description: " "
---

The rain pouring down on the lamp post in the dead of night was like the water pressure (water from a hand-held shower head) in their one-bedroom, one-bathroom apartment on Barrow. He walked West 11th Street, past the 10-foot skeleton wearing a flower crown with either crows or ravens in its palms, past the celadon pumpkins that lined the brownstones. He passed a bird-box library and looked inside, where there was a lone copy of a short story he’d already read but didn’t have a copy of in New York. He tweezed the little knob and opened the little door and reached for *The Murders in the Rue Morgue*. He thought of his father who had read it to him when he was five years old (an interesting choice). He put the tiny paperback in the pocket of his dark brown leather jacket (the arms and shoulders of which were getting rained on in spite of the umbrella that he held (insecurely) over his head of dark brown, shaggy hair. 