---
title: "Samantha XII"
author: "Elizabeth Kolling"
date: "2025-10-01T21:14:00"
categories: [Samantha]
description: " "
---


It was Wednesday, which meant class would start with voice and speech and end with movement.

“Today is all about lifting the soft palette,” said the voice and speech instructor who induced a yawn on the spot only to point her finger at Jonah and shout out, “Yes!”

Everyone turned in the direction of her long almond nail, where Jonah was ending a yawn. One by one, they started yawning. Adrian saw Samantha who saw Kirk who turned his head towards Igor who looked at Alexis who twisted towards Jamal who faced Freddie who wouldn’t look at Summer who wondered why Nia wasn’t in class. Each person could miss one Tuesday, Wednesday, and Thursday and still graduate from the program. 

“So,” said the voice and speech instructor. “How did that feel?”

“It’s all dominos to me,” Jonah said.  

“Anyone else?”

“I don’t do yawns,” said Matthew. “I’m unaffected.”

[insert more]

The class was crickets, so the voice and speech instructor called for a water break. Summer didn’t know where to wait for the break to be over. She hated waiting. She wasn’t thirsty, and she didn’t need to pee but she went to the restroom anyway to kill time. By the time she got back to the room, there was the sound of music and the water break had seemingly taken the form of a snack break. Samantha was near the door, cradling a bag of trail mix.

“Hey,” said Samantha, stepping a few paces towards Summer. “Would you like some?” 

“Oh, thanks, but I’m okay.” 

“You sure, it’s really good.”

“Yeah, thanks for offering though.”

Samantha seemed to accept the fact that she was alone in her appreciation of a bite of pumpkin seed mixed with cranberry and a chocolate chunk. She stepped closer to Summer until she was in her ear, with a look that suggested she had someone else’s secret to tell.

“Freddie is like so hot.” 

Summer looked over at him at the opposite side of the room to corroborate the claim. He had a heart-shaped face with a defined jaw and a strong nose, nice bushy eyebrows that framed big eyes. They were downturned eyes, but she realized she didn’t actually know the color. She didn’t need to look at him long to know Samantha was right. He was handsome there at the piano, playing Piano Man. She didn’t know how to respond to Samantha’s covert comment, or why she had said it in the first place. It sounded like she was yearning or wanted to do something about how hot he was. 

“Yeah,” she said. “Are you going to do something about it?” 

“Oh, no,” said Samantha. “He has a girlfriend.”

“Yeah,” said Summer. 

“If a guy has a girlfriend, I’m not attracted to them at all.”

Summer nodded her head, though she didn’t really understand Samantha. If what she had just told her were true, why gossip about his hotness at a whisper at all? 

[insert more]

After class, Summer took the R towards Prince Street. A man with beer on his breath and a Mets hat got in the car and sat down on the seat next to her, even though there were several other empty seats. She stood up when she felt enough time had passed and he wouldn’t get offended. 

[insert more]