---
title: "Levi XV"
author: "Elizabeth Kolling"
date: "2025-11-09T11:16:00"
categories: [Levi]
description: " "
---

(End of summer, before senior year)

“You know those trees that have a split top?” 

“Uh, no.”

“Well, I’m like a tree with a split top.”

“Okay,” said Levi. “How do you mean?”

“I mean, fuck it. I’ll apply. I’ll move across the country for her.”

“Who?”

“The girl I met on the service trip.”

“Oh, right."

"She's from New York. Grew up on Park Ave."

"I forgot to ask how—”

“Go on, ask away.”

“How was Ghana?” 

“It was good. Really good.” 

“Tell me about it.”

“I will. I will, but I want to hear about you. How've you been?”

“Honestly, alright.”

“Honestly, you look depressed.

“Why, what gives, do I smell?”

“It’s the yellow stain.” 

“Where?” 

“There.” 

“Oh, that’s just a little dijon.” 

“The soiled white shirt is screaming depression. Like, don’t hold your breath. This guy has it.”

“Come to think of it, I have been living in my bed. Day in, day out.”

“Popping those USSRs or whatever they’re called.” 

“SSRIs, and no. Get me a ham and cheese from Tartine, and I'm good. I don’t mess with those Soviet meds.” 

“You don’t take a little tranquilizer every now and then, no Phenazepam?”

“I don’t believe in it.”

“Like you don’t believe drugs work?”

“I mean, I don’t believe depression's a real thing, if I’m being honest.”

“Hmm, hot take.”

“I mean, I think it’s cause and effect." 

"It's not chicken or egg?"

"Depression’s the effect. The cause comes first." 

"I don't know."

"The cause is what you really want to cure. Medication doesn’t equal cure. It’s like a bandaid on a bullet hole."  

"Did you hear about the mass shooting?" 

"Where?"

"Outer Richmond." 

"Oh, no. When?" 

"Last night. And I was just at Ocean Beach earlier in the afternoon. Then boom. Sun sets. Six dead. The shooter shot himself. But he's stable." 

"Dang." 

"What if it's like spackle on a dry wall." 

"I guess, maybe, but you can definitely see where the hole was." 

“Okay, now I’m getting depressed because of this conversation,” said Ethan. “So, Samantha. Do you think she wants to see me?” 

“Wait, so back to the girl. What about—”

“Samantha and I, we’re on a break.”

“You broke up.”

“Not technically.” 

"I asked for an open relationship when I got there, and she was pissed."

"Are you serious?"

“I missed her, and this girl reminded me of her. The girl from New York. Have you seen her?”

“You haven’t shown me a picture.”

“Samantha, I mean.”

“Uh, not really.”

“Not really? You have or you haven't."

"I have not."

"She’s still mad at me, probably taking it out on you too. Maybe I should text her.”

“I think her phone broke.” 

“What?”

“That’s all I know.” 

“What do you mean her phone broke?”

“That’s all she told me to tell you.”

“She told you to tell me that her phone is broken.”

“That she's unreachable, if you asked about reaching out.” 

“What the fuck, dude. So you have seen her.” 

“Not really. Just at the grocery store. I run into her there, you know. I don’t know. She gave me a script. I said my lines. I’m staying out of it from now on.” 

“Let’s just get out of this house. Get lunch. Go to Dolores.”

"Tartine?"

"No more croissants for you." 

“La Taqueria?”

“Yeah, but first take a shower.”

[insert more]

"So," said Ethan, before biting into his carnitas super. "What are you reading right now?"

"Nothing."

"Nothing?"

"I'm taking a break from books." 

"What are you talking about."

[inseert more]

"She's reading de Beauvoir. I thought she'd be enthralled. All these intellectuals. They'll talk your ear off about anything, but when it's time to walk the walk, all they are is the epitome of hypocrisy."

"I think she should be allowed to agree with the theoretical argument in favor of an open relationship without wanting to be in one." 

"I don't know. She's such a hypocrite." 

"I mean, do you even like her? It doesn't sound like you like her."

"I love her." 

"If you say so." 

"So, are we going to talk about the fact that you're in love with my girlfriend?"

"Is she your girlfriend?"

"She was, and she will be." 