---
title: "Derin Dribben III"
author: "Elizabeth Kolling"
date: "2025-09-20T11:25:00"
categories: [Derin Dribben]
description: " "
---

“I think one thing we’re all dying to know is who is the gentleman methamphetamine user? All of the characters appear to transcend spheres of social influence. We learn that Laura and Catherine, for instance, grew up together. They’re now leading separate lives, though interconnected, on opposite coasts. Sara is living in San Francisco, which parallels Max’s experience in New York. Samantha finds herself going to school on the east coast, crossing paths with Max. She ends up in acting class with Summer and Freddie. Not to speak for everyone in this room, but I think we, as readers walk away with the feeling that Samantha is Red Bird, or at least becomes Red Bird. But it doesn’t seem to make sense given the current geography. We don’t necessarily see that return to California, so to speak. It seems implied, but, pardon, back to the point of the question. It’s really Ethan and Levi who are harder to place. I guess my question is, is Ethan the gentleman methamphetamine user, or is Levi? Or is Buck Wilde neither?”

Derin Dribben just sat there, with his forearms on his thighs, head bowed, holding the neck in his hand. The uninspired wrist was such that the head of the microphone faced hell straight on. So this is hell, he wondered, nodding along, and part of the job. When the woman with the other microphone took a breather from all of these jumbled-together words, he looked up and out for the eyes of his agent who returned a pleading smile. Please God be nice, thought the agent, sitting in the far back seat, anxious, against the window. 

“You know,” said Derin Dribben. “It’s all up to you.”

“It’s all up to me?”

“It’s up to the reader to decide the fates of these characters and how they’re all connected. If I tell you, then this turns into something formulaic, there is no mystery, and where is the fun in that? Reading is, and should be, like calculus. You know calculus?”

“Yes, I took calculus, as everyone here, I’m sure.”

“AB, BC, multivariable?”

“Uh,” she said, nervously laughing and looking out at the crowd for a lifeline. “I can’t remember, quite honestly.”

“Well, these things are variable. It’s my belief that the duty of the reader is to read. What comes with that is interpretation, taking the first and second and third derivative of a thought or way of phrasing, over and over again, until the subtext is understood. And it’s subjective. I’ll set up the squiggly thing (the integral), but it’s not my job or desire to solve these problems for you.”