---
title: "Herb"
author: "Elizabeth Kolling"
date: "2025-10-18T11:20:00"
categories: [Herb]
description: " "
---

[insert more]

It wasn’t that Herb didn’t like asking for anything. He’d ask them anything, and like it. The way their eyes searched the recesses of their insular, academic minds for some common sense turned him on, and he was old and celibate enough to not care about offending anyone. The cute and petite, hairily under-armed, 20-something year-olds who took the orders and made the lattes and warmed the cardamom buns and weaved the aisles to serve him his drip would answer politely and smile, only throwing him stones. They’d brush off the unsavory undertones, and he would spit back the first sip.

“Hold on,” he’d say. “This is too sweet.”  

Herb should have stopped asking for honey in his coffee years ago, because the young women who came and went were all the same. The cute and petite, hairily under-armed 20-something year-olds studying politics and philosophy and history and comparative literature who he’d flirt with at every opportunity had heavy hands and wouldn’t know *a little honey* if it fell out of a hive onto their dense heads. They weren’t dumb. They just didn’t have a palette or know moderation when it came to food and wine. In this way, he thought, they weren't all that different, and it finally clicked with him one Saturday in October when he opened his cupboard to check his sea salt and pepper reserves. He'd have to pop into the market as well as the liqour store later. 

[insert more]

He opened the lower cabinet, where the mouse trap was there to antagonize him, and reached for the black t-shirt bag. The plastic bag was made of high-density polyethylene, from the liquor store around the corner. He’d go later that day to pick up a bottle of vermouth before meeting his older brother who was a hoarder living in the East Village. 

[insert more]

“Honey?” 

“No, Honey.” 

“No honey today? So unlike you, Herb.”

“I’m a changed man,” he said to Frieda. 

"Don't change," she said. "Come as you are." 

Herb left a dollar tip, even though he couldn't afford it, and turned towards the aisle, with a bit of blush along his cheekbones. He chose the table with the best view of her and unclipped his black leather briefcase, reaching for a jar of raw honey. 

[insert more]
