---
title: "Levi VIII"
author: "Elizabeth Kolling"
date: "2025-07-07T17:00:00"
categories: 
description: " "
---


“Are you okay to talk about this chapter?”

“Yeah, why wouldn’t I be?”

“I thought maybe—”

“Are you okay?”

“Yeah,” Levi said. “Thanks for asking.”

“Totally,” said Ethan, visibly shaken. “Let’s get into it.” 

“So, to start, I thought it was interesting that he used the word chapel instead of church.”

“He used church in the other chapter?”

“Yeah, when he unknowingly walks into the black church.” 

“Okay, so what’s the significance?”

“Well, he assigns ownership or association, in a way.”

“How?”

“By using the possessive, saying ‘Whaleman’s Chapel.”

“So, what’s a whaleman’s chapel?”

“Right,” said Levi. “So I think he doesn’t really mean church when he says chapel. He uses chapel, because he’s alluding to a funeral home, even thought it appears to be just a regular Sunday sermon.” 

“So funerals happen in chapels, not churches?”

“I think so.”

“And he uses the word chapel so that he can get into talking about death?” 

“Yeah, that’s where it leads, I believe.”

“Sly guy, this Ishmael.”

“Or Melville.”

“Or whoever he is,” said Ethan. “Do you think he’s writing himself into it?”

“Like is Ishmael really Melville?”

“Yeah, I mean the names sound the same.” 