---
title: "Samantha II"
author: "Elizabeth Kolling"
date: "2025-07-09T07:25:00"
categories: 
description: " "
---

Samantha only ever played supporting roles, secondary characters, in the lives of other people. 

Part of this was because the girl who always played the lead in the fall productions wanted to be an actress as a career and happened to be the daughter of a big Hollywood producer who doubled as a donor to the private school. There was a building named after her, and the drama teacher thought she may have a second chance at hitting the big screen if she did something for them. She even told her she was talented, which wasn’t a requirement where they came from. She (and Ethan and Levi and all) walked past the plaque on their way to Western Philosophy and couldn’t help but feel everything about the world was rigged, out of reach, like looking up in the Sistine chapel. She was the pointer finger, strong, proffering with purpose and good intention, and her dreams were a collapsed wrist, indifferent, or like someone who didn't know what to do with another's want of connection, Platonic, creating distance. 

They had been assigned *Symposium* as summer reading, due on the first day of class. But it was the time of cherry plums, and August was far away.  