---
title: "Don IV"
author: "Elizabeth Kolling"
date: "2025-08-07T09:48:00"
categories: [Don]
description: " "
---



"I’m sorry if dinner’s cold."

"And a little bit burnt?"

"I tried, tried to time it."

"No, I'm just...it's timing, you know, we had the pears to process, it's a process, oh, and the pomegranates."

"That's the hardest part."

"Carving the pomegranate? Ah, 70% carcass." 

"Hah, no," said Don. "Timing, I mean, is the hardest part."

"Have you ever written a letter you’ve not sent?"

"Yes."

"You have?"

"Yes, I have."

"Who to?"

"Oh, uh, no one, really."

"So, you wrote an unsent letter to no one really?"

"Mmm."

"Okay."

"Maybe we can talk about something else? Maybe those mining skills of yours, Ms. Pomegranate..."

"Mrs."

"Shoot, sorry, Laura."

"Life's shorter than we tell ourselves. Why don’t you send it?"

"I can't—"

"Tell her how you feel?"

"It just wouldn’t be possible."

"I think possibility is all we have, and that's life. There’s a fine line between what is and what isn’t.

"Isn't that distinction what it is that matters?"

Don had written a letter (more than one) to the love of his life, but Levi's mother could never read it.

 