---
title: "I.C.E. Coffee"
author: "Elizabeth Kolling"
date: "2025-07-31T04:48:00"
description: " "
---

Dear —, 

“Keep your cool,” a wise woman once said…

…It was Thursday work from home, and I had decided to take my lunch break at Birch Coffee (on 88th between 3rd and Lexington) before afternoon meetings—for a bit of calmness and reading.

There was high demand at the late morning hour, so I stood in line while looking innocently out the window. I saw that both picnic tables were occupied, but there was still enough space at the one with the woman. There were two men and another woman who appeared to be the girlfriend (and much more) of one of them, who was just about to leave, sitting at the picnic table on the right. Everyone had computers, so much in common, and some ice left over as Rayn greeted me at the counter. She asked for my order.

[Dialogue is not direct quotation]

“Is it…Liz?”

“Haha, good memory!" I said. "Technically it’s Elizabeth, but yes, you can put down Liz. It’s easier.”

I saw her proceed to write down Elizabeth, and I felt bad for how much longer than Liz the name was. 

“What’s your name?”

"Rayn," she said. 

“Ah, Rain?! One of my middle names is Rain.”

“Oo wow, I love that!”

“R-A-I-N?”

“R-A-Y-N, actually.”

“Oo I love that spelling,” I said. “What does it mean?”

“Heaven’s door, I think.”

I opened up Moby Dick and handed her the punch card (not quite an accurate bookmark; I stick it randomly somewhere towards the ending, which I haven't reached yet).

“Oo,” said Rayn. “Next one’s on us.”

“Oo, exciting,” I said, wondering whether that’s a good or bad thing, since it means I’ve been drinking a good amount of coffee lately. Going to Birch, I guess, has become part of my routine—I go there whenever I want to read a chapter. 

[Which reminds me] I said:

“Do you mind if I sit?” 

The woman at the picnic table gave me no answer (“NA”), so I just shrugged my shoulders and looked around to see if anyone else had witnessed the embarrassing Q&NA. No one cared what I was doing, of course. I sat down and started The Ship. I read for a few minutes and then turned to see if my cappucino was ready. Through the window I could see a little teacup and saucer on the counter, so I got up ad went back inside retrieve it. I thanked the male barista who had made it and said hi to Alicia who greeted me with an enthusiasm that felt sincere. I added a dollop of honey that was supposed to be an elegant drizzle around the art. I walked back in a balancing act to picnic table. I sipped once for some strength and then mixed in the sweetness. Every time, I seem to sing "You're So Vain" to myself. I think everything is set just right, with "clouds in my coffee," and my palm wrapped around something warm (It makes me feel warm inside. And with a good book to read? How lucky am I?). 

So, I sat there, sipping, reading, blissfully unawares, and all of a sudden the woman across the table started screaming. More specifically, she started yelling at the men at the other table. 

“Jesus, can you stop talking so loudly!”

“We’re outside,” one of them said. “We’re in public.” 

“In America, people don’t take calls on speaker phone.”

At this point, I had looked up from the page and turned straight ahead after making one quick glance at the woman who had erupted in the middle of everyone's morning coffee. Her AirPods were out, and she was ugly. With those big, round eyes (blue) and that alopecia, she kind of resembled Gollum. But call her Karen.

“We *are* American,” said the man.

The woman didn't respond. She looked at me, because she must've thought I was on her side. She gave a gross sigh that sounded like she had mucus in her throat that she wanted out of there.

“Uccccgh.”

She rolled her big, round eyes (blue) and put her AirPods in. She returned to her computer (equilibrium) again, hunched over.

After a few deafening minutes, the men got up from the tables but left their computers. I tried to return to Moby Dick, but I couldn’t get over what had just occurred. I also didn’t entirely know what had just occurred. I had been reading, after all, and everything becomes white noise when I am reading. I didn’t even register that the man was on the phone behind me or talking loudly in the first place. I thought maybe I had heard some Farsi. Maybe the man had said something that upset her. So I said hi to her.

“Hi,” I said to her. “I just wanted to ask what it was that they were talking about?”

“Oh, I don't know," she said. 

"Did they say something that upset you?"

"No, they were just on the phone talking super loudly, on *speaker phone*.”

“Huh, I mean, it *is* a public space, so they’re allowed to do that, no?”

“No, they’re not. They’re just these douchey guys. Look at them. They clearly don’t live here.”

I turned to look where she was nodding her eyes towards. The two men were on the sidewalk. One was on the phone. They were well dressed. They had a sort of swagger. I would call them tall, dark, handsome. I didn't think this was evidence against them, and I turned back to face the woman.

“Sorry, but I think that’s kind of judgmental.”

“They’re talking loudly on the phone in some other language.”

“Asking them to speak more quietly is one thing. Especially if you’re nice about it. But it’s upsetting to me and I'm sure them that in tandem with that ask you accuse them of not being from America.”

“They sure don’t look or sound like it.”

“Seriously, lady, are you racist? Xenophobic? It’s not okay.”

“You don’t take a professional work call in public and put it on speaker phone. I’m working here too, and it’s very disruptive.”

“If you wanted peace and quiet, you maybe shouldn’t have opted for a hot spot at a coffee shop or a picnic table on a busy street, and—”

“I don’t know what kind of Gen Z speech you're about to give me, but—”

“Uh, I don’t identify with Gen Z, but thank you.”

“You’re clearly Gen Z.”

“Okay, Karen.”

“Karen! Uh! See! You are Gen Z.”

“Respectfully, you're a Karen, and I think you’re crazy.”

“Are *you* even from here?”

“No, I'm not from here."

"Then you should leave."

"I really hope you find peace. It appears to me that you are deeply troubled or going through something. So, I'm sorry for you, and I really hope you find peace with yourself.”

That was my last word. I put my book in my bag and carried my empty cup inside. By the time I placed the saucer on the counter (where Alicia and the male barista were debriefing about something), my composure cracked. I suddenly felt myself physically shaken and the welling start as I tried to warn the staff about this woman and tell them what had just happened out there.

“I’m sorry,” I said. “I don’t know why I’m crying. It’s just...it was really upsetting to me...it's really upsetting to me, especially now.”

The male barista (whose name I don’t know) leaned towards the window to look out at the woman whow was still there, hunched over her computer.

“I don’t recognize her,” he said. “I don’t even think she’s drinking our coffee.”

“I don’t know if she’s a regular, but I just thought you should know.”

“Thank you, thank you for telling us.”

“We’ll talk to the two men. They're regulars...and ask them about it.”

“I tried to talk to her about it, but I don’t know what this woman’s deal is. I couldn’t get through to her. I don’t know, she may have mental health issues. Either that or she’s just entitled and very rude.

“Definitely racist,” said the male barista.
 
“Classic Upper East Side,” said Alicia.

I had learned Alicia’s name this past Saturday, and I’d asked her whether she was writing that other (early) morning when I saw her with her computer at one of the picnic tables. She smiled and laughed, before clarifying. 

“Oh, no, that was just me working on the schedule,” she had said. “I’m the manager.”

I was not expecting the turn of events today. I tried to stick up for what I thought was right, and ultimately I was pretty floored by the interaction. I must admit, I was a little sassy with some of my remarks and some definitely weren't as diplomatic as they could have been. But I tried. I don’t try to intellectualize why I cry sometimes. Hormones, maybe? I’ve always been a sensitive person. It’s my superpower and kryptonite, and has been since I was a little girl. Beyond this, there are also a lot of things going on in my life which I haven’t had any more tears for recently and maybe these tears today were those manifesting. Sometimes I’m like the New York sky in summer, in need of an exhale after the unfortunate weather we’ve been having. 

Sitting now again at my desk and monitor, I look out the window and see it’s raining hard outside. There’s also a spotted lantern fly holding onto the screen, and I’ve stomped on only a few over the years. They always manage to fly free at the last moment, prior to toes down. Calm before the storm? Maybe the storm is before the calm. Maybe the woman was going through something and taking it out on others is her cry for help. Maybe she's just an ugly person who lacks humanity. All I know is...if you can’t keep your cool while drinking a seven-dollar cold brew, then I can’t help you. 

Love, 

Elizabeth Kolling
