---
title: "Levi VII"
author: "Elizabeth Kolling"
date: "2025-07-06T14:05:00"
categories: 
description: " "
---

“Personally, I’m a bit disappointed.” 

“Mmm.”

“I thought we were going to see a few knocked-off hats.”

“Ishmael can talk a big game.”

“But what it comes down to is all walk.”

“So, he takes a walk around New Bedford—”

“Which he does refer to as a civilized town.”

“That’s nonetheless filled with savages.”

“It felt icky reading some parts.”

“Yeah, I felt racist reading it.”

“Was Melville a racist dude?”

“I don’t know enough about him.”
“Let’s see, maybe it says in the introduction.” 

“I didn’t actually read it.”

“The introduction?”

“Yeah, is that bad?”

“I mean, neither did I.”

“I didn’t want to ruin the experience.”

“Fresh eyes are the best eyes in my opinion.”

“It’s the same with Instagram for me.” 

“Huh?” Levi said. 

“I don’t want to cheapen getting to know a person.” 

“What do you mean?”

“Like I want to know you from how you are when I’m in front of you, not from what you appear to be in a box on my screen.”

“I couldn’t find anything about him in the Intro.”

“Okay, let’s move to the internet.”

“Wikipedia works wonders.”

“Okay, so he was born in New York, NY on August 1, 1819.”

“What was going on then?”

“Definitely slavery.”

“But it was on its way out, especially in New York.”

“He was still probably racist. It was ingrained, right, but he could’ve not been.”

“I hate to speculate.”

“You’re right. Let’s just go back to the primary source document.”’

“So, he’s definitely obsessed with this idea of the civilized and uncivilized.” 

“Right, and he’s making a distinction between the one and the other.” 

“Moluccas versus Puritans, for instance, and Mediterranean mariners versus—”

“Natives versus New Englanders.”

“The difference seems to be religion.” 

“There’s this cleansing, remember the one chapter that referred to how a Christian person washes their face.” 

“Counterpane?”

“The entire soap industry was rooted in the ideals driving colonization, justifying imperialism, and racism, right?”

“Yeah.”

“So not to back-track, but I do think that’s why he included it in the counterpane chapter.”

“He represents the other as not being religious, here, he refers to their ‘unholy flesh.’”

“Can Ishmael relate?”

“I mean, the scene from the last chapter, where the supernatural hand holds his own, it’s unclear whether that was dream or reality.”

“Right, so it’s possible he too was once a foreigner or a native who then assimilated.” 

“Perhaps.”

“I still feel like Ishmael is like the whitest dude possible, some richy rich sort of figure who maybe fell from grace.” 

“Everything is a possibility.” 