---
title: "Samantha VIII"
author: "Elizabeth Kolling"
date: "2025-09-06T12:18:00"
categories: [Samantha]
description: " "
---


“When you see a trail of ants on the windowsill,” said Levi. “Do you spray them?”

“I do.”

“What if that’s their way towards worship?”

Samantha felt guilty and bad about doing it, but not enough to stop killing them in early September. The kitchen was infested, but there was no final thing she could do about this devotion. The reality of her life was hitting her as she stared longingly out the north-east facing window, doing the dishes after making breakfast for him before the work day.

"Hey, hija." 

She turned to him, lacing up his boots at the door.

"Yeah, Papá?"

"Abue, she isn't doing well. I'll have to leave tomorrow."

"How long are you gone?"

"Only a week this time, promise, pececita." 

Samantha had always been a good swimmer and loved the water, so he called her his little fish (She would wake up early on school days, just so she could sit with him (a cup of tea in her hand) as he ate his eggs and potatoes. Without her, she knew he'd skip breakfast and wait for a scrappy lunch in the orchard (on the days he was feeling poor). Every blue harvest moon, he and the other workers would take lunch in the parking lot at the taqueria in town or on the side of the road by the taco truck. He liked the chicken mole and carnitas, because it reminded him of his mother who still lived in Michoacán. Abuelita was getting older, and he was always due for a visit soon it seemed. Because of this, Samantha lived in a constant state of immminent abandon and spent a lot of time home alone with her younger brother. Papá would kiss them on the forehead, leave a letter on the kitchen table, and slip out into the night after the wor day. She would look after her younger brother (walk him to school, back home afterwards, until he was old enough to walk alone, and cook dinner) for weeks, sometimes months at a time. Every time, she never knew exactly when he was ever coming back). 
