---
title: "Plane Ride"
author: "Elizabeth Kolling"
date: "2025-06-15"
description: " "
---


Dear —, 

I have my traditions—rites of reflection. I walk Division Street each Sunday and turn left on Orchard, with the same destination in mind: Son Del North. The one and only burrito worth condsidering in New York City. I get the carne asada (caramelized onions, pinto beans, cheese, a grilled tortilla, comes with salsa verde).

On a sunny day, I'd have taken my bliss to Elizabeth Street Garden for eating followed by reading. However, today was drizzly and I didn't end up getting a burrito. Here's why: From Stanton Street, I could see a crowd out front, blocking the sidewalk and pouring out into the middle of the street. I walked up to a woman who had a burrito in her hand with some bites missing and asked what the situation was.

"How long for a burrito, and why so many people?" 

It took a few attempts to hear her, but she told me that today was the Pedro Pascal lookalike contest. 

"You know, the actor." 

"Oh, okay, thanks," I said, not sure what that had to do with Son Del North or what it meant for my burrito prospects. I weaved further into the compact crowd, without seeing much resemblance, and approached a man in a white uniform. My guess was that he worked for Son Del North, which has a white facade, but another man got to him first. He asked the question that I would've asked:

"How do I order a burrito?" 

The man in white looked down at the sidewalk to think for a second. 

"Uh, we'll be open in 20 minutes." 

I was confused; How could the kitchen be closed with all these people around eating burritos. They had to have ordered them, some way, somehow, which meant the place had to have been open and operating. Was it all of a sudden closed for some reason? I didn't want to ask questions or get to the bottom of it. As people, we must pick our battles and so I walked on. I did look back though, before I reached E Houston Street. I saw that the man who had interjected was walking in the same direction. Both of us, at a (temporary) loss. No burrito today, but that's okay. I had some delicuous Borscht, and potato and cheese dumplings, in Ukrainian Village. 

Afterwards, I planned to take the yellow line home. However, there was caution tape tied to the entrance and the posted sign said the R/W trains weren't servicing the 8th St-NYU station, same as the past few weekends. So, I walked on towards West 4th (along Greenwich Avenue), which is where a full circle moment came into play. 

As I walked, I sent a text inquiring about dinner. I offered to pick up some slices from Mama's Too (which specializes in the square, but is my favorite for its triangular slice with pepperoni, vodka sauce, parmesan and basil (I believe)). Point is, this was a time-sensitive text. I was almsot at 6th Ave, after all, and I could either (1) go straight to the nearby subway or (2) presume every person wants pizza for dinner and go straight for the slices. I don't like to presume, so I started to slow my roll. I walked at a snail's pace, stopping a few times to loiter in front of quiet residences. I stopped outside *Goods for the Study* and looked into the store through the window. I saw the pens and the notebooks they sold, which looked nice. I thought maybe I could go in and buy some more time without actually buying anything while I waited for this special person to respond to my text. 

Then, all of a sudden, relief. A ding. Pizza, as it were. I started to respond at the spot, and I turned left to face the street (for some reason). That's when I saw the face of a man who I recognized. This man looked too familiar for me not to stop him with a *hey*. 

"Hi," he said. 

"I think we were..." I said.

"I'm really in a rush," he said. 

"Can I walk with you?"

He didn't say yes but he didn't say no. He sort of just shrugged, as if to say *okay that should be fine.*

So, I walked with him and tried to talk to him as if he were just a person (which I am convinced of, of course).

"A few years ago, I was on a plane ride to San Francisco with you," I said.

"Woah, really? I haven't been there in years. When was that?"

"2018? 2019? 2021? I have no clue," I said.

"Huh."

"We were on the same plane ride, and I regretted not slipping you a piece of paper with my friend's name on it. She's a singer-songwriter, and I wanted to give her a plug."

At this point, we were both stopped just before 6th Avenue, and he had turned to face me.

"On Spotify? What's her name?"

"Yeah, Spotify," I said as he pulled out his phone. "Rebecca McCartney."

He typed in her name, tapped on her top song, *Close to Me*, and it played as he held out his phone. 

"Her?"

"Yes, her."

"What songs?"

I recommended my favorites as he scrolled through her discography.

"They're all good, give her a listen," I said, and we parted ways.

The man on the street was Jack Antonoff, and I've been thinking about this interaction for the past few hours since it happened. The Universe kind of, sort of, gives you little gifts like these. For years since it happened, I've thought back on the flight to SFO when I saw him sitting in first class and recognized him then only to fail in telling him about my friend. I felt like I had failed her or lost her a career opportunity. I want for her to succeed like he has in the music industry, and I gave myself a hard time for not having the courage then to slip him a piece of paper with a note. And then today, years later, at about 5:11 pm (phone call to Rebecca time stamp), becuase of timing and a semi-broken subway system, I crossed paths with this music producer again. I was able to tell him about her, as I had originally intended. That feels good. 

It's also a wonder what leaves your mind when you meet a person who has been so successful at the thing that you or someone you know aspires to. The mystique takes over. For me, the word *flight* fell away from my vocabulary, and I ended up saying *plane ride* at least twice during the conversation. I thought that was funny. 



Love, 

Elizabeth Kolling
