---
title: "Alexis III"
author: "Elizabeth Kolling"
date: "2025-10-19T12:41:00"
categories: [Alexis]
description: " "
---


Alexis woke up on Sunday morning trying to forget about Saturday night, and not feel so down. Unfortunately, she was ill at ease and remembered everything. She replayed the scene, as she tore off a crumb-size corner and stared into the eyes of her black current scone. She picked off the sugar crystals and considered the cut of her diamond ring. She was 29 and planning her wedding (destination, somewhere tropical). All she needed now was someone blonde, six feet or taller with broad shoulders, from Connecticut or a functioning family, to love her and who wouldn't make her go crazy like the last guy who still liked her pictures but never cared enough to plan something or ever see her in person. Her five-year plan was to [retire early and [insert more]]. She took a sip and then a picture of the oat milk latte, with her manicured hand holding up a big chunk of berry crumbly. She captioned it *Sunday Mornings and Current Scones Calling My Name* with *#HappinessIs* as a hashtag, tagged the designer of the rings on her fingers, and posted it to her story. This made her feel a little bit better, (and, plus, she got 50K for every post as part of the brand deal) but last night was still front and center. 

[insert more]

“So,” said the tall and light-haired, handsome man sitting a practical mile across from her. He may as well have been marathons away from her as he chewed his medium-rare, dry-aged steak with his mouth wide open and buck teeth showing. “What do you do for fun?” 

“For fun, uh—” 

“Yeah,” he said, raising his fist to his mouth and closing his eyes as if he were about to cough or choke or burp or die of heartburn before swallowing. “What’s a typical Saturday for you?”

“A typical Saturday,” said Alexis as she tried not to think about her checklist, the boxes with exes in them, and the evolving tally in her head. His fourth red flag was that he was a talker, and it took him until the entree to ask her a question. His third was that he chewed with his mouth open, which wouldn’t have been an issue had he not pointed out her elbow on the table during the hors d’oeuvres and remarked that his pet peeve was people who had no class. She didn’t even want to think about the first or second, which she had already managed to compartmentalize away. Chemistry was a ways away as she swore a speck of borderline rareness had just flicked onto the candlelit white linen tablecloth, and she was trying to locate it. Something was amiss, just like last Saturday. There was no spark, but that wasn't a dealbreaker (As her mother had told her: "Just look at me and your father...a lighted candle isn't forever, or even always from the start."). 

“I mean,” said the tall and light-haired, handsome man. “What’d you do today?” 

Alexis didn’t know if she wanted to tell this man what she did today, no matter how tall and light-haired and handsome. She had a feeling he wouldn’t understand how or why she walked 7th Avenue, starting from Church Street towards West Broadway onto Reade temporarily and then Hudson (no, not the river) until she took a right on Grove (since she liked looking at the restaurant with the red facade) to volunteer at the place with the red door.

“A food bank, huh?”

“Yeah, there are a lot of them in the city.”

"So why 14th Street?"

"Well, I'm looking for an apartment around there, and I want to better the neighborhood, so..." 

“They really need people to help hand out food, huh?” 

“Yes.”

“I didn’t know hungry people didn’t have hands,” said the tall and light-haired, handsome man. “But, hey, many hands make light work, right?”

“Have you ever volunteered?”

“Oh, no, never.” 

“Why not?”

“Never been interested. Not a good use of my time.”

“It only takes an hour or two,” Alexis said. 

“Not really worth it. I could be, I don’t know, golfing.” 

“Sorry, you said, hitting around balls?”

“Hah, you’re funny.”

"I wasn't trying to be."

"Hitting balls into holes, by the way. Hard work."

It was official, another hash mark. Alexis would not be sleeping with this guy, and she never wanted to see him again, but she would order the mousse for dessert and she'd check her DMs again when she got home. 