---
title: "Levi XII"
author: "Elizabeth Kolling"
date: "2025-08-20T20:23:00"
categories: [Levi]
description: " "
---


“Where’s Samantha?”

“Oh,” said Ethan. “She has to work.”

“Oh.”

“Yeah, it’s a bummer.”

“She’s doing the evening shift?”

“Uh, yeah.”

“I thought she worked mornings.”

“Uh, she does both.”

“She works mornings and nights?”

“No, I mean she used to do the morning shift, but she switched to evenings a few weeks ago.”

“Oh,” said Levi. “Why?”

“I don’t know.”

“You don’t know?”

“No, I—”

“She’s your girlfriend, dude.”

“I know, of course I know, but it’s none of your business.”

“Sorry I asked.”

“Ice,” said Ethan. “We need ice.”

“We have ice.”

“One bag, but we need more.”

“So what do you want to do? Fill some trays?”

“Oh, my friend, you’re funny, but yeah, no.”

“I’ll go to the store.” 

“Has anyone ever told you how handsome you are?”

“Okay, okay, don’t push your luck, I’m feeling rather testy.”

“Drive slow.”

“Only have one speed.”

“Nothing good comes of over the limit.” 

“Limit? I’ve never heard of her.”

“Just hurry up and get some ice already. At least five.” 

“Five plus the one or four plus the one.”

“I don’t know, dude, just get us some ice.” 

“Anything else?”

“No, uh, actually, yeah, maybe some watermelon and chips.”“Sea salt and vin?”

“Yeah, barbecue too.” 

“Are we barbecuing?”

“Should we?”

“Do we have any real food or just booze?”

“Get whatever you want at the store, okay?”

“I think I will.”