---
title: "Nia"
author: "Elizabeth Kolling"
date: "2025-10-04T12:36:00"
categories: [Nia]
description: " "
---



It was Saturday, and her mother unfortunately wasn’t in jail or the hospital. Nia wished she were, after the past month of torment and what had happened on Wednesday (when she was leaving (about to leave)), but it was no use getting to where either of them needed to go. Jail wasn’t the answer and an introductory acting class wouldn’t save her, but it was a starting point. Her hand held the phone and hovered over those three digits (911 was a sense of hope and false safety, simultaneously something to fear) as she tried talking to her mother like she was a normal person. She was a person, with rights, but none of this was right. Nothing about a 19-year-old navigating the system alone on behalf of a parent was normal, but it had been Nia’s new normal for some time now, and she wasn’t an expert. She couldn’t crack the code or ever get through to anyone (a sympathetic operator), it seemed. HIPAA was the bane of her existence, during the really bad times. When better times were on the verge of worse, she tried talking to her about their options. 

“I’ve lived here thirty-five years,” her mother had said. “I’m not going anywhere.” 

“How are you feeling?”

“I feel like sidewalk.”

"How are you feeling about your medication?"

"A sidewalk has feelings, you know."

“How does a sidewalk feel?”

“Stepped on.” 

“I’m not trying to step on you,” Nia had said. “I love you.”

“I am the goddamn sidewalk and the man at the door is spraying a hose down at me. Your grandfather was one of those men wearing those fancy suits and ties for a wage, standing there, smiling through the sorrow at the strangers who ignored them, and it hurt. No man is meant to stand. Promise me, Nia. Promise you’ll walk or run but never stand idle. We’re the mighty stream going towards the ocean but we’re not our natural state. We’re not water anymore. Every sterile shot they shoot at us in those white-walled rooms is bleach. It’s bleach they’re administering. Those needles have made me what I am. I’m a bottle of bleach! I can smell it, the scent of bleach. Ever present in my veins. My blood is pure. Pure poison! They poisoned me. They’re poisoning me.”

“Who, mom, who is poisoning you?”

“Those cops down there, in their cop cars. I know their route, the constant circling. I know the hour, but I can’t pin down the exact minute. They’re fast, in and out, and then gone in a flash. I hear them climbing the fire escape. They’re clumsy on the approach. But then it’s a silent entry. I hear no creak, in through the window and over the floorboards. They fill the whole apartment with aerosols. I can’t hold my breath forever. I open the windows to get it all out. And they see it as their chance. They come in all over again. Close your mouth, Nia! You’re inhaling more of it that way! Don’t be so goddamn careless.” 

Nia looked her mom in the eyes, those wide eyes, so pale brown and weak with the lack of sleep. Her mother was wearing a medical-grade face mask. Shoot, Nia thought, remembering they were nearing out. She had forgotten to stop at the corner store before coming home the night before. She would pick up another box after class this evening. 

“Mom, I love you. I’m going to go to the store, to get you more masks.”

“They’re poisoning you too!”

“I’ll go get us more masks so we don’t have to breathe the bad air.” 

“Get us more than one box this time.” 

“Okay, I will.” 

[insert more] 

She just got hurt, trying to talk sanity into an insane person. So, she dissociated and let go of the memory of her. The mother she remembered. She remembered what the nice woman in Los Angeles had said to her over the screen, during one of the free support sessions for family members (while she was away at college). To be the best caretaker to your loved one, first you need to take care of yourself. So, Nia invested what she could in herself (she signed up for acting class). 

[insert more]

“Where do you think you’re going?”

“I told you,” Nia said. “I have class.”

“There’s a group of cops out there, and they’re double agents,” said her mother. “They’re trafficking, they’re looking at us through the windows from down there.”

“I talked to them, they understood our situation, they’re nice people, they won’t hurt us.”

“They’re going to get you, if you walk out that door.”

“Please, I have to get to class.”

“I can’t let you.” 

Nia rushed towards the door (in an anxious attempt to escape), and her mother descended. 

[insert more about the struggle] 

(She grabs hold and tackles Nia. Her mother has pinned her down to the floorboards, which have been creaking at the pitch of a scream. As her mother catches her breath, Nia musters strength for a few minutes. Then, tries to push her mother off of her. Her mother is strong, hardly budges as her nails dig deeper into Nia’s arms the more she struggles.) 

“Please, Mom! You’re hurting me.” 

These words seemed to send a shock through the nervous system of her mother, who let go. 

“Who are you?” 

“I’m your daughter,” she said, through tears. “Nia.” 

“Why are you crying?” 

“Nothing.”

Her mother walked over to the window, and Nia rose slowly. 

“You know you can talk to me about anything, my sweet girl.” 

“I know,” Nia said on a sniffle as she pressed her knuckles into her medial canthus and looked around for her phone. Her mother had thrown it across the room, and now there was a crack down the center of the screen. The time was 5:47 pm. The 29 minutes that it took to take the 2 and transfer to the 4 at Franklin Avenue couldn’t get her there in 13 minutes or less. There were delays, also. She wouldn’t make it, and she didn’t have it in her anymore. Still, she turned towards the door and turned the knob.

“Where are you going?”

“Going to the grocery store. Would you like anything?”

“You know what I like. Surprise me.”

“I will,” said Nia. “I love you.” 

“I love you more than life itself.” 

Nia didn’t have much to spend at the grocery store. She hadn’t had the intention of going, but she lied on the fly. She didn’t feel safe saying that all she wanted was some fresh air, to take a walk.  

[insert more]

She read the lines of her monologue in her head, even though she already knew them by heart.