---
title: "Summer IX"
author: "Elizabeth Kolling"
date: "2025-09-27T12:11:00"
categories: [Summer]
description: " "
---



Summer awoke to a text from Philip who thought maybe she must be serious this time since there was now only an unclaimed pillow next to him to greet him *good morning*.

“Hey, can we talk?”

Summer didn’t know if she wanted to talk so soon. She needed time to think things through. She thought about him for the 19 minutes it took her to boil the water and whisk the matcha and pour in the almond milk, and longer. She stirred the froth with a tiny wooden spoon, which she licked and set on the sill, noting how she preferred the feel of silver against her tongue instead. She told herself to remember it instead of leaving it there like last time. She was already on thin ice around Kim, who was so mean for some reason. She thought she maybe understood why. But still, she thought it was unfair of her to be always on her back about everything just because nothing in her life was taut. Kim had made her choices. She had slacked off at every turn, because she knew she could afford to, and now she was unemployed and living mercilessly in one of the most expensive neighborhoods in New York on their parents’ dime. They were not at all the same despite coming from the same place, which always fascinated her. 

[insert more]

She put her feet up and looked out the east facing window (which looked directly down at the garden), considering nurture versus nature. She didn’t know where she stood not the subject, and she remembered she had a long way to go after organic chemistry. She tried not to think. She just focused on the rim of the turquoise ceramic and sipped slowly, thinking ultimately about how her parents would probably disown her and rescind the terms of her trust fund if they only knew what she’d spent it on and where she’d been on Tuesday, Wednesday, and Thursday of this past week.  

[insert more]

There was yoga going on down there in the garden, and she thought of going next Saturday. She’d have to ask Kim to borrow her mat, and she though about how her parents liked Philip. They had told her this, even though they didn't really know him. They’d only met him once last spring. 

[insert more]

Once was enough for the two of them; they themselves had met when they’d moved to NYU for college, so they now had this undying belief that a person should only be in one relationship for the rest of their life. Once you decide once, that’s that. Summer thought how her parents were hypocrites, since they were both pre-med at the time they met, but eventually only her mother stuck with it. Her dad couldn’t pass the MCAT though he did get a near perfect score on the LSAT without even studying, so he went to law school. They did long distance while she was in residency at UCSF, and he was in Cambridge. They wrote each other letters, and she used to sneak into her parent's room to hide under the bed where the treasure chest was and read through them when she was little. 

[insert more]

Her mother acted like it annoyed her how he’d never say the word Harvard at the start of a story that he’d tell strangers at a dinner party, but Summer knew how she really felt. Her mother liked her father’s modesty. He was never one to flash his wealth, which is something Kim had never seemed to inherit. Kim wasn’t the golden daughter, and expectations weren’t as high for her as they were for Summer. They expected her to become a doctor, and her mother most of all wanted her to choose the path of medicine. I see you as a neurosurgeon, she had always said, though Summer never saw herself this way wholeheartedly. She watched the effect of the wind on the ivy that grew on the northern wall of the garden. It moved like whitecaps off the Atlantic shore, one big green wave or ripple. The green in her mug was nearly gone, and it was time to face her phone. All those unanswered questions weighed on her. 

“Sure,” she texted back, which she regretted for sounding bitter.

“Are you free today? I’m free all day.”

“I have something this morning, but I’m free after.” 

“Shoot, I actually have a lunch in the early afternoon. What’s your thing this morning?”

“Going to a bookstore.”

“Oh, then can I come?”

Summer didn’t have any real issue with him coming, but she was on the fence about it. It took her seven minutes to say *okay, I’ll be getting there at 10*. 

Philip checked his watch where he was, which was a nine minute walk to Kim’s (where Summer was now staying), and it was 9:30 am. 

“Okay, I’ll meet you there at 10. Wait, where do I meet you?” 

Summer thought for a moment of sending him the wrong name of the place or a random location, but ultimately decided against it in the four minutes that it took her to pick out an orange Ralph Lauren crewneck sweater.

“It’s the Theatre Bookstore.”

“The one on 37th, between sixth and seventh?”

“Yeah, there’s only one.”  

“Okay, I can be there in 50.” 

Summer thumbs-upped the message, got dressed, and left. 

She walked the north side of the street (quiet on a Saturday morning) to Prince Street, where there was an N in eight minutes and a man with a beat-up red suitcase sitting on the platform bench. She tried to put off the thought that there was an explosive in it, and instead think of the kind of mic drop of a monologue she would look for, for next Thursday. She walked in at 9:55 am, and was pleased to see Jonah there. He was looking at monologues for young men. 

“Hey,” said Summer to no answer.

“Oh God,” he said. “You scared me.” 

“I’ve been told before I have that effect.” 

“Huh?”

“Nevermind,” she said. “Find anything good yet?”

“No, all of these monologues are so depressing.” 

“Hmm, have you checked the comedies?” 

“I don’t want anything too cheesy either.” 

“Oh.”

“It’s a delicate balance between heavy and light-hearted.”

“Totally, I agree.” 