---
title: "Book of Romans"
author: "Elizabeth Kolling"
date: "2025-09-14T22:38:00"
description: " "
---

Dear —, 

[insert more]

I wake up, make breakfast, go to Birch.

There’s a new barista behind the register.

I give him my order, hand him my punch card.

Regular milk is good, 6oz, for here, please.

"Oh, looks like this one's on us," he says. 

Do I deserve it?

"Would you like to keep it, for the memories?"

I say, no, I'm okay.

Hi, to Ariel who smiles.

[insert more]

The Lion of God has a break.

He sits across from me, and sets his timer to sixteen minutes.

The countdown has started as I look up from my page and smile. 

"You read a lot."

I don't know about a lot. 

Every time walking into a bookstore is an exercise in humility.

There is always more to read. 

There is actually very little I have read. 

"I don't read books."

He wasn't finished.

"I read the Bible."

I ask, what's his favorite part.

"My favorite part?

Yeah, which of the books?

"Romans."

Why, Romans?

I don't remember it.

"Do you know Paul?"

The apostle?

Yes, I say, my dad was named after him.

"Oh, well, he says, you know sin?"

I know sin.

"Basically, we've all sinned. We live in a world of sin. Sin surrounds us."

I nod my head and clock the young family nearby.

Their baby, in a stroller.

[insert more]

"Are you Christian?"

No, I say.

"Oh, well, I was saved in February."

He'd been living in the D.R. becuase New York City wasn't good for him.

He had gotten into trouble, he says, he had to get away.

"So I left, stayed with family out there," he says. "I started going to a Spanish-speaking church, and hearing what they had to say."

He had felt something, so he decided to save himself. 

He let the water wash over him, and he wanted to stay.

But his mom needed him. 

"She needed my help with rent here."

He didn't want to go back, but he did because he loves her.

"I got this job to help pay the bills, for the both of us."

[insert more]

Paul wanted to visit Rome, so he did.

[insert more]

"Can I take this in for you?"

I look down at the cup and saucer, up at him.

It's a very kind offer.

Yes, I say, thank you.

"See you tomorrow."
 
I don't have faith in Monday.

"Or when will I next see you?"

I wasn't sure, Thursday, Friday, or same time Sunday. 

"Well, I'll see you when I see you." 

[insert more]

Love, 

Elizabeth Kolling
