---
title: "Maximilian XI"
author: "Elizabeth Kolling"
date: "2025-07-22T07:57:00"
categories: [Maximilian]
description: " "
---


"It seems to me mid-July is the season of painting en plein air."

"Yeah?"

"Yeah, I saw at least two people painting yesterday, and four the day before."

"What’s your greatest fear?"

"Max, that's kind of a lame question."

"What? No it's not."

"It's cheesy and overdone."

"It's deep and about vulnerability."

"I just can't answer a question like that. I refuse to answer."

"Whatever."

"So, what's yours?"

"Why are you like this?"

"Like what? What am I?"

"Misunderstanding," said Max.

"Misunderstanding? Gee thanks."

"No, Sara. Misunderstanding is my answer to the question. Jeez not everything is about you."

"So your greatest fear is people misunderstanding you?"

"No, it’s more specific than that, and it's not about other people. Not being able to understand, me personally, not being able to understand what I’m reading, like reading a paragraph and reaching the end of it and having no clue what I've just read, having to go back to the beginning and read it again, except it’s the same thing the second time, and then again, and again, and I’m stuck on this page stuck on this paragraph and—"

"I think that happens, and I think part of that's inevitable."

"So you're saying I fear the inevitable?"

"I didn't say that."

