---
title: "Samantha X"
author: "Elizabeth Kolling"
date: "2025-09-24T19:41:00"
categories: [Samantha]
description: " "
---


They were strangers on the third floor, sitting in on Day 2, and there she was one of them, a stranger on the third floor too, just like in the movie. As the technique instructor spoke, her thoughts drifted. She thought of how a leaf falls and what Levi had said, so innocently in the car that one day in late September as the leaves started to turn color. He put on the right blinker, and checked the rearview before turning onto her street, which was a cul-de-sac that some might call a dead end. He didn’t know why he was so nice to her. She didn’t know why he so offered to drive her. It was out of the way, since Marin City was farther south of their high school and he lived northwest in the hills of Mill Valley.

“Everyone is a stranger,” he had said. “Until you get to know them.”

“I don’t know,” she had said. “What about the people you feel like you’ve always known?”

“I know none of the kind.” 

“What about your dad? Haven’t you, I don’t know, always just known him, who he was to you, and his heart?” 

Levi didn’t reply after this. Samantha just turned her head to look straight out again. The lights were on, which meant Tom and Casey were likely still awake. Her stomach sank at the thought of walking through those doors. 

“Everything alright?”

“Yeah,” she said. “I was just thinking.”

“About anything, uh, interesting?”

“Just about what I just said.”

She was thinking of his white scarf, and what it may take. How much of herself would she have to give up and over, to act like Peter Lorre? She wondered whether she’d ever be able to affect someone. She thought maybe she needed those bulging eyes of his, to begin with, in order to have the same effect. 

“Samantha?” said the technique instructor to no response. “Uh, Samantha Flores?”

“Here!” 

She was a bit startled, hearing her name said aloud when she was least expecting it. 

“Do you go by Sam?” 

“Uh, no, just Samantha.” 

“Samantha, it is, then, welcome,” said the technique instructor. “Okay, next we have Summer?” 

“Here.”

“Oh, boy. Two long names, both starting with S. This will be the true test of our time together these coming weeks. For me, of course. You’ll be tested in other ways, but more of that to come. Okay, let’s get through this roll call already, so we can get to the fun part. And ladies, please, please, please correct me if I say your names wrong or confuse the two of you, and seriously I’m so sorry in advance. Samantha, Summer. Samantha, Summer.”

"If it's an issue," said Samantha. "I can go by Sam."

"No, no, no," said the technique instructor. "No issue." 

Summer and Samantha just looked at each other, a few strangers away from each other, at opposite curves of the circle, shrugged their shoulders and smiled. 

[insert more]