---
title: "Samantha V"
author: "Elizabeth Kolling"
date: "2025-08-04T19:45:00"
categories: 
description: " "
---


Samantha was turned around by the nectarines. One had fallen, and, plus, there was a cleanup on aisle eight. 

“Hey.”

“Hi.”

"You work here?"

She shook her head no, then *yes*.

"I thought you worked at the ice cream shop?"

"On the weekends," she said. "Here weekdays."

"Oh," he said. "I didn't know."

"Haha, I didn't expect you to."

"Uh—"

"Any way, it's good to see you, I better go see about—"

“Hey,” Levi said. “I got that book that you recommended.”

“Oh?”

“The play, I mean.”

“Oh, The Sea Gull?”

“No, the one you said was your favorite.”

“The Cherry Orchard?”

She smiled with her eyes at him. Ethan hadn’t read it, though she had recommended it too to him. He said he would, after The Whale, which was all-consuming, but that was back in April and she hadn’t brought it up again because she didn’t want to force him into anything he had no interest in, basically. She didn’t want him to read it. She wanted him to be happy and focus on what brings joy into his days. She wanted to be a part of that *joie de vivre*. She wanted to learn another language besides her own. But most of all, she wanted him to want to read it. She wanted recipriocation, the interest to be mutual, rooted in something real.   

“I read Act One.”

“You did?”

“Yeah.”

“Did you like it?”

“I get what you meant by it,” said Levi. “That this is not a pipe.” 

“Oh, haha, I didn’t get the reference for a second.”

“I realized what you meant by it by the end of the first page.”

“Which part?”

“The part where Varya tells Anya that she is wearing a brooch her mother gave her…the brooch, it looks like a bee.” 

“But it’s not a bee, you mean, it’s a brooch.” 

“Yeah, like what you said to me, how did you say it? I’d butcher the accent if I tried.”

“Ceci,” she said. “N’est pas une pipe.” 

“Ceci,” he said. “N’est pas une bee.”

“Hehe.”

“What’s the French word for bee?”

“I couldn’t tell you.”

“You can’t tell me, or you wouldn’t if you knew?

“I don’t know the French word for bee.”

“Oh.”

“But I’ll tell you when you’re least suspecting.”

“I don’t tend to suspect anything.” 

“Expecting,” Samantha said. “When you’re least expecting.”

“Well, I do have the greatest, the greatest of expectations.”

“Well, then, it’ll be hard to tell you then, but when I do sense a lowering of your expectation, that’s when I’ll hit you with *ceci*, you see.”

“Deal.”

“Ceci une good thing to try sometimes.”