---
title: "Summer XII"
author: "Elizabeth Kolling"
date: "2025-10-07T20:26:00"
categories: [Summer]
description: " "
---

[insert more]

Summer didn’t weep on the downtown W this time, for the first time in the last two weeks. Her stop was Rector Street, and all that quiet confidence she had accumulated through the years had been chipping like the red paint of that one residential building across from the *roastery* just north of Hangman’s Elm. Things with Philip were the same, going in circles. One good night was followed by mourning the next day, and she was thinking of letting go of the metal pole as the train eased into the station. There was no jolt, and another long text to reply to.

They’d met after college ended. Life was beginning to be real, and, even though Philip had studied physics, he was living in the Financial District, working in Finance with one of her friends from summer camp who had also pledged a passion for capital markets in the interview. They both wanted to work in IB for a few years until the Associate level and then switch over to trading (Quant) (Philip had his eyes on one firm in particular, which happened to be the one that Sara’s father ran (insert more later)). 

He had wanted her to move in with him, since her lease was ending and they were coming up on three years of being together, but she wasn’t ready for that sort of commitment. Not with Philip. She didn’t know if he was the one for her. It was more a feeling. She felt this way, because *scared to speak* and *fear of his reaction* were sometimes the feelings before she spoke. He wanted a filtered version, to look at life through rose-colored lenses, her unbothered and never questioning. 

She couldn't help it. She had questions. 

"Are you able to meet this week?" she texted. "I think it may be better for everyone if we continue this conversation in person."

"Thursday," Philip said. "After work." 

"Thursday works," she said. "I can leave work early and meet you down in FiDi at 5. I have class at 6." 

"I don't get off until 10."

Class ended at 10 so that could've been perfect, but she didn't want to meet too late.

"Do you want to do the weekend then?"

"No," he said. "I'll move some things around. I can do five." 

"Okay," she said. "Do you want to meet at Pier 17?" 

"Sure." 

"Sounds good."

Summer tucked her phone into her back pocket and walked into the lobby. 

[insert more]
 
The action she chose was brushing her teeth, and flossing before that. The emotion she was mostly was cautious, though she answered with *mindful* when the technique instructor asked.

“Oh, I still have more—”

“Let’s stop it there,” said the technique instructor. “What are you? What emotion did you choose?”

“Uh, mindful.”

“Mindful, okay, mindful, okay, nice, I think I saw that, mindful.” 

[insert more]