---
title: "Sara II"
author: "Elizabeth Kolling"
date: "2025-07-10T17:41:00"
categories: 
description: " "
---


Sara’s parents and Sara’s parents’ parents and Sara’s parents’ parents’ parents on both sides were patrons of the Metropolitan Museum of Art, old money, which meant her mother didn’t work for a living and spent an hour, maybe two, on the weekends volunteering. 

“Volunteering is the greatest feeling,” she had said to her daughter. “It’s also a form of service, and it’s important what we’re doing, making a difference,” but Sara saw her mother’s motivation as more of a status symbol and something to brag about at dinner parties or a way to stave off her loss. In fact, Sara had tilted her head and furrowed her brow (incomplete agreement) before realizing it. 

“Don’t squint, honey, you’ll get wrinkles.”

Her mother had not even one, thank God and thanks to no injector in high demand on the Upper East Side. The injector’s wife was her surgeon (generally she was against invasive procedures or changing her appearance and she only ever got her nose done), and they owned a practice together, which she thought was sweet. She liked supporting small, family-owned businesses even though she wanted tighter borders and with lower taxes. She didn’t believe in government but she’d give a twenty dollar bill to every woman on the sidewalk or migrant mother trying to sell fresh fruit in Central Park. She’d seen more than one getting arrested by the NYPD. 

“It’s just heartbreaking,” she’d said in her silk gown to the middle-age financier fingering a cigar in front of her.

She, who was known to kiss her husband even though his lips tasted of tobacco, had the view that women weren’t the ones doing drugs. 

“I just can’t picture it.” 

She always carried a banana and a bag of almonds in her purse in case she passed one in NoHo, off the Broadway Lafayette subway stop (which she’d only ever walked past on her way to SoHo). For one, she thought it was important not to spike the blood sugar. Doing so could make a person age five years, according to science or her own fiction, and nuts were good to pair for this purpose (not too many at once, because they contained cyanide and could make you sick). 

Essentially, she gave the men in the streets food instead, she told him, because she didn’t trust them (she didn’t know what use the men would make of the money). 

“I mean, I can’t speak for them,” he had said with a puff and a croak. 

“Won’t you quit?”

“Okay, I’ll quit for you.”

The middle-age financier fingering a cigar in front of her had wanted to study at Juilliard, and he’d gotten in on his own merit, having filled out the application under a pseudonym, but his ill father’s deathbed wish was for his son to take over the boutique firm. He went to Princeton and hadn’t played seriously since the audition. Any way, Sara’s mother could talk for hours. She could listen too as long as her audience was handsome enough, and her husband was handsome.

“Do you regret it?”

“What?”

“Going to Princeton?”

“Not an ounce of it.”

“Regret, you mean?” She said. “Do you regret meeting me?”

“Now, you’re the reason I don’t regret anything.”

“You mean it?”

“If I hadn’t gone to Princeton, I would’ve never seen you from across the room.”

“I thought we met in the library.”

“No it was a party.” 

“Maybe it was both.” 

“So, you’ll quit?”

“I guess.”

“You guess, my love?”

“I will.”

“I just don’t want you to resent me.”

“How could I resent you?” He said, turning to face Sara. “Look what you’ve given me.” 

Sara thought she was in trouble or something but was then relieved when her mother and father turned away to face each other again, only to throw up a little in her mouth at the sight of them flirting with each other in public at a private event. They really loved each other, Catherine and James Ascher, college sweethearts, which was totally gross and rare. 

“You could always start up again,” Catherine said. 

“Hmm?”

“Saxophone.”

Regardless of standing in opposition to some of the things her mother and father represented, Sara couldn’t help but be cut from that same cloth, and the more she heard her say it (volunteering is…) while slurping a farmed shrimp cocktail on a rooftop overlooking the Reservoir, the more she believed it to be incontrovertibly true. Either way, she effectively grew up a the MET. 

At the age of eight months, Sara was climbing the grand steps at a crawl (her mother would set her loose), and by age seven she was manning the information desk (which those on the inside called the pit), and by eleven she was upstairs with events and programming, but by the time she reached high school, she had told her mom that she wanted to help with curating. A phone call was all it took, and she found herself in a room with PhDs who didn’t mind that she had no justification for being there other than where she came from. They had come from the same place, of course. 

Any way, this is how Sara started up volunteering and why she and Max found themselves in Gallery 821 on a Friday, staring at Latour’s *Roses and Lilies*. 

She had broken the silence by saying the roses looked like cabbages.

“No they don’t,” said Max. 

“The lilies look like yearning.”

“I see that.”

She had tilted her head towards him to mirror the slant of the white flowers in the vase. 

“You can tell there’s water in it.”

“Yeah.”

“I like the tension of the stems’ ends against the glass,” she said. “It’s almost like they’re trying to break through, but they can’t.”

“And the leader flower, somehow, it doesn’t bend.”

“Yeah, it looks like it would bend like the ones beneath it.”

“There’s some bend in the stems to the left.”

“Yeah.”

“I can’t quite track the stems to the flowers,” he said. “They all blend.”

“I think that section, where all the stems converge, is my favorite section of the painting.”  

“Yeah.”

“I could stare at it for hours,” she said. “Or a few minutes, and it wouldn’t make a difference.”

It’d been at least three in front of this one, and more than one stranger had come up to it with their iPhone to take a picture only to immediately move on. The two of them saw people do this, time after time, but they were different. Hers was in her purse. His Android, in his jean pocket.