---
title: "Jamal"
author: "Elizabeth Kolling"
date: "2025-09-29T20:07:00"
categories: [Jamal]
description: " "
---

The purple sky after sunset, Jamal thought, on his way up the stairs.

Day or night did it. The way the light changed as he walked Essex made him think of Prince, and Joey who he had happened to meet here at random ten years ago. The thirtieth day of September and April 21, 2016, were two dates he would only ever continue to remember. He’d never forget where he was or when he heard the news. There he was, standing outside the Black Cat, smoking a spliff (what he thought was a mere joint, at first glance), and the headline read: Prince Dead at 57. Kenya and what could have been, another album or two, were on his mind as he walked Rivington past Norfolk and Suffolk that Monday night (the eve of week two).

[insert more]

They mulled one together, later in the night. Really, Jamal watched. 

“Do you always mix them?”

“Hmm?”

“I mean, do you ever roll just weed?”

“Mmm,” said Joey, licking the seal. “I like the taste of the tobacco, and it evens it out.”

"I've never tried it."

"You wanna?"

He did, and didn't.

"Yeah, okay."

"You sure? You don't have to."

"No," said Jamal. "I mean, I want to."

"Haha, okay then."

Joey handed him the roll. Jamal held it, a little unsure where the light would come from.

"Uh, got a lighter?"

"I got you," said Joey. "Here."

He reached for the roll in Jamal's hand and set the end between his lips. 

(Jamal leans in, Joey lights the spliff for him. Jamal inhales way too deeply and coughs until he has to spit. Joey wants to get him water but doesn't want to have to leave him alone in order to get it. So he gives him his beer to clear his throught, and Jamal drinks it even though he doesn't drink. Jamal is out of his element. Joey feels bad.)

[insert more]

Jamal took the F train from Delancey to 14th Street and the 2/3 back uptown to 125th Street. It was no small feat, each commute from Harlem, but it was no big deal either. He put his headphones on, and drowned out the drama of the subway car. The muscles shone through from his white beater, and a young woman sitting across the way kept looking his way. He looked the other way, saw a man with the same mess of curls Joey had had and tried not to hum the lyrics. 

*“I never wanted to be your weekend lover…Honey, I know, I know, I know times are changin’…”*

[insert more]

He worked from home, in customer service for a skincare company. It was his job to manage complaints, assist with returns, recommend alternative products to retain customers, and upsell them. 