---
title: "Samantha XI"
author: "Elizabeth Kolling"
date: "2025-09-24T21:14:00"
categories: [Samantha]
description: " "
---


Samantha was on the A train, thinking of the letter L.

She couldn't escape the thought of Levi, not in any everlasting way. She did what she could, come as it may. She left the office at 5 pm, which was more than fine in order to get downtown by six. This is what it was like to work in Big Tech. Everything in her life was easy, but the hardest part was this feeling that followed her like a shadow wherever she she'd go. She had this overwhelmming feeling that she was doing nothing intrinsically good with her life, but worse than this was the feeling that she was actually doing a very bad thing for society and everyone unawares around her. Everywhere she looked were people with their crowns down, multi-tasking on the walk and totally detached, while riding the subway. The plastic in their ears wrapped around heads like gauze after a car crash. They listened so they wouldn't have to hear. T

She held in her hand a litany of poems (John Keats) that she couldn’t quite quit. Since it was September again, she read his stanzas:

*“You say you love; but with a voice
Chaster than a nun’s, who singeth 
The soft Vespers to herself 
While the chime-bell ringeth—
O love me truly!*

*You say you love; but with a smile
Cold as sunrise in September,
As you were Saint Cupid’s nun,
And kept his weeks of Ember.
O love me truly!*

*You say you love—but then your lips
Coral tinted teach no blisses
More than coral in the sea—
They never pout for kisses—
O love me truly!*

*You say you love; but then your hand
No soft squeeze for squeeze returneth, 
It is like a statue’s, dead—
While mine for passion burneth—
O love me truly!*

*O breathe a word or two of fire!
Smile, as if those words should burn me,
Squeeze as lovers should— O kiss
And in thy heart inure me!
O love me truly!”*

She put the book away and took out her notebook and felt around for a pen. She used the first one she had reached for, the red one, even though she wished it were black. 

Love me the way a feather falls,
Falsely, with ever so slight a resistance, 
She floats. 

The train was edging into Chambers Street, so she knew Fulton was next. She read the poem back, and crossed it out. 

~~Love me the way a feather falls,
Falsely, with ever so slight a resistance, 
She floats.~~

She looked at the strikethrough and realized she hadn't even started to think about her life in five. What was she going to say, and where to start? 