---
title: "Maximilian XXII"
author: "Elizabeth Kolling"
date: "2025-12-07T09:04:00"
categories: [Maximilian]
description: " "
---

[insert more]

(He's talking to his shrink)

"I don't eat. I don't sleep," he said. "I can't walk the park past her parents' apartment. Don't know if they live there anymore."

"Stewart called," said the shrink. "You can't be going around there anymore."

"Who's Stewart."

"The doorman." 

"Well, there's more than one."

"He said the one on night watch has been seeing you sleeping on the bench across 5th Ave."

"That's a lie."

"You don't like your apartment?"

"I prefer the air outside."

"Hard to believe the air's better there."

"There aren't too many cars. You'd be surprised." 

"Sorry, I think I sidetracked you."

"For a shrink you sure talk a lot."

"Would you please refer to me as your therapist."

"I can't control what I say to people. But I won't call you it to your face."

"Okay." 

"I could call you Doc. Short for Doctor, you know."

"Max, we have 10 minutes left for today. How would you like to use our remaining time together?"

"I'd like to share the poem I wrote." 

"Sorry, you were saying. Whenever you're ready."

"I don't eat. / I don't sleep. / I fall asleep to the sound of a shitty pop song. / I can't walk the mile / past her parents' apartment. / Don't know if they live there anymore / I will be like them one day. / Move out the city without a word / Won't look at the art on the walls without looking / over my left shoulder / There's a rainbow, and / I've nowhere to roam. These crowded halls on a late Sunday / Mourning and memories." 

"Thanks, Max, for sharing. How did that feel?"

"It's not a great poem. It's not even a good one, but you have to respect the process. So, you see, it's important to share each iteration. It's an iterative process."

"I heard some kernels."

"Colonels?"

"Like bits of popcorn before it pops."

"That's pretty poetic, Doctor. See, you're a poet."

"I don't know about that." 

"I don't know. When I first met her at school, I thought she hated me. I decided to hate her back, but only on the surface, as a sort of defense. We were like two warring nations in Rhetoric, but it was her on offense."

"Why did you need to hate her, do you think?"

"If I hated her enough...the hate she had for me would then be warranted. But I didn't hate her. I don't hate anyone. I just told myself I did. I do. I've never thought of myself as a likeable person, you know. I mean, I don't know. I met her a second time, and she was different. You know, outside of her usual context. She wasn't the competitive person she was with me. She taught me things. "

"What did she teach you?"

"I mean, everything. But first? How to stand in front of a painting. You know, and see it."

"It sounds like she's left quite an impression."

"She left, you know. But yes, she was someone who..."

"Someone who...Max?"

[insert more]