---
title: "Ethan XIX"
author: "Elizabeth Kolling"
date: "2025-09-06T11:41:00"
categories: [Chapter 15]
description: " "
---

“So, cod or clam?”

“You speak to me in parables.”

“Of course, it may be because I’m hungry, but I’ve been thinking.”

“Yeah?”

“We never even touched the chowder.”

“The chowder?”

“The chowder chapter.”

“We didn’t go over it? I thought we did.”

“I don’t think so.”

“In any case, what is it that has you so stuck on it?”

“The idea of chowder, I guess.”

“Dude, what are you even talking about.”

“Chowder is a stew, right?”

“Yeah, I mean I don’t think it qualifies as soup.”

“Stew is a noun,” said Levi. “But it’s also a verb.”

“Okay.”

“And this book is basically—” 

“A bit of a slow cooker, if you asked me.”

“I *am* asking you, and exactly.”

“So, you’re saying this book is basically chowder.”

“Yes, I don’t think it was random. I think Melville wants to take it slow, to make us stew. He put the chowder chapter in there for a reason.”

“I’m getting tired of all his tricks, but let’s get down to it.”

“I wonder what he was thinking when he wrote this.” 

“Or who he was thinking of. I think Melville got his heartbroken. That’s the real reason he had to leave Manhattan. Sea or imminent death was the only escape from the ache.” 

"Why do we always have to read through a romantic lens. I don't think Ishmael gives a flying farce about women. He has more important things to care about."

Ethan was a little shocked, because Levi didn't normally speak this way. He was like a tea pot reaching heat. What had changed?

Levi lost his cool, because, no matter the method of quelling his madness, the feelings for Samantha remained the same, indisputedly there, which was unfortunate for him and everyone involved, and he thought Ethan did have some redeeming qualities. For instance, he wasn’t afraid to go after what he wanted, which was her, or say it as he saw it, however absurd. Levi exercised more caution, a kind of tenderness and care that manifested as non-action. 
